# -*- coding: utf-8 -*-
"""LT. Герой: senelis Antanas Petraitis, Dzūkija, Varėna. Produktas: Osteomed gelis."""
T = {}
T[0] = '﻿'
T[1] = ('„Kas netiki gamtos galia, niekada nesupras savo kūno" — senelis Antanas Petraitis iš Dzūkijos, '
        'grąžinęs daugiau nei 1700 žmonių džiaugsmą vaikščioti be nė vienos išrašytos cheminės tabletės')
T[2] = 'Specialus reportažas · Sveikata ir savijauta'
T[3] = '+'
T[4] = 'SveikataInfo Lietuva'
T[5] = 'Visuomenės sveikatos reportažai'
T[6] = '„Kas netiki'
T[7] = 'gamtos galia'
T[8] = ', niekada nesupras'
T[9] = 'savo kūno'
T[10] = '."'
T[11] = 'Senelis Antanas Petraitis, liaudies žolininkas iš Dzūkijos, grąžino'
T[12] = 'daugiau nei 1700 žmonių'
T[13] = 'džiaugsmą vaikščioti'
T[14] = 'be nė vienos išrašytos cheminės tabletės'
T[15] = '. Mūsų žurnalistas nuvyko į jo atokią sodybą užduoti svarbiausio klausimo: kaip jam tai pavyksta?'
T[16] = 'Paskelbta:'
T[17] = ', 09:36'
T[18] = ('Dzūkijos miškuose gyvena 72 metų vyras, kurį aplinkiniuose kaimuose paprasčiausiai vadina „seneliu Antanu". '
         'Niekada nebuvo gydytojas. Niekada nestudijavo. Bet per pastaruosius trejus metus išgelbėjo daugiau nei 1700 '
         'žmonių nuo sąnarių skausmo — žmonių, kuriuos net geriausi specialistai jau buvo nurašę. Žmonių, pasmerktų '
         'neįgaliojo vežimėliui. Žmonių, kurie negalėjo atsikelti iš savo lovos. Ir visa tai dėl paprastų gelio '
         'tūtelių, pagamintų savo rankomis — pagal senovinę gamtos išmintį.')
T[19] = ('Antradienio rytą atvykome į Varėną, į miškingus slėnius. Rūkas dar kabojo tarp medžių viršūnių. Paskutinius '
         'kilometrus ėjome pėsčiomis, nes toliau asfaltuoto kelio nebėra. „Ieškote senelio Antano?" — paklausė '
         'vyresnė moteris kaimo gale, su skarele ant galvos. „Sukite kairėn prie mažo akmeninio šulinio. Jo namas '
         'prie šaltinio. Bet paskubėkite, nes vidurdienį jis eina į mišką rinkti vaistažolių."')
T[20] = ('Taip radome Antaną Petraitį — 72 metų liaudies žolininką, visą gyvenimą praleidusį Dzūkijoje ir šiandien '
         'griaunantį vieną didžiausių tabu šalyje: kad sąnarių skausmui yra tikras sprendimas. Sprendimas, kuris '
         'nepriklauso nuo cheminių tablečių, injekcijų ar operacijų. O nuo gamtos, senovinės išminties ir šimtmečių '
         'atminties susitikimo.')
T[21] = ('Artimiausiose vietovėse — Varėnoje, Alytuje, Druskininkuose ir kitur — senelį Antaną pažįsta beveik kiekviena '
         'šeima. Dukterys atveža savo šlubuojančius tėvus, kad jis apžiūrėtų. Žmonos užsako gelio tūteles savo motinoms '
         'senelių namuose. Vyrai ateina po ilgų darbo dienų, kad vėl galėtų vaikščioti. Gydytojas iš rajono sveikatos '
         'centro pripažįsta:')
T[22] = '„Nemoku paaiškinti, kas vyksta su tuo žmogumi. Bet mano pacientai iš tiesų atsigauna."'
T[23] = ('„Devyniolika metų gyvenau su skausmu. Man išrašė dvylika skirtingų vaistų — ir nė vienas nepadėjo. Vieną dieną '
         'sesuo papasakojo apie senelį Antaną. Tris valandas ėjau pas jį pėsčiomis, nes netikėjau. Dabar šį gelį naudoju '
         'jau keturias savaites. Vakar pati nulipau į rūsį atsinešti atsargų. Pirmą kartą per devyniolika metų."')
T[24] = '— Ona, 78 metai, Varėna'
T[25] = ('„Sūnus dirba Anglijoje. Jo žmona nenorėjo gyventi su manimi dėl mano nugaros skausmų. Likau vienas kaimo gale, '
         'name, kurį vos apšildau. Net šuo su manimi nėjo, nes negalėjau paskui jį nueiti. Tada senelis Antanas pats '
         'atėjo pas mane. Ant kelių jam padėkojau. Šiandien pats einu iki šaltinio vandens."')
T[26] = '— Vladas, 71 metai, Alytus'
T[27] = ('Senelis Antanas su viena savo pacienčių, teta Maryte iš Varėnos. „Šių žmonių niekas nelanko. Vaikai išvažiavo, '
         'gydytojai juos nurašė. Bet gamta jų nenurašė. Tereikia įsiklausyti į tai, ką ji šnabžda."')
T[28] = '„Kūnas žino viską. Tereikia nutildyti triukšmą, kad išgirstum, ką jis šnabžda."'
T[29] = ('Pokalbis su seneliu Antanu Dzūkijos širdyje — jo namuose, kur nuo sienų kabo džiovintų žolelių ryšuliai, o '
         'lentynose ilsisi šimtmečių senumo knygos')
T[30] = 'Senelis Antanas Petraitis:'
T[31] = ('„Viską prisimenu taip, tarsi būtų buvę vakar. Anksti auštant, rūkas dar kabojo tarp viršūnių. Sėdėjau prie '
         'savo trobelės šalia ugnies ir ruošiau spygliuočių ištrauką — tada dar savo paties skausmams. Staiga išgirdau '
         'tylius žingsnius. Pasirodė moteris tamsia suknele iki žemės, kokių šešiasdešimties metų. Akys buvo kaip '
         'stovintis vanduo — pilnos baimės. Atsisėdo šalia manęs ant nuversto kamieno ir tarė:')
T[32] = ('„Seneli Antanai, prašau, išgelbėkite mano vyrą. Mano vyras miršta. Sąnariai jam vis labiau stingsta, keliai '
         'sugadinti. Gydytojai nieko daugiau negali padaryti. Negali vaikščioti, negali atsikelti, negali net sėdėti. '
         'Tik guli ir verkia."')
T[33] = ('TĄ AKIMIRKĄ SUPRATAU: IŠMINTIS APIE ŽOLELES, KURIĄ PAVELDĖJAU IŠ SAVO MOKYTOJO, DUOTA NE TIK MAN — BET IR TAI '
         'MOTERIAI BEI JOS VYRUI. TADA NUSPRENDŽIAU JĄ NEŠTI TOLIAU."')
T[34] = ('Senelis Antanas Petraitis, 72 metų liaudies žolininkas iš Dzūkijos. Gyvena mažame akmeniniame name, kurį '
         'septintajame dešimtmetyje pastatė pats, giliai miške. Neturi universiteto diplomo — bet turi mokytoją, iš '
         'kurio jaunystėje išmoko gydomąsias žinias apie žoleles, ir daugiau nei penkiasdešimt metų patirties, kokios '
         'neturi niekas kitas.')
T[35] = ('Senelis Antanas kalba lėtai, kartais su ilgomis pauzėmis — tarsi kiekvieną žodį atskirai svertų. Jo didelės '
         'kaulėtos rankos ilsisi ant kelių. Pirštai išsitepę sakais ir šaknimis, su kuriomis dirba jau šešiasdešimt '
         'penkerius metus. Už jo, ant sienos, kabo džiovinti šalavijo ir kmynų ryšuliai. Lentynose stovi stiklainiai, '
         'maži tamsūs indeliai ir sunki, oda įrišta knyga — itališkas „De Materia Medica" vertimas iš šešioliktojo '
         'amžiaus, paveldėtas iš mokytojo.')
T[36] = ('„Žmonės mano, kad sąnarių skausmai yra natūrali senatvės dalis. Tai melas. Keliai, nugara, klubai — tai kaip '
         'miškas. Jei jį gerai saugai, gyvena šimtmečius. Jei jį alini ir nuodiji, per šešerius ar aštuonerius metus '
         'sugriūva. Šiuolaikinė medicina sąnarių nesaugo. Tik užmigdo skausmą. Ir kasmet išrašo vis daugiau tablečių. '
         'Kol žmogus nugriūva ir nesusilaužo kaulo."')
T[37] = ('„Keturiasdešimt metų dirbau ūkyje. Keldavausi ketvirtą ryto, gulti eidavau aštuntą vakaro. Niekada '
         'nesiskundžiau. Kai klubas atsisakė tarnauti, gydytojas man pasakė: „Ponia Milda, tai metai. Turite priprasti." '
         'Kaip man priprasti? Vos šešiasdešimt penkeri! Vyro nebėra. Vaikai Anglijoje. Esu viena ir negaliu nueiti į '
         'daržą pomidorų. Tada paštininkas papasakojo apie senelį Antaną."')
T[38] = '— Milda, 65 metai, Druskininkai'
T[39] = '„Vaistinės nesako tiesos — nes jei sakytų, bankrutuotų"'
T[40] = 'Senelis Antanas Petraitis aiškina, kodėl tradiciniai vaistai sąnariams daro daugiau žalos nei naudos'
T[41] = 'Senelis Antanas Petraitis:'
T[42] = ('— Papasakosiu, ką matau mėnuo po mėnesio pas tuos, kurie pas mane ateina. Moteris, šešiasdešimt penkerių. Jau '
         'dešimt metų geria priešuždegiminius vaistus. Kelio skausmas kasmet blogėja. Dabar skauda ir skrandį nuo tiek '
         'tablečių. Inkstų tyrimai blogi. Gydytojas išrašo dar vieną tabletę — dabar skrandžiui. Paskui inkstams. O '
         'kelias tuo metu byra. Kremzlės niekas neatstato. Tik skausmas užmigdomas — kol kremzlė visiškai nusidėvi.')
T[43] = ('Tai užburtas ratas: skausmas → tabletė → skausmas grįžta stipresnis → stipresnė tabletė → skrandis kenčia → '
         'dar viena tabletė skrandžiui → inkstas atsisako → o sąnarys tuo metu byra.')
T[44] = 'Niekas nesako tiesos: yra kitas kelias — duoti kremzlei tai, ko jai reikia, ir leisti jai pačiai atsistatyti.'
T[45] = ('Tetos Janinos, 74 metų, iš Alytaus keliai. Trečio laipsnio artrozė — kremzlė beveik visiškai nusidėvėjusi. Jau '
         'penkis mėnesius neišeina iš namų. Ant naktinio staliuko — šešios rūšys tablečių, kurios nieko nepakeitė. Visas '
         'jas atnešė sūnus iš įvairių vaistinių, tikėdamasis, kad kuri nors padės. Nė viena neveikia.')
T[46] = 'Skausmas kelyje, nugaroje ar klube po keturiasdešimt penkerių metų'
T[47] = 'nėra „normalus pagal amžių"'
T[48] = ('— tai ženklas, kad sąnario kremzlė dyla ir kad nyksta sąnario skystis. Kas šį ženklą užgniaužia tabletėmis, '
         'lėtai ir tyliai naikina savo paties sąnarius.')
T[49] = ('Kairėje: sveikas sąnarys su išlikusia kremzle ir pakankamai sąnario skysčio. Dešinėje: sunaikintas sąnarys — '
         'nusidėvėjusi kremzlė, lėtinis uždegimas, kaulas į kaulą. Tokia yra daugelio vyresnių nei 60 metų žmonių '
         'kaimuose tikrovė. Priešuždegiminiai vaistai kremzlės neatstato — tik malšina skausmą, o viskas toliau byra.')
T[50] = ('Priešuždegiminiai vaistai tik blokuoja skausmo signalą, o naikinimas tyliai tęsiasi. Be tikros kremzlės '
         'regeneracijos sąnarys galiausiai visiškai subyra — ir tada lieka tik dvi galimybės: neįgaliojo vežimėlis arba '
         'operacija su endoprotezo įstatymu, kainuojanti visą turtą. Nė viena negrąžina tikro gyvenimo.')
T[51] = 'Senelis Antanas Petraitis:'
T[52] = ('— Suvokite, kaip tai rimta. Daugeliui tų, kurie pas mane ateina, kremzlė kelyje, stubure ar klube sunaikinta '
         'nuo 70 iki 90 procentų. Vaikšto kaulas į kaulą — jei apskritai dar gali vaikščioti. Kiekvienas žingsnis yra '
         'kančia.')
T[53] = 'TRADICINĖS TABLETĖS KREMZLĖS ATSTATYTI NEGALI — JOS TIK SLEPIA SKAUSMĄ, KOL VISKAS BYRA!'
T[54] = ('O žinote, kas man labiausiai skauda krūtinėje? Tai, kad šie žmonės vieni. Vaikai išvažiavo į Angliją, Norvegiją, '
         'Airiją, Vokietiją. Vaistinė vaistus atveža kartą per savaitę. Gydytojas juos mato kartą per metus. O tuo metu '
         'jie tyliai byra. Nugara, keliai, klubai. Ilgainiui bijo net išeiti iš namų, kad nenugriūtų. Todėl darau tai, '
         'ką darau.')
T[55] = ('„Keturiasdešimt dvejus metus dirbau ūkyje. Melžiau karves, kasiau bulves, nešiau malkas. Niekada '
         'nesiskundžiau. Paskui vieną rytą, sulaukusi šešiasdešimties, negalėjau atsikelti iš lovos. Kelias buvo kaip '
         'akmuo. Dukra dirba Norvegijoje. Telefonu pasakė, kad važiuočiau į Vilnių pas specialistą. Kaip man važiuoti? '
         'Net laiptais nulipti negaliu. Senelis Antanas atėjo pas mane, pusę dienos ėjo pėsčiomis. Per dvi savaites jau '
         'dirbau darže."')
T[56] = '— Kazė, 72 metai, netoli Akmenės'
T[57] = ('„Trisdešimt metų dirbau karjere Akmenėje. Nugarą skaudėjo dar nuo keturiasdešimties. Sulaukęs septyniasdešimties '
         'negalėjau net stačias stovėti. Diskopatija, išialgija — gydytojai sugalvodavo pavadinimus, o skausmas '
         'nesiliovė. Sūnus stato Anglijoje. Siunčia pinigus, bet neturi laiko aplankyti. Su senelio Antano geliu po '
         'keturių savaičių vėl užlipau ant stogo jo taisyti — pirmą kartą per šešerius metus."')
T[58] = '— Rimas, 70 metų, buvęs karjero darbininkas iš Akmenės'
T[59] = 'Istorijos, kurių niekada nepamiršiu — ir istorijos, kurios pakeis tai, kaip žiūrite į gamtos galią'
T[60] = 'Senelis Antanas Petraitis:'
T[61] = ('— Papasakosiu, ką matau kiekvieną savaitę. Nekalbu apie statistiką. Apie žmones. Apie žmones su vardais, '
         'turinčius šeimą, turinčius savo istorijas. Apie žmones, kuriuos medicina jau nurašė — o gamta jų dar nenurašė.')
T[62] = ('Teta Genė, 77 metų, iš Varėnos. Reumatoidinis artritas abiejose rankose — negalėjo išlaikyti net šaukšto. Vyras '
         'jai mirė prieš dvejus metus. Dukra dirba Norvegijoje. „Vaistinėje man davė 12 skirtingų vaistų. Visi kenkė '
         'skrandžiui, o sąnarį skaudėjo taip pat. Senelis Antanas atėjo pas mane, kai paštininkas jam pasakė, kad '
         'nebegaliu net bulvės nuskusti."')
T[63] = ('„Rytais žiūrėdavau į savo rankas ir jų nepažindavau — buvo ištinusios, iškrypusios, tarsi ne mano. Negalėjau '
         'nei susišukuoti, nei pomidoro supjaustyti. Su senelio Antano geliu po dviejų savaičių jau nėriau vąšeliu. '
         'Vakar baigiau savo pirmąją kalėdinę staltiesėlę — pirmą kartą per visus metus. Žiūriu į ją ir verkiu."')
T[64] = '— Teta Genė, 77 metai'
T[65] = ('Senelis Petras, 75 metų, iš Alytaus. Diskopatija L4-L5, abipusė koksartrozė. Jau aštuonis mėnesius nesikėlė. '
         '„Sakė, kad esu per senas operacijai. Kad turiu su tuo susitaikyti. Kad neturiu vilties. Senelis Antanas '
         'paprasčiausiai atsisėdo šalia, paėmė mane už kelio ir pasakė: „Petrai, po dviejų savaičių einame kartu į '
         'daržą." Taip ir buvo."')
T[66] = ('„Keturiasdešimt penkerius metus buvau traktorininkas ūkyje. Suariau pusę rajono. O paskui vieną rytą negalėjau '
         'net galvos nuo pagalvės pakelti. Du mano vaikai dirba Airijoje. Siunčia pinigus ir kviečia Kalėdoms. Bet kas '
         'man paduos vandens, jei naktį užspringsiu nuo kosulio? Su senelio Antano geliu po keturių savaičių vėl '
         'skaldžiau malkas. Nedaug — bet pakankamai, kad pats apsišildyčiau."')
T[67] = '— Senelis Petras, 75 metai'
T[68] = 'Štai simptomai, kuriuos matau dažniausiai — ir kuriuos milijonai žmonių nevertina rimtai, manydami, kad tai „tik metai":'
T[69] = 'Aštrus skausmas kelyje lipant laiptais aukštyn ar žemyn — arba prie kiekvieno judesio;'
T[70] = 'Rytinis sustingimas — kūnas „medinis", nejuda 30–60 minučių po pabudimo;'
T[71] = 'Lėtinis nugaros skausmas — negali pasilenkti, negali atsikelti iš lovos;'
T[72] = 'Patinimai keliuose, kulkšnyse ar pirštuose;'
T[73] = 'Girgždėjimas ir traškėjimas sąnariuose prie kiekvieno judesio;'
T[74] = 'Skausmas klube, plintantis į šlaunį — negali nueiti daugiau nei 50 metrų;'
T[75] = 'Deformuoti, sumazgyti pirštai — negali paimti daiktų;'
T[76] = 'Tirpimas kojose ar rankose — diskopatijos arba suspausto nervo ženklas;'
T[77] = 'Jausmas, tarsi „peilis" kryžkaulyje tiesinant nugarą;'
T[78] = 'Susikūprinusi nugara, iškrypusi laikysena — progresuojanti kifozė;'
T[79] = 'Naktinis skausmas, neleidžiantis miegoti — pabunda 4–5 kartus per naktį;'
T[80] = 'Kiekvienas iš šių simptomų yra pavojaus signalas. Ir po 45-erių ar 50-ies metų jų ignoravimas veda į vieną vienintelę pabaigą:'
T[81] = ('VISIŠKAS NEJUDRUMAS, NEĮGALIOJO VEŽIMĖLIS, VISIŠKA PRIKLAUSOMYBĖ NUO KITŲ — IR DAUGELIU ATVEJŲ APGYVENDINIMAS '
         'SENELIŲ NAMUOSE, KUR VAIKAI ATVAŽIUOJA TIK KARTĄ PER METUS.')
T[82] = ('Kiekviena diena, praleista su negydomais sąnariais, artina jus prie visiško nejudrumo! Tūkstančiai Lietuvos '
         'pensininkų atsidūrė senelių namuose būtent todėl, kad skausmo nevertino rimtai — arba gėrė tik tabletes, '
         'kurios problemos neišsprendė. Veikite dabar — dėl savęs arba dėl savo artimųjų — kol dar nevėlu!')
T[83] = '„Mano mokytojas mane išmokė: kiekvienam skausmui gamta turi atsakymą — jei žinai, kur ieškoti"'
T[84] = 'Kaip senelis Antanas Petraitis rado formulę, kurią šiandien naudoja daugiau nei 1700 žmonių iš Dzūkijos kaimų'
T[85] = 'Senelis Antanas Petraitis:'
T[86] = ('— Kitą dieną nuėjau pažiūrėti tos moters vyro. Namas buvo prieblandoje. Žmogus atrodė kaip išdžiūvęs grybas — '
         'sausas, gelsvas. Kūnas dar buvo šiltas, o žvilgsnis jau atsisveikino su pasauliu. Atsisėdau šalia, paėmiau už '
         'rankos ir paklausiau: „Kiek metų jau gyveni su tuo skausmu, broli?" Tylėjo. Ašara nuriedėjo skruostu. '
         '„Devyniolika metų," sušnabždėjo. „Ir niekas nežino, kaip man padėti. Visi tik išrašo vaistus."')
T[87] = ('Tada prisiminiau seną įrašą. Prieš daugelį metų savo mokytojo palikime radau pamirštą sąsiuvinį — itališką '
         'šešioliktojo amžiaus žolyną, didžiojo Dioskorido „De Materia Medica" vertimą. Viename puslapyje buvo parašyta:')
T[88] = ('„Vidinė kūno ugnis vagia sąnariams jų drėgmę ir lankstumą. Tik tas, kuris pažįsta medžio ašarą — sakus, '
         'saugančius žmogaus audinio atmintį — gali grąžinti gyvybę jų kaulams."')
T[89] = ('Žolynas, kurį senelis Antanas paveldėjo iš savo mokytojo. „Ši knyga saugojo išmintį du šimtus metų, kol jos '
         'neradau. Visos žolelės, kurios patenka į Osteomed, yra šiuose puslapiuose."')
T[90] = ('Žinoma, tai nebuvo mokslinis paaiškinimas — o išmintis, perduodama iš kartos į kartą. Bet tada dar nežinojau, '
         'kad ta diena bus trejų metų darbo pradžia. Trejų metų, per kuriuos savo mokytojų palikimą ir miško dovanas '
         'sujungiau į paprastas gelio tūteles, pagamintas rankomis — kurios gali atstatyti kremzlę iš vidaus, negeriant '
         'cheminių tablečių.')

# ---------- 91–180 ----------
T[91] = 'Ką sudėties turi senelio Antano gaminamas gelis:'
T[92] = 'Spygliuočių sakai iš Dzūkijos miškų — medžio ašara'
T[93] = ('Spygliuočių sakai — kuriuos mano mokytojas vadino „medžio ašara". Tradicinė liaudies medicina juos šimtmečius '
         'naudoja sąnarių skausmui. Natūrali priešuždegiminė medžiaga, stabdanti kremzlės irimą ir žadinanti regeneraciją')
T[94] = 'Gliukozaminas ir chondroitinas — natūralios formos'
T[95] = 'Kremzlės plytos — senovinė gamtos atsarga, kurią ląstelės atpažįsta ir panaudoja'
T[96] = 'Hialurono rūgštis — mažų molekulių pavidalu'
T[97] = 'Grąžina sąnariui drėgmę — tai, ką gamta skyrė žmogaus kūnui ir ką atėmė uždegimas'
T[98] = 'II tipo kolagenas ir MSM'
T[99] = 'Stiprina raiščius ir sausgysles aplink sąnarį — natūralų apsauginį tinklą, kuris su metais silpsta'
T[100] = 'Kamparas ir kalnų arnika'
T[101] = 'Akimirksniu palengvina skausmą ir patinimą — kaip sakydavo mano mokytojas: „medžio dvasia, gesinanti ugnį"'
T[102] = ('Gelyje yra dar 14 kitų retų augalinių ekstraktų, kuriuos senelis Antanas ir jo pagalbininkai renka Dzūkijos '
          'miškuose per šešias savaites — kasmet, tik vieną kartą per metus, kai augalai yra visiškos brandos. '
          'Proporcijų senelis Antanas išmoko iš savo mokytojo ir kiekvieną žingsnį atlieka savo rankomis.')
T[103] = 'Taip atsirado gelis Osteomed — pagamintas rankomis, su geriausiomis Dzūkijos vaistažolėmis'
T[104] = 'Senelis Antanas Petraitis:'
T[105] = ('— Jis negimsta laboratorijoje. Jis gimsta mano dirbtuvėje, čia, miško pakraštyje. Spygliuočių sakus renkame '
          'aš ir mano pagalbininkai — senose eglynuose, aukščiausiose kalvose, kur medžiai šimtmečius verkia savo '
          'ašaromis. Ir kitas vaistažoles renkame čia pat, pamiškėse. Rinkimas užtrunka šešias savaites, nes kiekvieną '
          'augalą reikia nupjauti tiksliai jo brandos akimirką. Paskui gelį gaminame mažomis partijomis ir pakuojame '
          'rankomis. Per dieną galime pagaminti daugiausia 70 gelio tūtelių — ne daugiau, nes tai sugadintų kokybę.')
T[106] = ('Senelio Antano dirbtuvė miško pakraštyje. Ant lentynų kabo išdžiovinti šalavijų, medetkų ir erškėtuogių '
          'pundeliai. Čia gimsta kiekviena Osteomed tūtelė — rankomis, mažomis partijomis.')
T[107] = ('Gelio pagrindas — 200 metų senumo receptas, kurį man paliko mano mokytojas. Šiuolaikine mokslo kalba tariant: '
          'koncentruotų augalinių ekstraktų derinys leidžia veikliosioms medžiagoms įsigerti į kūną ir su krauju '
          'pasiekti patį sąnario dangalą, kur yra ardoma kremzlė. Poveikis penkis kartus stipresnis už bet kurį papildą '
          'iš vaistinės, nes gamta tiksliai žino, kaip bendradarbiauti su žmogaus kūnu. O gelio pranašumas prieš '
          'įprastus kremus ir losjonus tas, kad jis prasiskverbia giliau — iki pat sąnario dangalo, o ne lieka tik odos '
          'paviršiuje. Užtepate tiksliai ten, kur skauda: ant kelio, nugaros, klubo, rankų ar kaklo — be tablečių, '
          'einančių per skrandį. Vyresniems žmonėms, gyvenantiems vieniems, tai reiškia paprastą naudojimą ir '
          'savarankiškumą.')
T[108] = ('Osteomed nėra konkurentas. Jis nenori varžytis. Jis nori tik padėti. Kiekviena sudedamoji dalis — tikslia '
          'proporcija — žadina kremzlės regeneraciją, sinovinio skysčio atsinaujinimą ir uždegimo nuslopinimą. Tai '
          'vienintelė priemonė, veikianti ląstelių lygmeniu ir tuo pačiu metu pasiekianti visas pažeistas vietas — '
          'kelius, nugarą, klubus, rankas, kaklą — iš vidaus. Ir svarbiausia: jis veikia ir sulaukus 70, 80, 85 metų! '
          'Mano pirmieji pacientai buvo patys vyriausi — žmonės, kuriuos visi jau buvo nurašę.')
T[109] = 'Senelis Antanas Petraitis:'
T[110] = ('— Pirmoji moteris, kuriai daviau šį gelį, keturis mėnesius nebuvo atsikėlusi iš lovos. Tai buvo teta Marytė '
          'iš Varėnos. Trečią dieną ji pati atėjo į virtuvę ir išvirė man kavos. Abu verkėme. Ji — nes pirmą kartą po '
          'daugelio metų ne kiekvienas judesys skaudėjo. Aš — nes tą akimirką supratau, kad mano mokytojo palikimas '
          'gyvas. Kad visus tuos metus dirbau ne veltui.')
T[111] = 'Osteomed keturiais būdais padeda jums grąžinti džiaugsmą vaikščioti — bet kokio amžiaus'
T[112] = 'Keturi pagrindiniai gelio Osteomed veikimo būdai:'
T[113] = 'Skausmo ir uždegimo pašalinimas'
T[114] = ('Jau per pirmas 30–45 minutes po užtepimo spygliuočių sakų, arnikos ir kamparo derinys mažina skausmą ir '
          'uždegimą. Jis neblokuoja nervinio signalo (kaip įprastos cheminės tabletės) — o ramina patį uždegimo '
          'šaltinį, ten, kur prasideda problema.')
T[115] = 'Kremzlės atstatymas'
T[116] = ('Gliukozaminas, chondroitinas ir II tipo kolagenas pasiekia sąnario dangalą ir žadina kremzlės ląsteles '
          '(chondrocitus), kurios pradeda kurti naują kremzlinį audinį. Šis procesas prasideda po 3–5 reguliaraus '
          'naudojimo dienų.')
T[117] = 'Sinovinio skysčio atsinaujinimas'
T[118] = ('Hialurono rūgštis iš mažų molekulių įsigeria į kūną ir atstato sinovinį skystį — natūralų sąnario „tepalą". '
          'Dėl to kaulai nebesitrina vienas į kitą, o judesys tampa lengvas ir neskausmingas.')
T[119] = 'Ilgalaikė apsauga ir profilaktika'
T[120] = ('MSM ir mineralų kompleksas stiprina raiščius bei sausgysles aplink sąnarį ir užkerta kelią būsimiems '
          'pažeidimams. Po 30–60 naudojimo dienų sąnarys gauna stabilią apsaugą, trunkančią kelis mėnesius.')
T[121] = 'Istorijos, kurias senelis Antanas pasakoja pats — apie žmones, kurie vėl vaikšto'
T[122] = 'Senelis Antanas Petraitis:'
T[123] = ('— Papasakosiu jums apie kai kuriuos iš tų, kuriuos matau kas savaitę. Apie žmones, kuriems niekas nedavė '
          'šanso — nei gydytojai, nei šeima. Apie žmones, kurie vėl vaikšto.')
T[124] = 'Teta Marytė, 82 metai, Varėna.'
T[125] = ('Keturis mėnesius nebuvo atsikėlusi iš lovos. Trečią Osteomed naudojimo dieną pati žengė pirmus žingsnius. Po '
          '30 dienų išeina į kiemą be pagalbos. „To niekas nesitikėjo. Nei aš pati. Senelis Antanas ateina kartą per '
          'savaitę. Tik pažiūri, paliečia kelį ir linkteli galva."')
T[126] = 'Rezultatas po 30 dienų:'
T[127] = 'Savarankiškas vaikščiojimas, rytinis sustingimas dingo, skausmas nukrito nuo 9/10 iki 2/10.'
T[128] = 'Senelis Rimas, 70 metų, buvęs karjero darbininkas iš Akmenės.'
T[129] = ('Diskopatija, išialgija, negalėjo stovėti ilgiau nei 5 minutes. Po 6 savaičių — grįžo į savo daržą, apdirba '
          'dvi lysves per dieną. „Maniau, kad mano nugara visam laikui sugriauta. Buvau pasiruošęs sutikti su neįgaliojo '
          'gyvenimu. Apsirikau. Su senelio Antano geliu jaučiuosi dvidešimčia metų jaunesnis."')
T[130] = 'Rezultatas po 45 dienų:'
T[131] = 'Aštrus skausmas kryžkaulyje dingo, judrumas grįžo, pirmą kartą po 4 metų giliai išmiegojo visą naktį.'
T[132] = 'Kodėl Osteomed nėra vaistinėse? Ir kaip jį gauti?'
T[133] = 'Senelis Antanas Petraitis:'
T[134] = ('Atvirai kalbant, Osteomed gamyba yra sunkus ir lėtas procesas. Žaliavos retos — spygliuočių sakus galima '
          'rinkti tik senuose eglynuose, kitas žoleles rankomis pamiškėse, o turime vos šešių savaičių langą per metus, '
          'kai augalai visiškai subrendę. Per dieną senelio Antano dirbtuvėje galime pagaminti daugiausia 70 tūtelių. '
          'Negalime patenkinti visų užklausų.')
T[135] = ('Praeis dar bent 2–3 metai, kol Osteomed pasieks vaistines. Iki tol jis prieinamas visoje šalies teritorijoje '
          'tik internetu, paramos programose, kurios atsidaro du kartus per metus.')
T[136] = 'Nuolaida gali siekti 50 %'
T[137] = '— o tai ypač svarbu kaimo pensininkams Lietuvoje, gyvenantiems iš mažos pensijos.'
T[138] = ('Kai vaistinėse sužinojo, kad šie geliai iš tiesų veikia — net esant pažengusiai artrozei ir diskopatijai — '
          'norėjo už juos imti po 129 EUR už tūtelę. Pasakiau jiems: „Nedirbu dėl pinigų. Mano mokytojas man nemokamai '
          'atidavė viską, ką žinojo. Neapiplėšiu Lietuvos pensininkų." Vaistinės manęs atsisakė. Po kelių dienų mane '
          'ėmė lankyti žmonės iš sveikatos inspekcijos. Prašė dokumentų. Norėjo nubausti. Bet nepasidaviau. Tada mano '
          'gyvenime atsirado jaunas vyras iš Vilniaus. Jo motiną prieš trejus metus išgydžiau nuo sunkios kelių '
          'artrozės — jį ir jo motiną seniai buvau pamiršęs. Dabar jis grįžo. Pasakė: „Seneli Antanai, tu čia miške '
          'savo rankomis darai stebuklus. Bet Lietuvoje yra tūkstančiai kenčiančių žmonių, kurie niekada čia '
          'neatvažiuos. Leisk man padėti." Jis sutvarkė, kad geliai, pagaminti mano įrankiais, būtų pakuojami švarioje '
          'dirbtuvėje į sterilias tūteles, kad kurjerių tarnyba juos pristatytų po visą šalį ir kad maža komanda '
          'atsakytų į telefonus. Aš juos vis dar gaminu čia, savo tempu. Jis rūpinasi tik tuo, kad jie pasiektų tuos, '
          'kuriems reikia.')
T[139] = 'Kaina, prie kurios priėjome:'
T[140] = 'Kaina, kurios prašė vaistinės'
T[141] = '129 EUR'
T[142] = 'Kaina kitose regiono šalyse'
T[143] = '99 EUR'
T[144] = 'Kaina, kurią siūlome šiandien'
T[145] = '78 EUR'
T[146] = 'Su nuolaida skaitytojams šiandien'
T[147] = '39 EUR'
T[148] = ('Prašau jūsų: NEPRALEISKITE ŠIOS PROGRAMOS! Ne tik dėl savęs — bet ir dėl tėvų, senelių, artimų giminaičių, '
          'kurie galbūt kenčia tyliai. Arba dėl tų, kurie jau senelių namuose, vieni, ir kuriems niekas nieko '
          'nesiunčia. Būkite tas, kuris pakeičia viską.')
T[149] = 'Užsakymui naudokite žemiau esančią formą.'
T[150] = ('Paskutinė proga šiemet gauti Osteomed — sau arba artimam žmogui, kuris kenčia tyliai')
T[151] = 'Senelis Antanas Petraitis:'
T[152] = ('— Rezervavau 20 000 tūtelių išskirtinai šio portalo skaitytojams. Kiekvienas Lietuvos gyventojas, vyresnis '
          'nei 40 metų, gali gauti')
T[153] = '50 % nuolaidą'
T[154] = ', bet programa užsidaro'
T[155] = '.'
T[156] = ('Nelaukite, kol nebegalėsite užlipti laiptais. Kol keliai galutinai neišduos. Kol nugara neužsiblokuos. Ir '
          'svarbiausia — nelaukite, kol tapsite „našta" artimiesiems. Vienas kursas pažadina natūralią kremzlės '
          'regeneraciją — ir nuo tos akimirkos kūnas dirba pats. Nereikia gydytis visą gyvenimą, nereikia cheminių '
          'tablečių, nėra grįžtančio skausmo. Vienas žingsnis, ir jūsų kūnas prisimins, kaip gyventi.')
T[157] = ('Įrašykite savo vardą ir telefono numerį. Konsultantas jums paskambins, parinks tinkamą programą ir sutvarkys '
          'pristatymą per 2–3 dienas kurjerių tarnyba tiesiai į jūsų adresą, visoje Lietuvoje.')
T[158] = ('Su meile ir rūpesčiu — senelis Antanas Petraitis. Rūpinkitės savo artimaisiais. Galbūt vienintelis dalykas, '
          'kurio jiems reikia, yra žinoti, kad jie nepamiršti.')
T[159] = 'Atnaujinta:'
T[160] = ':'
T[161] = 'Dėl išskirtinio susidomėjimo atsargos gali baigtis greičiau, nei numatyta! Šiandien —'
T[162] = '— paskutinė programos diena'
T[163] = 'arba iki atsargų pabaigos.'
T[164] = 'Dėmesio! Neuždarykite ir neatnaujinkite puslapio, kitaip jūsų Osteomed tūtelė bus pasiūlyta kitam žmogui!'
T[165] = 'Galite dalyvauti pasiūlyme — jūsų vieta rezervuota:'
T[166] = 'Nr.'
T[167] = '19'
T[168] = '974'
T[169] = 'Oficiali užsakymo forma'
T[170] = 'Nr.'
T[171] = '19'
T[172] = '974'
T[173] = '/'
T[174] = '20 000'
T[175] = 'Norėdami gauti'
T[176] = '50 % nuolaidą'
T[177] = 'įrašykite savo vardą ir telefono numerį į laukelius žemiau ir paspauskite mygtuką „UŽSAKYTI".'
T[178] = 'Prieinama:'
T[179] = '33'
T[180] = '/1000'

# ---------- 181–273 ----------
T[181] = '78 EUR'
T[182] = '39 EUR'
T[183] = 'Vardas'
T[184] = 'Telefono numeris'
T[185] = 'UŽSAKYTI DABAR'
T[186] = '✔️ Garantuotas pristatymas sertifikuotu kurjeriu'
T[187] = 'tiesiai jūsų nurodytu adresu'
T[188] = 'KOMENTARAI'
T[189] = 'Rasa Jankauskienė'
T[190] = 'Prieš 2 valandas'
T[191] = ('Verkiau, kol tai skaičiau. Mamai 76 metai, jau dvejus metus ji senelių namuose Kaune — būtent todėl, kad keliai '
          'ją išdavė, o aš negalėjau ja pasirūpinti. Tai mano didžiausia kaltė. Užsakiau jai Osteomed. Tikiuosi, kad dar '
          'ne vėlu. Duok Dieve, kad padėtų.')
T[192] = 'Vida Butkienė'
T[193] = 'Prieš 5 valandas'
T[194] = ('Praėjusį penktadienį gavau Osteomed. Ryte ir vakare tepu gelį. Per 5 dienas skausmas gerokai atlėgo, galiu '
          'lipti laiptais žemyn nesilaikydama turėklo! Istorija apie senelį Antaną mane įtikino užsakyti. Nepaprastas '
          'žmogus, iš tiesų.')
T[195] = 'Danutė Šimkienė'
T[196] = 'Prieš 8 valandas'
T[197] = ('Man 69 metai. Ketverius metus kankinausi su nugara — diskopatija ir išialgija. Negalėjau net pasilenkti '
          'batraiščių užsirišti. Gydytojai išrašė priešuždegiminių vaistų, kurie sugadino skrandį. Po 3 savaičių su '
          'Osteomed skausmas beveik dingo. Pati einu į turgų, gaminu valgyti. Susigrąžinau savo gyvenimą, ačiū Dievui.')
T[198] = 'Gintaras Kavaliauskas'
T[199] = 'Prieš 12 valandų'
T[200] = ('Dirbu po 10 valandų per dieną biure Vilniuje. Nugara ir kaklas nebereaguoja. Gydytojas pasakė: „Arba keiti '
          'darbą, arba operacija." Pasirinkau gelį Osteomed. Po 5 savaičių — nė pėdsako skausmo. Ir didžiulė pagarba '
          'seneliui Antanui — pasaulyje, kur visi nori pinigų, jis pėsčiomis eina pas pamirštus senukus miške.')
T[201] = 'Laima Norkienė'
T[202] = 'Prieš 14 valandų'
T[203] = ('Atvirai sakant, netikėjau. Tiek daug dalykų reklamuojama internete, kad praradau pasitikėjimą. Šį tekstą '
          'perskaičiau tik todėl, kad mano anyta negali vaikščioti, o aš nusivylusi. Užsakiau galvodama „jei nepadės, '
          'prarasiu 39 €". Praėjo 3 savaitės. Anyta vakar pati atsistojo iš fotelio! Mano anyta! Kuri nebuvo atsikėlusi '
          '8 mėnesius. Dabar nežinau, ką pasakyti. Rašau tiems, kurie abejoja kaip aš.')
T[204] = 'Darius Mikalauskas'
T[205] = 'Prieš 16 valandų'
T[206] = ('Užsakiau 3 tūteles — sau (keliai), žmonai (rankos, artritas) ir žmonos tėvui senelių namuose. Negalime jo '
          'dažnai lankyti, tai bent atsiųsime tai, ko jam reikia. Tikiuosi, kad ir jam padės. Ačiū už šį straipsnį.')
T[207] = 'Danguolė Ruškienė'
T[208] = 'Prieš 18 valandų'
T[209] = ('Svarstau, ar užsakyti tėčiui. Jau 3 metus jis senelių namuose — keliai visiškai nebedirba. Pasidavė, vos '
          'kalba. Kaip manote, ar Osteomed gali padėti ir sulaukus 78 metų?')
T[210] = 'Marija Gudaitienė'
T[211] = 'Prieš 17 valandų'
T[212] = ('Danguole, mano mamai 82 metai! Sunkus artritas abiejuose keliuose, nebuvo atsikėlusi iš lovos. Jau 2 mėnesius '
          'naudoja Osteomed — dabar pati išeina į kiemą. Neperdedu. Ir gražiausia: kai ją aplankiau, ji manęs laukė '
          'stovėdama tarpduryje! Kartu verkėme. Užsakyk nedvejodama, tavo tėtis nusipelno progos.')
T[213] = 'Zigmas Sakalauskas'
T[214] = 'Prieš 15 valandų'
T[215] = ('Danguole, užsakykite drąsiai. Man 78 metai, buvau per žingsnį nuo neįgaliojo vežimėlio — koksartrozė. '
          'Osteomed per 2 mėnesius pastatė mane ant kojų. Tiesiogine prasme. Tėvas nusipelno daugiau nei senelių namų.')
T[216] = 'Jolanta Andriuškevičienė'
T[217] = 'Prieš 20 valandų'
T[218] = ('Vieną savaitę tepu gelį ant kelių ir kryžkaulio. Ryte jau nebesu „medinė lazda". Galiu pasilenkti, galiu '
          'atsistoti be „ojoj". Užsakiau ir kaimynei, jai 73 metai ir gyvena viena, vaikščiodama laikosi sienų.')
T[219] = 'Sigita Vaitkienė'
T[220] = 'Prieš 1 dieną'
T[221] = ('Prisipažįstu — šį straipsnį skaičiau nepasitikėdama. Turiu patirties su produktais, kurie žada viską. Bet '
          'istorija apie senelį Antaną mane užkariavo ir nusprendžiau pabandyti, nes keliai kankina jau 5 metus. Po '
          'mėnesio — galiu kasti darže! Nesakau, kad tai stebuklas. Sakau, kad veikia. Duokite jam progą.')
T[222] = 'Stasė Tamošaitienė'
T[223] = 'Prieš 1 dieną'
T[224] = ('Man 82 metai. Pernai negalėjau net pati nueiti į tualetą. Vaikai kalbėjo, kad atiduos mane į senelių namus. '
          'Išbandžiau Osteomed — be didelių vilčių. Ir VEIKIA!!! Vaikštau pati, rengiuosi pati, pati nueinu iki durų. '
          'Vaikai apie senelių namus nebeužsimena. Tai mano didžiausia laimė.')
T[225] = 'Bronius Paulauskas'
T[226] = 'Prieš 1 dieną'
T[227] = ('Mano žmona negalėjo net laiptais nulipti. Laikėsi už sienos ir verkė iš skausmo. Maniau, kad ją prarandu — '
          'ne dėl ligos, o dėl nevilties. Užsakiau Osteomed su nuolaida. Po 4 savaičių ji vakar pati nuėjo į turgų ir '
          'grįžo su gėlėmis. Su gėlėmis! Ačiū iš visos širdies.')
T[228] = 'Jūratė Kazlauskienė'
T[229] = 'Prieš 1 dieną'
T[230] = ('Užsakiau keturias tūteles — mamai (namuose, keliai), tėčiui (namuose, nugara) ir dvi sau (rankos, pirštų '
          'artritas, negalėjau rašyti). Istorijos iš straipsnio mane sujaudino. Nebeturiu pasiteisinimų.')
T[231] = 'Stanislava Gaidienė'
T[232] = 'Prieš 2 dienas'
T[233] = ('Gavau Osteomed — kurjeris pristatė per 2 dienas! Gelį jau perdaviau mamai į senelių namus. Širdyje turiu '
          'viltį. Šį straipsnį siunčiu ir personalui — gal jie paskambins seneliui Antanui.')
T[234] = 'Egidijus Lazauskas'
T[235] = 'Prieš 2 dienas'
T[236] = ('Ieškojau Osteomed vaistinėse — neturi. Pasakė, kad reikia užsisakyti šiame puslapyje. Tikiuosi, kad dar yra. '
          'Mano seneliui jo skubiai reikia — jam 81 metai ir jis nebegali vaikščioti.')
T[237] = 'Marytė Vaičiulienė'
T[238] = 'Prieš 3 dienas'
T[239] = ('Klausimas tiems, kurie jau naudoja: kiek kartų per dieną tepamas gelis ir kiek trunka vienas kursas? '
          'Straipsnyje perskaičiau paskubomis ir neįsiminiau.')
T[240] = 'Audrius Paulaitis'
T[241] = 'Prieš 3 dienas'
T[242] = ('Maryte, viršuje tekste parašyta: trumpiausias kursas, kurį rekomenduoja senelis Antanas, yra 30 dienų, esant '
          'sunkesnėms problemoms 60 arba 90 dienų. Gelis tepamas ant skaudamos vietos. Jei nesate tikra, paklauskite '
          'konsultanto, kai jis paskambins — man viską paaiškino telefonu.')
T[243] = 'Skaitytojo atsiųsta nuotrauka.'
T[244] = 'Irena Savickienė'
T[245] = 'Prieš 4 dienas'
T[246] = 'Ar reikia ką nors mokėti iš anksto, kai pateikiamas užsakymas šiame puslapyje? Nenoriai duodu kortelės duomenis.'
T[247] = 'Robertas Rakauskas'
T[248] = 'Prieš 4 dienas'
T[249] = ('Ne, puslapyje iš anksto nieko nemokama — į formą įrašote tik vardą ir telefono numerį. Mokate atsiimdami, '
          'kurjeriui. Taip parašyta ir po forma.')
T[250] = 'Teresė Kazakevičienė'
T[251] = 'Prieš 5 dienas'
T[252] = 'Kas tiksliai yra viduje? Klausiu todėl, kad esu jautri kai kurioms žolelėms.'
T[253] = 'Algis Urbonas'
T[254] = 'Prieš 5 dienas'
T[255] = ('Sudedamosios dalys išvardytos viršuje straipsnyje: spygliuočių sakai, gliukozaminas ir chondroitinas, '
          'hialurono rūgštis, II tipo kolagenas ir MSM, kamparas ir kalnų arnika. Jei esate kam nors jautri, pasakykite '
          'tai savo gydytojui — čia niekas negali nuspręsti už jį.')
T[256] = 'Prieš'
T[257] = 'Po'
T[258] = '*'
T[259] = 'Pridėti profilio nuotrauką'
T[260] = 'Pridėti nuotrauką'
T[261] = 'SIŲSTI'
T[262] = '🛡️'
T[263] = 'Sertifikuota kokybė'
T[264] = '🚚'
T[265] = 'Pristatymas per 2–3 dienas'
T[266] = '⚕️'
T[267] = 'Be recepto'
T[268] = '🔒'
T[269] = 'Saugus užsakymas'
T[270] = '© SveikataInfo Lietuva — specialus reportažas'
T[271] = 'Šiame puslapyje pateikta informacija yra informacinio pobūdžio ir nepakeičia gydytojo konsultacijos.'
T[272] = '{_box:2sHZz2rc}'
T[273] = '{_box:2sHZz2rc}'
