# -*- coding: utf-8 -*-
"""BA -> HR. Герой: djed Ivan Horvat, Zagorje."""
LEX = {
 'sedmica':'tjedan','sedmice':'tjedna','sedmicu':'tjedan','sedmično':'tjedno','sedmicama':'tjednima',
 'Sedmice':'Tjedni','sedmični':'tjedni',
 'hiljada':'tisuća','hiljade':'tisuće','hiljadu':'tisuću','hiljadama':'tisućama','hiljadu':'tisuću',
 'apoteka':'ljekarna','apoteke':'ljekarne','apoteci':'ljekarni','apotekama':'ljekarnama',
 'Apoteke':'Ljekarne','apotekarska':'ljekarnička',
 'doktor':'liječnik','doktora':'liječnika','doktoru':'liječniku','Doktor':'Liječnik',
 'doktori':'liječnici','ljekar':'liječnik','ljekara':'liječnika','ljekari':'liječnici',
 'ljekaru':'liječniku','Ljekari':'Liječnici','ljekarima':'liječnicima','ljekarski':'liječnički',
 'porodica':'obitelj','porodice':'obitelji','porodicu':'obitelj','porodici':'obitelji',
 'penzioner':'umirovljenik','penzionera':'umirovljenika','penzioneri':'umirovljenici',
 'penzionera':'umirovljenika','penzionisani':'umirovljeni','penzionisan':'umirovljen',
 'penzija':'mirovina','penzije':'mirovine','penzijom':'mirovinom','penziju':'mirovinu',
 'hemija':'kemija','hemije':'kemije','hemiju':'kemiju','hemijske':'kemijske','hemijski':'kemijski',
 'hemijskih':'kemijskih','hemijsku':'kemijsku','hemijskim':'kemijskim','hemijska':'kemijska',
 'hronična':'kronična','hroničan':'kroničan','hronično':'kronično','hroničnom':'kroničnom',
 'hronične':'kronične','Hroničan':'Kroničan','hroničnim':'kroničnim',
 'kičma':'kralježnica','kičme':'kralježnice','kičmi':'kralježnici','kičmu':'kralježnicu',
 'Kičma':'Kralježnica','kičmena':'kralježnična','kičmi.':'kralježnici.',
 'pršljen':'kralježak','pršljena':'kralješka','pršljenova':'kralježaka','pršljenovi':'kralješci',
 'operisati':'operirati','operisanih':'operiranih','operisan':'operiran',
 'dokumentovao':'dokumentirao','dokumentovana':'dokumentirana','registrovano':'registrirano',
 'kafa':'kava','kafu':'kavu','kahvu':'kavu','kafe':'kave',
 'avliju':'dvorište','avlija':'dvorište','avliji':'dvorištu',
 'komšinicu':'susjedu','komšija':'susjed','komšije':'susjedi','komšiju':'susjeda',
 'krompir':'krumpir','krompira':'krumpira','paradajz':'rajčicu','paradajza':'rajčice',
 'baštu':'vrt','bašti':'vrtu','bašta':'vrt','bašte':'vrta',
 'šta':'što','Šta':'Što','ko':'tko','Ko':'Tko','niko':'nitko','Niko':'Nitko','nikoga':'nikoga',
 'uslov':'uvjet','uslovom':'uvjetom','uslova':'uvjeta','uslovima':'uvjetima',
 'opšte':'opće','opšta':'opća','opšti':'opći','opštinu':'općinu','općine':'općine',
 'nana':'baka','nane':'bake','nana,':'baka,','dedova i nana':'djedova i baka',
 'sto ':'stol ','stolica':'stolica',
 'guta':'guta','tablete':'tablete',
 'dedo':'djed','Dedo':'Djed','deda':'djed',
 'sopstvenim':'vlastitim','sopstvene':'vlastite','sopstveni':'vlastiti','sopstvenom':'vlastitom',
 'sopstvenog':'vlastitog','sopstvenih':'vlastitih',
 'zahvaljujući':'zahvaljujući','takmičiti':'natjecati',
 'stoljeća':'stoljeća',
}
GEO = {
 'dedo Salih Mehić':'djed Ivan Horvat','Dedo Salih Mehić':'Djed Ivan Horvat',
 'Saliha Mehića':'Ivana Horvata','Salih Mehić':'Ivan Horvat',
 'dedo Salih':'djed Ivan','Dedo Salih':'Djed Ivan','dedom Salihom':'djedom Ivanom',
 'dede Saliha':'djeda Ivana','dedi Salihu':'djedu Ivanu','Salih':'Ivan',
 'Konjuha':'Zagorja','Konjuhu':'Zagorju','Konjuh':'Zagorje',
 'Kladnja':'Krapine','Kladnju':'Krapini','Kladanj':'Krapina',
 'Tuzle':'Varaždina','Tuzli':'Varaždinu','Tuzla':'Varaždin',
 'Olovu':'Ivancu','Olovo':'Ivanec',
 'Banovićima':'Labinu','Banovića':'Labina','Banovići':'Labin',
 'Sarajeva':'Zagreba','Sarajevu':'Zagrebu','Sarajevo':'Zagreb',
 'Bosne i Hercegovine':'Hrvatske','Bosni i Hercegovini':'Hrvatskoj','Bosna i Hercegovina':'Hrvatska',
 'BOSNI I HERCEGOVINI':'HRVATSKOJ','Bosnu i Hercegovinu':'Hrvatsku',
 'bosanski':'hrvatski','ZdravljeInfo Bosna i Hercegovina':'ZdravljeInfo Hrvatska',
 'Zumra':'Ljubica','tetkom Mejrom':'tetom Marom','tetka Mejra':'teta Mara','Tetka Mejra':'Teta Mara',
 'tetke Mejre':'tete Mare','Mejra':'Mara','tetka Cvijeta':'teta Cvijeta','Tetka Cvijeta':'Teta Cvijeta',
 'dedo Rasim':'djed Slavko','Dedo Rasim':'Djed Slavko','Rasime':'Slavko','Rasim':'Slavko',
 'Kada, 72':'Kata, 72','Kada,':'Kata,',
 'tetka':'teta','Tetka':'Teta',
 'Amra Delić':'Ana Jurić','Senada Hadžić':'Snježana Babić','Lejla Novalić':'Ljiljana Novak',
 'Damir Mihić':'Damir Mihaljević','Danica Rozić':'Danica Rožić','Marijana Golub':'Marijana Golub',
 'Zoran Savić':'Zoran Šarić','Jelena Anđelić':'Jelena Anđelić','Suzana Vrbić':'Suzana Vrbanić',
 'Stanka Tomić':'Stanka Tomić','Branko Pavlović':'Branko Pavlić','Jasna Krznarić':'Jasna Krznarić',
 'Slavica Gojić':'Slavica Gojak','Igor Lazić':'Igor Lasić','Marta Vrbić':'Marta Vrbanić',
 'Adnan Poljić':'Andrej Poljak','Ivanka Savić':'Ivanka Šarić','Boris Rakić':'Boris Rakitić',
 'Terezija Kos':'Terezija Kos','Alija Hrnjić':'Alojz Hrnjak','Mirjana':'Mirjana',
}
