# -*- coding: utf-8 -*-
"""PL. Bohater: dziadek Stanisław Woźniak, Beskid Niski, Gorlice. Produkt: Metonil, KAPSUŁKI."""
T = {}
T[0] = '﻿'
T[1] = ('„Kto nie wierzy w siłę natury, nigdy nie zrozumie własnego ciała" — dziadek Stanisław Woźniak z Beskidu '
        'Niskiego, który ponad 1700 osobom przywrócił radość chodzenia bez ani jednej przepisanej chemicznej tabletki')
T[2] = 'Reportaż specjalny · Zdrowie i samopoczucie'
T[3] = '+'
T[4] = 'ZdrowieInfo Polska'
T[5] = 'Reportaże o zdrowiu publicznym'
T[6] = '„Kto nie wierzy w'
T[7] = 'siłę natury'
T[8] = ', nigdy nie zrozumie'
T[9] = 'własnego ciała'
T[10] = '."'
T[11] = 'Dziadek Stanisław Woźniak, ludowy zielarz z Beskidu Niskiego, przywrócił'
T[12] = 'ponad 1700 osobom'
T[13] = 'radość chodzenia'
T[14] = 'bez ani jednej przepisanej chemicznej tabletki'
T[15] = '. Nasz dziennikarz pojechał do jego odludnej zagrody, żeby zadać najważniejsze pytanie: jak mu się to udaje?'
T[16] = 'Opublikowano:'
T[17] = ', 09:36'
T[18] = ('W lasach Beskidu Niskiego mieszka 72-letni mężczyzna, którego w okolicznych wsiach nazywa się po prostu '
         '„dziadkiem Stanisławem". Nigdy nie był lekarzem. Nigdy nie studiował. Ale przez ostatnie trzy lata uratował '
         'ponad 1700 osób od bólu stawów — ludzi, których nawet najlepsi specjaliści już spisali na straty. Ludzi '
         'skazanych na wózek inwalidzki. Ludzi, którzy nie mogli wstać z własnego łóżka. A wszystko to dzięki zwykłym '
         'kapsułkom, wytwarzanym własnymi rękami — według dawnej mądrości natury.')
T[19] = ('We wtorek rano dotarliśmy do Gorlic, w zalesione doliny pod grzbietami. Mgła wisiała jeszcze między '
         'wierzchołkami drzew. Ostatnie kilometry przeszliśmy pieszo, bo dalej nie ma już asfaltowej drogi. „Szukacie '
         'dziadka Stanisława?" — zapytała starsza kobieta na końcu wsi, w chustce na głowie. „Skręćcie w lewo przy '
         'małej kamiennej studni. Jego dom jest przy źródle. Ale pośpieszcie się, bo w południe idzie w góry zbierać '
         'zioła."')
T[20] = ('Tak znaleźliśmy Stanisława Woźniaka — 72-letniego ludowego zielarza, który całe życie spędził w Beskidzie '
         'Niskim, a dziś łamie jedno z największych tabu w kraju: że na ból stawów istnieje prawdziwe rozwiązanie. '
         'Rozwiązanie, które nie zależy od chemicznych tabletek, zastrzyków ani operacji. A od spotkania natury, dawnej '
         'mądrości i pamięci stuleci.')
T[21] = ('W najbliższych miejscowościach — w Gorlicach, Nowym Sączu, Krynicy-Zdroju i gdzie indziej — dziadka Stanisława '
         'zna niemal każda rodzina. Córki przywożą swoich kulejących ojców, żeby ich obejrzał. Żony zamawiają opakowania '
         'kapsułek dla swoich matek w domach opieki. Mężczyźni przychodzą po długich dniach pracy, żeby znowu móc '
         'chodzić. Lekarz z powiatowej przychodni przyznaje:')
T[22] = '„Nie umiem wyjaśnić, co dzieje się z tym człowiekiem. Ale moi pacjenci naprawdę wracają do zdrowia."'
T[23] = ('„Dziewiętnaście lat żyłam z bólem. Przepisano mi dwanaście różnych leków — i żaden mi nie pomógł. Pewnego dnia '
         'siostra powiedziała mi o dziadku Stanisławie. Trzy godziny szłam do niego pieszo, bo nie wierzyłam. Teraz '
         'biorę te kapsułki już cztery tygodnie. Wczoraj sama zeszłam do piwnicy po przetwory. Pierwszy raz od '
         'dziewiętnastu lat."')
T[24] = '— Helena, 78 lat, Gorlice'
T[25] = ('„Syn pracuje w Niemczech. Jego żona nie chciała ze mną mieszkać z powodu moich bólów kręgosłupa. Zostałem sam '
         'na końcu wsi, w domu, który ledwo ogrzewam. Nawet pies ze mną nie chodził, bo nie nadążałem za nim. Wtedy '
         'dziadek Stanisław sam do mnie przyszedł. Na kolanach mu dziękowałem. Dziś sam chodzę do źródła po wodę."')
T[26] = '— Władysław, 71 lat, Nowy Sącz'
T[27] = ('Dziadek Stanisław z jedną ze swoich pacjentek, ciotką Zofią z Gorlic. „Tych ludzi nikt nie odwiedza. Dzieci '
         'wyjechały, lekarze spisali ich na straty. Ale natura ich nie spisała. Trzeba tylko wsłuchać się w to, co '
         'szepcze."')
T[28] = '„Ciało wie wszystko. Trzeba tylko uciszyć hałas, żeby usłyszeć, co szepcze."'
T[29] = ('Rozmowa z dziadkiem Stanisławem w sercu Beskidu Niskiego — w jego domu, gdzie ze ścian zwisają pęki suszonych '
         'ziół, a na półkach spoczywają stuletnie księgi')
T[30] = 'Dziadek Stanisław Woźniak:'
T[31] = ('„Wszystko pamiętam, jakby to było wczoraj. Wczesnym świtem mgła wisiała jeszcze między wierzchołkami. '
         'Siedziałem przed swoją chatą przy ogniu i przygotowywałem wyciąg z drzew iglastych — wtedy jeszcze na własne '
         'bóle. Nagle usłyszałem ciche kroki. Pojawiła się kobieta w ciemnej sukni do ziemi, może sześćdziesięcioletnia. '
         'Oczy miała jak stojąca woda — pełne strachu. Usiadła obok mnie na zwalonym pniu i powiedziała:')
T[32] = ('„Dziadku Stanisławie, proszę, ratuj mojego męża. Mój mąż umiera. Stawy coraz bardziej mu sztywnieją, kolana są '
         'zniszczone. Lekarze nie mogą już nic zrobić. Nie może chodzić, nie może wstać, nie może nawet siedzieć. Tylko '
         'leży i płacze."')
T[33] = ('W TEJ CHWILI ZROZUMIAŁEM: MĄDROŚĆ O ZIOŁACH, KTÓRĄ ODZIEDZICZYŁEM PO SWOIM NAUCZYCIELU, NIE ZOSTAŁA DANA TYLKO '
         'MNIE — ALE TAKŻE TEJ KOBIECIE I JEJ MĘŻOWI. WTEDY POSTANOWIŁEM PONIEŚĆ JĄ DALEJ."')
T[34] = ('Dziadek Stanisław Woźniak, 72-letni ludowy uzdrowiciel z Beskidu Niskiego. Mieszka w małym kamiennym domu, '
         'który w latach siedemdziesiątych sam zbudował, głęboko w górach. Nie ma dyplomu uczelni — ale miał nauczyciela, '
         'od którego w młodości nauczył się leczniczej wiedzy o ziołach, i ponad pięćdziesiąt lat doświadczenia, jakiego '
         'nie ma nikt inny.')
T[35] = ('Dziadek Stanisław mówi powoli, czasem z długimi pauzami — jakby każde słowo osobno ważył. Jego wielkie, '
         'kościste dłonie spoczywają na kolanach. Palce ma pobrudzone żywicą i korzeniami, z którymi pracuje od '
         'sześćdziesięciu pięciu lat. Za nim, na ścianie, wiszą suszone pęki szałwii i kminku. Na półkach stoją słoje, '
         'małe ciemne naczynia i ciężka, oprawiona w skórę księga — włoskie tłumaczenie „De Materia Medica" z '
         'szesnastego wieku, które odziedziczył po swoim nauczycielu.')
T[36] = ('„Ludzie myślą, że bóle stawów to naturalna część starości. To kłamstwo. Kolana, plecy, biodra — to jak las. '
         'Jeśli dobrze go pilnujesz, żyje stulecia. Jeśli go wyniszczasz i trujesz, w sześć albo osiem lat się rozpada. '
         'Współczesna medycyna stawów nie pilnuje. Tylko usypia ból. I co roku przepisuje więcej tabletek. Aż człowiek '
         'nie upadnie i nie złamie kości."')
T[37] = ('„Czterdzieści lat pracowałam w gospodarstwie. Wstawałam o czwartej rano, kładłam się o ósmej wieczorem. Nigdy '
         'się nie skarżyłam. Kiedy odmówiło mi biodro, lekarz powiedział: »Pani Marianno, to wiek. Musi się pani '
         'przyzwyczaić.« Jak mam się przyzwyczaić? Ledwo sześćdziesiąt pięć lat mam! Męża nie ma. Dzieci są w Niemczech. '
         'Jestem sama i nie mogę wyjść do ogrodu po pomidory. Wtedy listonosz powiedział mi o dziadku Stanisławie."')
T[38] = '— Marianna, 65 lat, Krynica-Zdrój'
T[39] = '„Apteki nie mówią prawdy — bo gdyby ją powiedziały, splajtowałyby"'
T[40] = 'Dziadek Stanisław Woźniak wyjaśnia, dlaczego tradycyjne leki na stawy szkodzą bardziej, niż pomagają'
T[41] = 'Dziadek Stanisław Woźniak:'
T[42] = ('— Powiem wam, co widzę miesiąc w miesiąc u tych, którzy do mnie przychodzą. Kobieta, sześćdziesiąt pięć lat. '
         'Od dziesięciu lat bierze leki przeciwzapalne. Ból kolana co roku się nasila. Teraz boli ją też żołądek od '
         'tylu tabletek. Wyniki nerek są złe. Lekarz przepisuje kolejną tabletkę — teraz na żołądek. Potem na nerki. A '
         'kolano tymczasem się rozpada. Chrząstki nikt nie odbudowuje. Tylko usypia się ból — aż chrząstka zetrze się '
         'do końca.')
T[43] = ('To błędne koło: ból → tabletka → ból wraca silniejszy → mocniejsza tabletka → żołądek cierpi → jeszcze jedna '
         'tabletka na żołądek → nerka odmawia → a staw tymczasem się rozpada.')
T[44] = 'Nikt nie mówi prawdy: istnieje inna droga — dać chrząstce to, czego potrzebuje, i pozwolić jej się odbudować.'
T[45] = ('Kolana ciotki Janiny, 74 lata, z Nowego Sącza. Artroza trzeciego stopnia — chrząstka jest niemal całkowicie '
         'starta. Od pięciu miesięcy nie wychodzi z domu. Na szafce nocnej — sześć rodzajów tabletek, które nie '
         'zmieniły nic. Wszystkie przywiózł jej syn z różnych aptek, w nadziei, że któraś pomoże. Żadna nie działa.')
T[46] = 'Ból kolana, pleców albo biodra po czterdziestym piątym roku życia'
T[47] = 'nie jest „normalny dla wieku"'
T[48] = ('— to znak, że chrząstka stawowa się zużywa i że znika maź stawowa. Kto ten znak zagłusza tabletkami, powoli i '
         'po cichu niszczy własne stawy.')
T[49] = ('Po lewej: zdrowy staw z zachowaną chrząstką i wystarczającą ilością mazi stawowej. Po prawej: zniszczony staw '
         '— starta chrząstka, przewlekły stan zapalny, kość na kości. To rzeczywistość wielu osób po sześćdziesiątce na '
         'wsiach. Leki przeciwzapalne chrząstki nie odbudowują — tylko łagodzą ból, podczas gdy wszystko dalej się '
         'rozpada.')
T[50] = ('Leki przeciwzapalne tylko blokują sygnał bólu, podczas gdy zniszczenie po cichu postępuje. Bez prawdziwej '
         'regeneracji chrząstki staw w końcu rozpada się całkowicie — i wtedy zostają tylko dwie możliwości: wózek '
         'inwalidzki albo operacja wszczepienia endoprotezy, która kosztuje majątek. Żadna nie zwraca prawdziwego życia.')
T[51] = 'Dziadek Stanisław Woźniak:'
T[52] = ('— Zrozumcie powagę tego. U wielu, którzy do mnie przychodzą, chrząstka w kolanie, w kręgosłupie albo w biodrze '
         'jest zniszczona w siedemdziesięciu do dziewięćdziesięciu procentach. Chodzą kość na kości — jeśli w ogóle '
         'jeszcze mogą chodzić. Każdy krok to męczarnia.')
T[53] = 'TRADYCYJNE TABLETKI NIE MOGĄ ODBUDOWAĆ CHRZĄSTKI — TYLKO MASKUJĄ BÓL, PODCZAS GDY WSZYSTKO SIĘ ROZPADA!'
T[54] = ('A wiecie, co mnie najbardziej boli w piersi? To, że ci ludzie są sami. Dzieci wyjechały do Niemiec, do Anglii, '
         'do Holandii, do Norwegii. Apteka przywozi im leki raz w tygodniu. Lekarz widzi ich raz w roku. A w tym czasie '
         'po cichu się rozpadają. Plecy, kolana, biodra. Z czasem boją się nawet wyjść z domu, żeby nie upaść. Dlatego '
         'robię to, co robię.')
T[55] = ('„Czterdzieści dwa lata pracowałam w gospodarstwie. Doiłam krowy, kopałam ziemniaki, nosiłam drewno. Nigdy się '
         'nie skarżyłam. Potem pewnego ranka po sześćdziesiątce nie mogłam wstać z łóżka. Kolano było jak kamień. Córka '
         'pracuje w Niemczech. Przez telefon powiedziała, żebym jechała do Krakowa do specjalisty. Jak mam jechać? Nawet '
         'po schodach nie zejdę. Dziadek Stanisław przyszedł do mnie, pół dnia szedł pieszo. Po dwóch tygodniach już '
         'pracowałam w ogrodzie."')
T[56] = '— Kazimiera, 72 lata, spod Gorlic'
T[57] = ('„Trzydzieści lat byłem górnikiem naftowym pod Gorlicami. Plecy bolały mnie już od czterdziestki. Po '
         'siedemdziesiątce nie mogłem nawet prosto stanąć. Dyskopatia, rwa kulszowa — lekarze wymyślali nazwy, a ból nie '
         'ustawał. Syn buduje w Niemczech. Przysyła pieniądze, ale nie ma czasu mnie odwiedzić. Z kapsułkami dziadka '
         'Stanisława po czterech tygodniach znowu wszedłem na dach, żeby go naprawić — pierwszy raz od sześciu lat."')
T[58] = '— Ryszard, 70 lat, emerytowany górnik naftowy spod Gorlic'
T[59] = 'Historie, których nigdy nie zapomnę — i historie, które zmienią to, jak patrzycie na siłę natury'
T[60] = 'Dziadek Stanisław Woźniak:'
T[61] = ('— Powiem wam, kogo widuję co tydzień. Nie mówię o statystykach. O ludziach. O ludziach z imionami, którzy mają '
         'rodzinę, którzy mają swoje historie. O ludziach, których medycyna już spisała na straty — a natura ich jeszcze '
         'nie spisała.')
T[62] = ('Ciotka Genowefa, 77 lat, z Gorlic. Reumatoidalne zapalenie stawów w obu dłoniach — nie mogła utrzymać nawet '
         'łyżki. Mąż zmarł jej dwa lata temu. Córka pracuje w Niemczech. „W aptece dali mi 12 różnych leków. Wszystkie '
         'szkodziły mi na żołądek, a staw bolał tak samo. Dziadek Stanisław przyszedł do mnie, kiedy listonosz '
         'powiedział mu, że nie mogę już nawet ziemniaka obrać."')
T[63] = ('„Rano patrzyłam na swoje dłonie i nie poznawałam ich — były opuchnięte, powykręcane, jakby nie moje. Nie '
         'mogłam się ani uczesać, ani pomidora pokroić. Z kapsułkami dziadka Stanisława po dwóch tygodniach już '
         'szydełkowałam. Wczoraj skończyłam swoją pierwszą serwetkę — pierwszy raz od całego roku. Patrzę na nią i '
         'płaczę."')
T[64] = '— Ciotka Genowefa, 77 lat'
T[65] = ('Dziadek Józef, 75 lat, z Nowego Sącza. Dyskopatia L4-L5, obustronna koksartroza. Od ośmiu miesięcy nie '
         'wstawał. „Powiedzieli, że jestem za stary na operację. Że muszę się z tym pogodzić. Że nie mam nadziei. '
         'Dziadek Stanisław po prostu usiadł koło mnie, chwycił mnie za kolano i powiedział: »Józefie, za dwa tygodnie '
         'idziemy razem do ogrodu.« I tak było."')
T[66] = ('„Czterdzieści pięć lat byłem traktorzystą w gospodarstwie. Zaorałem pół gminy. A potem pewnego ranka nie '
         'mogłem nawet głowy podnieść z poduszki. Dwoje moich dzieci pracuje w Anglii. Przysyłają pieniądze i dzwonią '
         'na święta. Ale kto mi poda wody, jeśli w nocy zaduszę się od kaszlu? Z kapsułkami dziadka Stanisława po '
         'czterech tygodniach znowu rąbałem drewno. Niedużo — ale dość, żeby własnymi siłami się ogrzać."')
T[67] = '— Dziadek Józef, 75 lat'
T[68] = ('To są objawy, które widuję najczęściej — i których miliony ludzi nie traktują poważnie, myśląc, że to „tylko '
         'wiek":')
T[69] = 'Ostry ból kolana przy wchodzeniu lub schodzeniu po schodach — albo przy każdym ruchu;'
T[70] = 'Poranna sztywność — ciało jest „drewniane", nie rusza się przez 30–60 minut po przebudzeniu;'
T[71] = 'Przewlekły ból pleców — nie mogę się schylić, nie mogę wstać z łóżka;'
T[72] = 'Obrzęki w kolanach, kostkach albo palcach;'
T[73] = 'Skrzypienie i trzeszczenie w stawach przy każdym ruchu;'
T[74] = 'Ból biodra promieniujący do uda — nie mogę przejść więcej niż 50 metrów;'
T[75] = 'Zdeformowane, guzowate palce — nie mogę chwytać przedmiotów;'
T[76] = 'Mrowienie w nogach albo rękach — znak dyskopatii lub uciśniętego nerwu;'
T[77] = 'Uczucie „noża" w krzyżu przy prostowaniu pleców;'
T[78] = 'Zgarbione plecy, skrzywiona postawa — postępująca kifoza;'
T[79] = 'Nocny ból, który nie daje spać — budzę się 4–5 razy w ciągu nocy;'
T[80] = ('Każdy z tych objawów to alarm. A po czterdziestym piątym czy pięćdziesiątym roku życia ich lekceważenie '
         'prowadzi do jednego jedynego końca:')
T[81] = ('CAŁKOWITY BEZWŁAD, WÓZEK INWALIDZKI, PEŁNA ZALEŻNOŚĆ OD INNYCH — A W WIELU PRZYPADKACH UMIESZCZENIE W DOMU '
         'OPIEKI, DOKĄD DZIECI PRZYJEŻDŻAJĄ RAZ W ROKU.')
T[82] = ('Każdy dzień spędzony z nieleczonymi stawami przybliża was do trwałego bezwładu! Tysiące polskich emerytów '
         'trafiło do domów opieki właśnie dlatego, że bólu nie potraktowali poważnie — albo brali tylko tabletki, które '
         'problemu nie rozwiązały. Działajcie teraz — dla siebie albo dla swoich najbliższych — zanim będzie za późno!')
T[83] = '„Mój nauczyciel mnie nauczył: na każdy ból natura ma odpowiedź — jeśli wiesz, gdzie szukać"'
T[84] = ('Jak dziadek Stanisław Woźniak znalazł formułę, z której dziś korzysta ponad 1700 osób ze wsi wokół Beskidu '
         'Niskiego')
T[85] = 'Dziadek Stanisław Woźniak:'
T[86] = ('— Następnego dnia poszedłem zobaczyć męża tej kobiety. Dom był w półmroku. Człowiek wyglądał jak wysuszony '
         'grzyb — suchy, żółtawy. Ciało było jeszcze ciepłe, a spojrzenie już żegnało się ze światem. Usiadłem obok '
         'niego, chwyciłem go za rękę i zapytałem: „Ile lat żyjesz już z tym bólem, bracie?" Milczał. Łza spłynęła mu '
         'po policzku. „Dziewiętnaście lat," wyszeptał. „I nikt nie wie, jak mi pomóc. Wszyscy tylko przepisują leki."')
T[87] = ('Wtedy przypomniałem sobie stary zapis. Wiele lat wcześniej w spuściźnie po moim nauczycielu znalazłem '
         'zapomniany zeszyt — włoski zielnik z szesnastego wieku, tłumaczenie „De Materia Medica" wielkiego '
         'Dioskurydesa. Na jednej stronie było napisane:')
T[88] = ('„Wewnętrzny ogień ciała kradnie stawom ich wilgoć i giętkość. Tylko ten, kto zna łzę drzewa — żywicę, która '
         'przechowuje pamięć ludzkiej tkanki — może przywrócić życie ich kościom."')
T[89] = ('Zielnik, który dziadek Stanisław odziedziczył po swoim nauczycielu. „Ta księga przechowywała mądrość dwieście '
         'lat, zanim ją znalazłem. Wszystkie zioła, które trafiają do Metonilu, są na tych stronach."')
T[90] = ('Oczywiście nie było to naukowe wyjaśnienie — lecz mądrość przekazywana z pokolenia na pokolenie. Ale wtedy '
         'jeszcze nie wiedziałem, że ten dzień będzie początkiem trzech lat pracy. Trzech lat, w których spuściznę '
         'moich nauczycieli i dary lasu połączyłem w zwykłe kapsułki, wytwarzane ręcznie — które potrafią odbudować '
         'chrząstkę od środka, bez chemicznych tabletek.')

# ---------- 91–180 ----------
T[91] = 'Co zawierają kapsułki, które wytwarza dziadek Stanisław:'
T[92] = 'Żywica drzew iglastych z Beskidu Niskiego — łza drzewa'
T[93] = ('Żywica drzew iglastych — którą mój nauczyciel nazywał „łzą drzewa". Tradycyjna medycyna ludowa stosuje ją od '
         'stuleci przy bólach stawów. Naturalny środek przeciwzapalny, który zatrzymuje rozpad chrząstki i budzi '
         'regenerację')
T[94] = 'Glukozamina i chondroityna — w naturalnej postaci'
T[95] = 'Cegły chrząstki — dawny zapas natury, który komórki rozpoznają i wykorzystują'
T[96] = 'Kwas hialuronowy — w postaci małych cząsteczek'
T[97] = 'Przywraca stawowi wilgoć — to, co natura przeznaczyła ludzkiemu ciału, a co odebrał mu stan zapalny'
T[98] = 'Kolagen typu II i MSM'
T[99] = 'Wzmacniają więzadła i ścięgna wokół stawu — naturalną siatkę ochronną, która z latami słabnie'
T[100] = 'Kamfora i arnika górska'
T[101] = 'Natychmiastowa ulga w bólu i obrzęku — jak mówił mój nauczyciel: „duch drzewa, który gasi ogień"'
T[102] = ('Kapsułki zawierają jeszcze 14 innych rzadkich wyciągów roślinnych, które dziadek Stanisław i jego pomocnicy '
          'zbierają na zboczach Beskidu Niskiego przez sześć tygodni — co roku, tylko raz w roku, kiedy zioła są w '
          'pełni dojrzałości. Proporcji dziadek Stanisław nauczył się od swojego nauczyciela i każdy krok wykonuje '
          'własnymi rękami.')
T[103] = 'Tak powstały kapsułki Metonil — wytwarzane ręcznie, z najlepszych ziół leczniczych z Beskidu Niskiego'
T[104] = 'Dziadek Stanisław Woźniak:'
T[105] = ('— Nie rodzą się w laboratorium. Rodzą się w mojej pracowni, tutaj, u podnóża gór. Żywicę drzew iglastych '
          'zbieramy ja i moi pomocnicy — w starych świerkowych lasach, na najwyższych grzbietach, gdzie drzewa od '
          'stuleci roniły swoje łzy. I inne zioła lecznicze zbieramy tutaj, po zboczach. Zbiór zajmuje nam sześć '
          'tygodni, bo każdą roślinę trzeba ściąć w chwili jej dojrzałości. Potem wytwarzamy kapsułki w małych partiach '
          'i pakujemy je ręcznie. Dziennie możemy zrobić najwyżej 70 opakowań — nie więcej, bo to zepsułoby jakość.')
T[106] = ('Pracownia dziadka Stanisława u podnóża gór. Na półkach wiszą wysuszone pęki szałwii, nagietka i dzikiej róży. '
          'Tu powstaje każde opakowanie Metonilu — ręcznie, w małych partiach.')
T[107] = ('Podstawą kapsułek jest licząca 200 lat receptura, którą zostawił mi mój nauczyciel. Mówiąc współczesnym '
          'językiem nauki: połączenie stężonych wyciągów roślinnych sprawia, że substancje czynne wchłaniają się w '
          'organizm i z krwią docierają wprost do torebki stawowej, tam gdzie rozpada się chrząstka. Działanie jest '
          'pięć razy silniejsze niż jakikolwiek suplement z apteki, bo natura dokładnie wie, jak współpracować z '
          'ludzkim ciałem. A przewaga kapsułek nad maściami i żelami polega na tym, że działają od środka: substancje '
          'czynne krążą z krwią i docierają jednocześnie do wszystkich chorych stawów — kolan, pleców, bioder, dłoni i '
          'szyi — a nie tylko tam, gdzie akurat zdołacie sięgnąć ręką. Dla starszych ludzi, którzy mieszkają sami i '
          'nie potrafią się już schylić, to oznacza proste stosowanie i samodzielność.')
T[108] = ('Metonil nie jest konkurentem. Nie chce się ścigać. Chce tylko pomóc. Każdy składnik — w dokładnej proporcji '
          '— budzi regenerację chrząstki, odnowę mazi stawowej i wyciszenie stanu zapalnego. To jedyny środek, który '
          'działa na poziomie komórkowym i jednocześnie dociera do wszystkich zajętych miejsc — kolan, pleców, bioder, '
          'dłoni, szyi — od środka. I najważniejsze: działa także w wieku 70, 80, 85 lat! Moimi pierwszymi pacjentami '
          'byli najstarsi — ludzie, których wszyscy już spisali na straty.')
T[109] = 'Dziadek Stanisław Woźniak:'
T[110] = ('— Pierwsza kobieta, której dałem te kapsułki, przez cztery miesiące nie wstała z łóżka. To była ciotka Zofia '
          'z Gorlic. Trzeciego dnia sama przyszła do kuchni i zaparzyła mi kawę. Oboje płakaliśmy. Ona — bo pierwszy '
          'raz od wielu lat nie bolał jej każdy ruch. Ja — bo w tej chwili zrozumiałem, że spuścizna mojego nauczyciela '
          'żyje. Że przez te wszystkie lata nie pracowałem na darmo.')
T[111] = 'Metonil na cztery sposoby pomaga wam odzyskać radość chodzenia — w każdym wieku'
T[112] = 'Cztery główne działania kapsułek Metonil:'
T[113] = 'Usunięcie bólu i stanu zapalnego'
T[114] = ('Już w pierwszych 30–45 minutach po przyjęciu połączenie żywicy drzew iglastych, arniki i kamfory zmniejsza '
          'ból i stan zapalny. Nie blokuje sygnału nerwowego (jak zwykłe chemiczne tabletki) — lecz wycisza samo '
          'źródło zapalenia, tam gdzie problem się zaczyna.')
T[115] = 'Odbudowa chrząstki'
T[116] = ('Glukozamina, chondroityna i kolagen typu II docierają do torebki stawowej i budzą komórki chrząstki '
          '(chondrocyty), które zaczynają tworzyć nową tkankę chrzęstną. Ten proces zaczyna się po 3–5 dniach '
          'regularnego stosowania.')
T[117] = 'Odnowa mazi stawowej'
T[118] = ('Kwas hialuronowy z małych cząsteczek wchłania się do organizmu i uzupełnia maź stawową — naturalny „smar" '
          'stawu. Dzięki temu kości nie ocierają się już o siebie, a ruch staje się lekki i bezbolesny.')
T[119] = 'Długotrwała ochrona i profilaktyka'
T[120] = ('MSM i kompleks mineralny wzmacniają więzadła i ścięgna wokół stawu oraz zapobiegają przyszłym uszkodzeniom. '
          'Po 30–60 dniach stosowania staw zyskuje stabilną ochronę, która trzyma kilka miesięcy.')
T[121] = 'Historie, które dziadek Stanisław opowiada osobiście — o ludziach, którzy znowu chodzą'
T[122] = 'Dziadek Stanisław Woźniak:'
T[123] = ('— Opowiem wam o niektórych z tych, których widuję co tydzień. O ludziach, którym nikt nie dawał szansy — ani '
          'lekarze, ani rodzina. O ludziach, którzy znowu chodzą.')
T[124] = 'Ciotka Zofia, 82 lata, Gorlice.'
T[125] = ('Przez cztery miesiące nie wstała z łóżka. Trzeciego dnia przyjmowania Metonilu sama postawiła pierwsze kroki. '
          'Po 30 dniach wychodzi na podwórze bez pomocy. „Nikt się tego nie spodziewał. Ani ja sama. Dziadek Stanisław '
          'przychodzi raz w tygodniu. Tylko patrzy, dotyka kolana i kiwa głową."')
T[126] = 'Wynik po 30 dniach:'
T[127] = 'Samodzielne chodzenie, poranna sztywność zniknęła, ból spadł z 9/10 do 2/10.'
T[128] = 'Dziadek Ryszard, 70 lat, emerytowany górnik naftowy spod Gorlic.'
T[129] = ('Dyskopatia, rwa kulszowa, nie mógł stać dłużej niż 5 minut. Po 6 tygodniach — wrócił do swojego ogrodu, '
          'obrabia dwie grządki dziennie. „Myślałem, że mam plecy zniszczone na zawsze. Byłem gotów pogodzić się z '
          'życiem inwalidy. Pomyliłem się. Z kapsułkami dziadka Stanisława czuję się dwadzieścia lat młodszy."')
T[130] = 'Wynik po 45 dniach:'
T[131] = 'Ostry ból w krzyżu zniknął, ruchomość wróciła, pierwszy raz od 4 lat przespał głęboko całą noc.'
T[132] = 'Dlaczego Metonilu nie ma w aptekach? I jak go zdobyć?'
T[133] = 'Dziadek Stanisław Woźniak:'
T[134] = ('Szczerze mówiąc, wytwarzanie Metonilu to trudny i powolny proces. Surowce są rzadkie — żywicę drzew iglastych '
          'można zbierać tylko w starych świerkowych lasach, inne zioła ręcznie po zboczach gór, a mamy zaledwie '
          'sześciotygodniowe okno w roku, kiedy rośliny są w pełni dojrzałe. Dziennie w pracowni dziadka Stanisława '
          'możemy zrobić najwyżej 70 opakowań. Nie jesteśmy w stanie zaspokoić wszystkich zapytań.')
T[135] = ('Minie jeszcze co najmniej 2–3 lata, zanim Metonil trafi do aptek. Do tego czasu jest dostępny na terenie '
          'całego kraju tylko przez internet, w programach wsparcia, które otwierają się dwa razy w roku.')
T[136] = 'Rabat może sięgnąć 50 %'
T[137] = '— co jest szczególnie ważne dla emerytów ze wsi w Polsce, którzy żyją z niskiej emerytury.'
T[138] = ('Kiedy w aptekach dowiedzieli się, że te kapsułki naprawdę działają — nawet przy zaawansowanej artrozie i '
          'dyskopatii — chcieli za nie brać 129 EUR za opakowanie. Powiedziałem im: „Nie pracuję dla pieniędzy. Mój '
          'nauczyciel za darmo oddał mi wszystko, co wiedział. Nie okradnę polskich emerytów." Apteki mnie odrzuciły. '
          'Kilka dni później zaczęli mnie odwiedzać ludzie z inspekcji sanitarnej. Żądali dokumentów. Chcieli mnie '
          'ukarać. Ale nie odpuściłem. Wtedy w moim życiu pojawił się młody mężczyzna z Warszawy. Jego matkę trzy lata '
          'wcześniej wyleczyłem z ciężkiej artrozy kolan — jego i jego matkę dawno zapomniałem. Teraz wrócił. '
          'Powiedział: „Dziadku Stanisławie, ty tu w górach robisz cuda własnymi rękami. Ale w Polsce są tysiące '
          'cierpiących ludzi, którzy nigdy tu nie dojadą. Pozwól mi pomóc." Załatwił, żeby kapsułki, wytwarzane moimi '
          'narzędziami, pakowano w czystej pracowni w sterylne opakowania, żeby firma kurierska dostarczała je po całym '
          'kraju i żeby mały zespół odbierał telefony. Ja nadal robię je tutaj, we własnym tempie. On dba tylko o to, '
          'żeby trafiły do tych, którzy ich potrzebują.')
T[139] = 'Cena, do której doszliśmy:'
T[140] = 'Cena, której żądały apteki'
T[141] = '129 EUR'
T[142] = 'Cena w innych krajach regionu'
T[143] = '99 EUR'
T[144] = 'Cena, którą oferujemy dzisiaj'
T[145] = '78 EUR'
T[146] = 'Z rabatem dla czytelników dzisiaj'
T[147] = '39 EUR'
T[148] = ('Proszę was: NIE PRZEGAPCIE TEGO PROGRAMU! Nie tylko dla siebie — ale też dla rodziców, dziadków i babć, '
          'bliskich krewnych, którzy może cierpią w milczeniu. Albo dla tych, którzy są już w domach opieki, sami, i '
          'którym nikt nic nie przysyła. Bądźcie tym, kto robi różnicę.')
T[149] = 'Do zamówienia użyjcie formularza poniżej.'
T[150] = 'Ostatnia szansa, żeby w tym roku dostać Metonil — dla siebie albo dla kogoś bliskiego, kto cierpi w milczeniu'
T[151] = 'Dziadek Stanisław Woźniak:'
T[152] = ('— Zarezerwowałem 20 000 opakowań wyłącznie dla czytelników tego portalu. Każdy mieszkaniec Polski powyżej 40. '
          'roku życia może dostać')
T[153] = 'rabat 50 %'
T[154] = ', ale program zamyka się'
T[155] = '.'
T[156] = ('Nie czekajcie, aż nie będziecie mogli wejść po schodach. Aż kolana w końcu odmówią. Aż plecy się zablokują. I '
          'przede wszystkim — nie czekajcie, aż staniecie się „ciężarem" dla najbliższych. Jedna kuracja budzi naturalną '
          'regenerację chrząstki — i od tej chwili ciało pracuje samo. Nie trzeba leczyć się całe życie, nie trzeba '
          'chemicznych tabletek, nie ma bólu, który wraca. Jeden krok, a wasze ciało przypomni sobie, jak się żyje.')
T[157] = ('Wpiszcie swoje imię i numer telefonu. Konsultant do was zadzwoni, dobierze odpowiedni program i zorganizuje '
          'dostawę w 2–3 dni firmą kurierską prosto pod wasz adres, w całej Polsce.')
T[158] = ('Z miłością i troską — dziadek Stanisław Woźniak. Dbajcie o swoich najbliższych. Może jedyne, czego im '
          'potrzeba, to wiedzieć, że nie są zapomniani.')
T[159] = 'Zaktualizowano:'
T[160] = ':'
T[161] = 'Ze względu na wyjątkowe zainteresowanie zapasy mogą skończyć się szybciej, niż przewidziano! Dzisiaj —'
T[162] = '— to ostatni dzień programu'
T[163] = 'albo do wyczerpania zapasów.'
T[164] = ('Uwaga! Nie zamykajcie i nie odświeżajcie strony, bo wasze opakowanie Metonilu zostanie zaproponowane innej '
          'osobie!')
T[165] = 'Możecie wziąć udział w ofercie — wasze miejsce jest zarezerwowane:'
T[166] = 'Nr'
T[167] = '19'
T[168] = '974'
T[169] = 'Oficjalny formularz zamówienia'
T[170] = 'Nr'
T[171] = '19'
T[172] = '974'
T[173] = '/'
T[174] = '20 000'
T[175] = 'Aby otrzymać'
T[176] = 'rabat 50 %'
T[177] = 'wpiszcie swoje imię i numer telefonu w pola poniżej i naciśnijcie przycisk „ZAMÓW".'
T[178] = 'Dostępne:'
T[179] = '33'
T[180] = '/1000'

# ---------- 181–273 ----------
T[181] = '78 EUR'
T[182] = '39 EUR'
T[183] = 'Imię'
T[184] = 'Numer telefonu'
T[185] = 'ZAMÓW TERAZ'
T[186] = '✔️ Gwarantowana dostawa certyfikowanym kurierem'
T[187] = 'prosto pod wskazany przez was adres'
T[188] = 'KOMENTARZE'
T[189] = 'Agnieszka Dębska'
T[190] = '2 godziny temu'
T[191] = ('Płakałam, czytając to. Mama ma 76 lat, od dwóch lat jest w domu opieki w Rzeszowie — właśnie dlatego, że '
          'kolana ją zawiodły, a ja nie mogłam się nią zająć. To moja największa wina. Zamówiłam jej Metonil. Mam '
          'nadzieję, że nie jest za późno. Daj Boże, żeby zadziałało.')
T[192] = 'Wiesława Kowalczyk'
T[193] = '5 godzin temu'
T[194] = ('W zeszły piątek dostałam Metonil. Rano i wieczorem biorę kapsułki. Po 5 dniach ból znacznie odpuścił, mogę '
          'schodzić po schodach bez trzymania się poręczy! Historia o dziadku Stanisławie przekonała mnie do '
          'zamówienia. Niezwykły człowiek, naprawdę.')
T[195] = 'Stanisława Hajduk'
T[196] = '8 godzin temu'
T[197] = ('Mam 69 lat. Cztery lata męczyłam się z plecami — dyskopatia i rwa kulszowa. Nie mogłam się nawet schylić, '
          'żeby zawiązać buty. Lekarze przepisali mi leki przeciwzapalne, które zniszczyły mi żołądek. Po 3 tygodniach '
          'z Metonilem ból prawie zniknął. Sama chodzę na targ, gotuję. Odzyskałam swoje życie, dzięki Bogu.')
T[198] = 'Grzegorz Król'
T[199] = '12 godzin temu'
T[200] = ('Pracuję po 10 godzin dziennie w biurze w Warszawie. Plecy i kark już nie reagują. Lekarz powiedział: „Albo '
          'zmieniasz pracę, albo operacja." Wybrałem kapsułki Metonil. Po 5 tygodniach — ani śladu bólu. I ogromny '
          'szacunek dla dziadka Stanisława — w świecie, gdzie wszyscy chcą pieniędzy, on idzie pieszo do zapomnianych '
          'staruszków w górach.')
T[201] = 'Lidia Nowak'
T[202] = '14 godzin temu'
T[203] = ('Szczerze mówiąc, nie wierzyłam. Tyle rzeczy reklamuje się w internecie, że straciłam zaufanie. Ten tekst '
          'przeczytałam tylko dlatego, że moja teściowa nie może chodzić, a ja jestem zrozpaczona. Zamówiłam z myślą '
          '„jeśli nie zadziała, stracę 39 €". Minęły 3 tygodnie. Teściowa wczoraj sama wstała z fotela! Moja teściowa! '
          'Która nie wstawała 8 miesięcy. Teraz nie wiem, co powiedzieć. Piszę dla tych, którzy wątpią jak ja.')
T[204] = 'Damian Michalak'
T[205] = '16 godzin temu'
T[206] = ('Zamówiłem 3 opakowania — dla siebie (kolana), dla żony (dłonie, artretyzm) i dla ojca żony w domu opieki. Nie '
          'możemy go często odwiedzać, to chociaż wyślemy mu to, czego potrzebuje. Mam nadzieję, że jemu też pomoże. '
          'Dziękuję za ten artykuł.')
T[207] = 'Danuta Różycka'
T[208] = '18 godzin temu'
T[209] = ('Zastanawiam się, czy zamówić dla taty. Już 3 lata jest w domu opieki — kolana w ogóle nie pracują. Poddał '
          'się, ledwo mówi. Myślicie, że Metonil może pomóc także w wieku 78 lat?')
T[210] = 'Marianna Gołąb'
T[211] = '17 godzin temu'
T[212] = ('Danuto, moja mama ma 82 lata! Ciężki artretyzm w obu kolanach, nie wstawała z łóżka. Już 2 miesiące bierze '
          'Metonil — teraz sama wychodzi na podwórze. Nie przesadzam. I najpiękniejsze: kiedy ją odwiedziłam, czekała '
          'na mnie stojąc w drzwiach! Płakałyśmy razem. Zamów bez wahania, twój tata zasługuje na szansę.')
T[213] = 'Zbigniew Sawicki'
T[214] = '15 godzin temu'
T[215] = ('Danuto, zamawiajcie spokojnie. Mam 78 lat, byłem o krok od wózka inwalidzkiego — koksartroza. Metonil w 2 '
          'miesiące postawił mnie na nogi. Dosłownie. Ojciec zasługuje na więcej niż dom opieki.')
T[216] = 'Jolanta Andrzejewska'
T[217] = '20 godzin temu'
T[218] = ('Od tygodnia biorę kapsułki rano i wieczorem. Rano nie jestem już „drewnianym kijem". Mogę się schylić, mogę '
          'wstać bez „ojej". Zamówiłam też dla sąsiadki, ma 73 lata i mieszka sama, przy chodzeniu trzyma się ścian.')
T[219] = 'Zuzanna Wróbel'
T[220] = '1 dzień temu'
T[221] = ('Przyznaję — ten artykuł czytałam z nieufnością. Mam doświadczenie z produktami, które obiecują wszystko. Ale '
          'historia o dziadku Stanisławie mnie ujęła i postanowiłam spróbować, bo kolana męczą mnie już 5 lat. Po '
          'miesiącu — mogę kopać w ogrodzie! Nie mówię, że to cud. Mówię, że działa. Dajcie temu szansę.')
T[222] = 'Stanisława Tomczyk'
T[223] = '1 dzień temu'
T[224] = ('Mam 82 lata. W zeszłym roku nie mogłam nawet sama dojść do toalety. Dzieci mówiły, że oddadzą mnie do domu '
          'opieki. Spróbowałam Metonilu — bez wielkich nadziei. I DZIAŁA!!! Chodzę sama, ubieram się sama, sama dochodzę '
          'do drzwi. Dzieci o domu opieki już nie wspominają. To moje największe szczęście.')
T[225] = 'Bronisław Pawlak'
T[226] = '1 dzień temu'
T[227] = ('Moja żona nie mogła nawet zejść po schodach. Trzymała się ściany i płakała z bólu. Myślałem, że ją tracę — '
          'nie przez chorobę, tylko przez rozpacz. Zamówiłem Metonil z rabatem. Po 4 tygodniach wczoraj sama poszła na '
          'targ i wróciła z kwiatami. Z kwiatami! Dziękuję z całego serca.')
T[228] = 'Jadwiga Krzemińska'
T[229] = '1 dzień temu'
T[230] = ('Zamówiłam cztery opakowania — dla mamy (w domu opieki, kolana), dla taty (w domu opieki, plecy) i dwa dla '
          'siebie (dłonie, artretyzm w palcach, nie mogłam pisać). Historie z artykułu mnie poruszyły. Nie mam już '
          'wymówek.')
T[231] = 'Sławomira Gajda'
T[232] = '2 dni temu'
T[233] = ('Dostałam Metonil — kurier dostarczył w 2 dni! Kapsułki już przekazałam mamie w domu opieki. W sercu mam '
          'nadzieję. Ten artykuł wysyłam też personelowi — może zadzwonią do dziadka Stanisława.')
T[234] = 'Igor Łaziński'
T[235] = '2 dni temu'
T[236] = ('Szukałem Metonilu po aptekach — nie mają. Powiedzieli, że trzeba zamówić na tej stronie. Mam nadzieję, że '
          'jeszcze jest. Mój dziadek pilnie go potrzebuje — ma 81 lat i nie może już chodzić.')
T[237] = 'Marta Wróblewska'
T[238] = '3 dni temu'
T[239] = ('Pytanie do tych, którzy już biorą: ile razy dziennie przyjmuje się kapsułki i ile trwa jedna kuracja? W '
          'artykule przeczytałam to w pośpiechu i nie zapamiętałam.')
T[240] = 'Andrzej Polak'
T[241] = '3 dni temu'
T[242] = ('Marto, wyżej w tekście jest napisane: najkrótsza kuracja, którą zaleca dziadek Stanisław, to 30 dni, przy '
          'cięższych problemach 60 albo 90 dni. Kapsułki przyjmuje się doustnie, popijając wodą. Jeśli nie jesteś '
          'pewna, zapytaj konsultanta, kiedy zadzwoni — mnie wszystko wyjaśnił przez telefon.')
T[243] = 'Zdjęcie przysłane przez czytelnika.'
T[244] = 'Iwona Sawicka'
T[245] = '4 dni temu'
T[246] = 'Czy trzeba coś płacić z góry, kiedy składa się zamówienie na tej stronie? Niechętnie podaję dane karty.'
T[247] = 'Bogdan Rakowski'
T[248] = '4 dni temu'
T[249] = ('Nie, na stronie nie płaci się nic z góry — w formularzu wpisujecie tylko imię i numer telefonu. Płacicie przy '
          'odbiorze, kurierowi. Tak też jest napisane pod formularzem.')
T[250] = 'Teresa Kos'
T[251] = '5 dni temu'
T[252] = 'Co dokładnie jest w środku? Pytam, bo jestem wrażliwa na niektóre zioła.'
T[253] = 'Alojzy Hryniewicz'
T[254] = '5 dni temu'
T[255] = ('Składniki są wymienione wyżej w artykule: żywica drzew iglastych, glukozamina i chondroityna, kwas '
          'hialuronowy, kolagen typu II i MSM, kamfora i arnika górska. Jeśli jesteście na coś wrażliwi, powiedzcie to '
          'swojemu lekarzowi — tutaj nikt nie może ocenić tego za niego.')
T[256] = 'Przed'
T[257] = 'Po'
T[258] = '*'
T[259] = 'Dodaj zdjęcie profilowe'
T[260] = 'Dodaj zdjęcie'
T[261] = 'WYŚLIJ'
T[262] = '🛡️'
T[263] = 'Certyfikowana jakość'
T[264] = '🚚'
T[265] = 'Dostawa w 2–3 dni'
T[266] = '⚕️'
T[267] = 'Bez recepty'
T[268] = '🔒'
T[269] = 'Bezpieczne zamówienie'
T[270] = '© ZdrowieInfo Polska — reportaż specjalny'
T[271] = 'Informacje na tej stronie mają charakter informacyjny i nie zastępują badania lekarskiego.'
T[272] = '{_box:2sHZz2rc}'
T[273] = '{_box:2sHZz2rc}'
