# -*- coding: utf-8 -*-
"""BA (ijekavica) -> RS (ekavica). Герой: deda Milorad Jovanović, Zlatibor."""

# 1) екавица: только слова с рефлексом ятя, остальные -nje/-lje не трогаем
EKAV = {
 'Cijena':'Cena','cijena':'cena','cijele':'cele','cijeli':'celi','cijelo':'celo','cijeloj':'celoj',
 'cijelu':'celu','cijepao':'cepao','Cvijeta':'Cveta','cvijećem':'cvećem',
 'Lijevo':'Levo','lijevo':'levo','dvije':'dve','dvjesto':'dvesto','lijegala':'legala','lijehe':'leje',
 'lijekova':'lekova','lijekove':'lekove','lijekovi':'lekovi','liječenjem':'lečenjem',
 'izliječio':'izlečio','neliječenim':'nelečenim','ljekarski':'lekarski','ljekovitim':'lekovitim',
 'ljekovito':'lekovito','ljekar':'lekar','ljekari':'lekari','ljekara':'lekara','ljekaru':'lekaru',
 'Ljekari':'Lekari','ljekarima':'lekarima',
 'Prije':'Pre','prije':'pre','Poslije':'Posle','poslije':'posle','Posljednja':'Poslednja',
 'Posljednje':'Poslednje','posljednje':'poslednje','posljednji':'poslednji','Sljedećeg':'Sledećeg',
 'sljedećem':'sledećem','rijetki':'retki','rijetkih':'retkih','riječ':'reč','riječi':'reči',
 'riješile':'rešile','Rješenje':'Rešenje','rješenje':'rešenje','svijeta':'sveta','svijetu':'svetu',
 'tijela':'tela','Tijelo':'Telo','tijelo':'telo','tijelom':'telom','tijelu':'telu',
 'unaprijed':'unapred','uspijeva':'uspeva','zauvijek':'zauvek',
 'stoljetne':'vekovne','stoljetnog':'vekovnog','stoljeća':'vekova','stoljećima':'vekovima',
 'prijevod':'prevod','namijenila':'namenila','promijenile':'promenile','promijeniti':'promeniti',
 'nadomješta':'nadomešta','korijenja':'korenja','pomjera':'pomera','Omjere':'Odnose','omjeru':'odnosu',
 'omjeri':'odnosi','omjerima':'odnosima','Htjeli':'Hteli','htjela':'htela','htjeli':'hteli',
 'vidjeti':'videti','razumjeti':'razumeti','sjediti':'sedeti','živjeti':'živeti','živjela':'živela',
 'sjetiti':'setiti','sjetio':'setio','sjećam':'sećam','posjeti':'poseti','posjetila':'posetila',
 'posjećivati':'posećivati','posjećuje':'posećuje','Sjeo':'Seo','sjeo':'seo','Sjela':'Sela',
 'Sjedio':'Sedio','mjesec':'mesec','mjeseca':'meseca','mjeseci':'meseci','mjesta':'mesta',
 'mjestima':'mestima','mjesto':'mesto','umjesto':'umesto','gdje':'gde','Ovdje':'Ovde','ovdje':'ovde',
 'negdje':'negde','drugdje':'drugde','djeca':'deca','Djeca':'Deca','DJECA':'DECA','djece':'dece',
 'djed':'deda','djedova':'dedova','djelovanja':'delovanja','djeluje':'deluje','DJELUJE':'DELUJE',
 'djeluju':'deluju','Djelujte':'Delujte','djelovati':'delovati','djelovao':'delovao',
 'osjetljiva':'osetljiva','osjetljivi':'osetljivi','osjećam':'osećam','osjećanje':'osećanje',
 'Osjećaj':'Osećaj','osjetite':'osetite','osjetiti':'osetiti','osjetio':'osetio','osjetila':'osetila',
 'savjetnik':'savetnik','Savjetnik':'Savetnik','savjetnika':'savetnika','savjetovanje':'savetovanje',
 'vjerovala':'verovala','vjeruje':'veruje','vjerovao':'verovao','uvjerila':'uverila',
 'nepovjerenjem':'nepoverenjem','povjerenje':'poverenje','vjerujem':'verujem','vjerovati':'verovati',
 'Čovjek':'Čovek','čovjek':'čovek','čovjekom':'čovekom','čovjeka':'čoveka','čovjeku':'čoveku',
 'naslijedio':'nasledio','NASLIJEDIO':'NASLEDIO','naslijeđe':'nasleđe','izvještaj':'izveštaj',
 'Izvještaji':'Izveštaji','SMJEŠTAJ':'SMEŠTAJ','pješači':'pešači','pješačila':'pešačila',
 'pješačio':'pešačio','pješke':'peške','visjela':'visila','boljela':'bolela',
 'sprječavaju':'sprečavaju','oklijevanja':'oklevanja','osvježavajte':'osvežavajte',
 'zagrijem':'zagrejem','najljepše':'najlepše','miljeić':'milje','kadulje':'žalfije',
 'pripovijeda':'pripoveda','pretjerujem':'preterujem','mijenjaš':'menjaš','umijem':'umem',
 'zamjenjuju':'zamenjuju','Njemačkoj':'Nemačkoj','Njemačku':'Nemačku','Njemačkoj.':'Nemačkoj.',
 'Švicarsku':'Švajcarsku','Švicarskoj':'Švajcarskoj','sedmica':'nedelja','sedmice':'nedelje',
 'sedmicu':'nedelju','sedmično':'nedeljno','sedmicama':'nedeljama','hiljadu':'hiljadu',
 'uveče':'uveče','ujutru':'ujutru','sjeme':'seme','sjemena':'semena',
}

# 2) имена, обращения и география
GEO = {
 'dedo Salih Mehić':'deda Milorad Jovanović','Dedo Salih Mehić':'Deda Milorad Jovanović',
 'Saliha Mehića':'Milorada Jovanovića','Salih Mehić':'Milorad Jovanović',
 'dedo Salih':'deda Milorad','Dedo Salih':'Deda Milorad','dedom Salihom':'dedom Miloradom',
 'dede Saliha':'dede Milorada','dedi Salihu':'dedi Miloradu','Salih':'Milorad',
 'dedo':'deda','Dedo':'Deda',
 'Konjuha':'Zlatibora','Konjuhu':'Zlatiboru','Konjuh':'Zlatibor',
 'Kladnja':'Čajetine','Kladnju':'Čajetini','Kladanj':'Čajetina',
 'Tuzle':'Užica','Tuzli':'Užicu','Tuzla':'Užice',
 'Olovu':'Ivanjici','Olovo':'Ivanjica',
 'Banovićima':'Boru','Banovića':'Bora','Banovići':'Bor',
 'Sarajeva':'Beograda','Sarajevu':'Beogradu','Sarajevo':'Beograd',
 'Bosne i Hercegovine':'Srbije','Bosni i Hercegovini':'Srbiji','Bosna i Hercegovina':'Srbija',
 'BOSNI I HERCEGOVINI':'SRBIJI','Bosnu i Hercegovinu':'Srbiju',
 'bosanski':'srpski','Bosanski':'Srpski',
 'ZdravljeInfo Bosna i Hercegovina':'ZdravljeInfo Srbija',
 # персонажи историй
 'Zumra':'Zorka','tetkom Mejrom':'tetkom Mirom','tetka Mejra':'tetka Mira','Tetka Mejra':'Tetka Mira',
 'tetke Mejre':'tetke Mire','Mejra':'Mira',
 'tetka Cvijeta':'tetka Cveta','Tetka Cvijeta':'Tetka Cveta','Cvijeta':'Cveta',
 'dedo Rasim':'deda Radisav','Dedo Rasim':'Deda Radisav','Rasime':'Radisave','Rasim':'Radisav',
 'Kada, 72':'Kata, 72','Kada,':'Kata,',
 # имена в комментариях
 'Amra Delić':'Ana Đorđević','Vesna Kovačević':'Vesna Kovačević','Senada Hadžić':'Snežana Ilić',
 'Goran Kralj':'Goran Kralj','Lejla Novalić':'Ljiljana Novaković','Damir Mihić':'Damir Mitić',
 'Danica Rozić':'Danica Rosić','Marijana Golub':'Marijana Golubović','Zoran Savić':'Zoran Savić',
 'Jelena Anđelić':'Jelena Anđelić','Suzana Vrbić':'Suzana Vrbić','Stanka Tomić':'Stanka Tomić',
 'Branko Pavlović':'Branko Pavlović','Jasna Krznarić':'Jasna Krstić','Slavica Gojić':'Slavica Gajić',
 'Igor Lazić':'Igor Lazić','Marta Vrbić':'Marta Vrbić','Adnan Poljić':'Aleksandar Popović',
 'Ivanka Savić':'Ivanka Savić','Boris Rakić':'Boris Rakić','Terezija Kos':'Terezija Kostić',
 'Alija Hrnjić':'Aleksa Hristić','Danice':'Danice','Mirjana':'Mirjana',
}
