# -*- coding: utf-8 -*-
"""STEPLEX → IT."""
T={}
T[0]='STEPLEX — Sir Michael Dixont'
T[1]='ISSN 2784-0391'
T[2]='Edizione speciale • Medicina rigenerativa'
T[3]='The Royal Medical Gazette'
T[4]='Sir Michael Dixont'
T[5]='Già medico personale della Famiglia Reale Britannica'
T[6]='Vol. XLVII • N. 12'
T[7]='Edizione italiana'
T[8]='Esclusiva — prima pubblicazione'
T[9]='Per 34 anni ho curato le articolazioni della Famiglia Reale. Oggi, per la prima volta, rendo questa formula'
T[10]='accessibile'
T[11]='a tutti'
T[12]=('«Ho lasciato Buckingham Palace con una sola certezza: la medicina che praticavo presso la famiglia reale '
       'funziona. E milioni di persone che ne avrebbero bisogno non ne hanno mai sentito parlare. È inaccettabile.»')
T[13]=('Sir Michael Dixont, MD, FRCP. 34 anni di servizio presso la Famiglia Reale Britannica. Cavaliere '
       'dell\'Ordine dell\'Impero Britannico. Fondatore del Dixont Institute of Regenerative Medicine di Cambridge.')
T[14]='✦ ✦ ✦'
T[15]='Sir Michael Dixont, MD, FRCP'
T[16]='Già medico capo della Casa Reale Britannica'
T[17]=('34 anni di servizio presso la Famiglia Reale. Membro del Royal College of Physicians. Cavaliere '
       'dell\'Ordine dell\'Impero Britannico. Fondatore del Dixont Institute of Regenerative Medicine.')
T[18]=('Sono Michael Dixont. Per trentaquattro anni sono stato il medico personale della Famiglia Reale '
       'Britannica. Ho curato articolazioni, colonne vertebrali, ginocchia — anche di persone il cui nome non '
       'posso pronunciare nemmeno ora. Avevo accesso a laboratori, ricerche e principi attivi che la sanità '
       'pubblica non vedrà mai. Non per cattiveria — per ragioni economiche. Ciò che funziona davvero è troppo '
       'costoso su scala industriale, e ciò che si produce su scala industriale cura troppo poco.')
T[19]='Ho lasciato il Palazzo a sessantasette anni. Non per stanchezza — per vergogna. Lasci che le spieghi.'
T[20]=('Un pomeriggio dell\'ultimo anno di servizio, dopo una visita a corte, entrai in un pub di Chelsea. Al '
       'bancone sedeva un uomo sulla sessantina con un tutore elastico al ginocchio, il viso grigio dal dolore, e '
       'ordinava una birra per mandare giù l\'ennesimo ibuprofene. Attaccai discorso — deformazione professionale. '
       'Gli chiesi da quanto tempo soffrisse. «Undici anni» — rispose. «Il mio medico dice che non c\'è niente da '
       'fare. Prendo antidolorifici e aspetto l\'intervento. La lista d\'attesa è di quattordici mesi.»')
T[21]=('Undici anni. Quattordici mesi di lista d\'attesa. Quello stesso giorno io avevo trattato esattamente lo '
       'stesso tipo di articolazione con un protocollo che rigenera la cartilagine in sei settimane. Ma quel '
       'protocollo era riservato a chi vive dentro le mura del Palazzo. All\'uomo seduto al bancone — ex operaio '
       'della Ford di Dagenham, padre di tre figli — toccavano l\'ibuprofene e il tutore.')
T[22]=('In quel momento capii una cosa molto semplice: possedere la cura e non condividerla equivale a non averla '
       'affatto. Trentaquattro anni di servizio reale non valgono nulla se l\'uomo seduto al bancone muore con un '
       'ginocchio distrutto, aspettando un intervento che forse non arriverà mai.')
T[23]='— Sir Michael Dixont'
T[24]=('Tre mesi dopo andai in pensione. Vendetti la casa di Kensington, presi i risparmi di una vita e aprii il '
       'Dixont Institute of Regenerative Medicine a Cambridge. Con me vennero due collaboratori fidati: il dottor '
       'James Harlow, biochimico, con cui avevo lavorato vent\'anni, e la dottoressa Priya Nair, specialista in '
       'formulazioni transdermiche, che aveva sviluppato con me i protocolli reali.')
T[25]=('L\'obiettivo era uno solo: prendere il protocollo che funzionava a Palazzo e trasformarlo in qualcosa che '
       'chiunque potesse usare a casa. Senza iniezioni. Senza ospedale. Senza liste d\'attesa di quattordici mesi.')
T[26]='Il laboratorio del Dixont Institute of Regenerative Medicine, Cambridge. Qui è stata sviluppata la formula transdermica di STEPLEX.'
T[27]='Da sinistra: il dottor James Harlow, Sir Michael Dixont e la dottoressa Priya Nair nel laboratorio di formulazione.'
T[28]='✦ ✦ ✦'
T[29]='Perché l\'Italia — e perché adesso'
T[30]='L\'Italia è stata la nostra prima scelta. Non per caso.'
T[31]=('In Italia la percentuale di malattie articolari è tra le più alte d\'Europa: oltre 2 milioni di persone '
       'sono colpite da una qualche forma di artrosi — quasi un italiano su cinque. Tra gli over 65 questa quota '
       'supera il 60%.')
T[32]=('Ma ciò che ci ha convinti davvero sono le liste d\'attesa. Per una visita ortopedica si aspettano in media '
       '2-3 mesi. Per un intervento di protesi al ginocchio o all\'anca nel servizio pubblico 1-2 anni — in '
       'alcune province anche di più. Centinaia di migliaia di italiani vivono nella trappola del dolore di oggi '
       'e di un intervento che arriverà l\'anno prossimo — o forse mai.')
T[33]=('Quando abbiamo deciso di rendere STEPLEX disponibile anche fuori dal Regno Unito, la scelta è stata '
       'immediata. In Italia il bisogno è il più grande. Ho contattato il professor Giancarlo Amati, primario di '
       'ortopedia in pensione a Milano, che avevo conosciuto a un congresso di Edimburgo nel 2017. Ha testato la '
       'formula su sessanta pazienti nel suo studio privato. I risultati hanno confermato ciò che già sapevamo. '
       'Mi ha detto: «Michael, questo dovrebbe essere in ogni farmacia italiana.»')
T[34]='2 milioni+'
T[35]='Italiani che convivono con una malattia articolare'
T[36]='1-2 anni'
T[37]='Attesa per un intervento di protesi'
T[38]='60 mld Ft'
T[39]='Spesa annua in antidolorifici per le articolazioni'
T[40]='✦ ✦ ✦'
T[41]='Perché le articolazioni si rovinano — e perché nessuno lo spiega'
T[42]=('La verità che nessun ortopedico dice in una visita di sei minuti: l\'articolazione non è un pezzo di ferro '
       'che semplicemente si consuma. È un organismo vivo. La cartilagine si rigenera — ma solo se riceve ciò di '
       'cui ha bisogno.')
T[43]=('In ogni articolazione c\'è la cartilagine — il cuscinetto che impedisce all\'osso di sfregare contro '
       'l\'osso. Intorno a essa il liquido sinoviale, che lubrifica e nutre la cartilagine stessa. Quando questo '
       'sistema funziona, l\'articolazione si muove senza dolore, senza scricchiolii, senza limiti.')
T[44]='Ecco cosa succede con l\'età e l\'usura:'
T[45]=('il liquido sinoviale si riduce, la cartilagine non riceve più nutrimento, comincia a seccarsi e a '
       'sgretolarsi. Osso contro osso. Ogni passo è dolore. E i farmaci? Spengono il segnale d\'allarme — il '
       'dolore — ma non riparano nulla. Anzi: senza dolore si carica ancora di più l\'articolazione, e la '
       'distruzione accelera.')
T[46]=('A Palazzo abbiamo risolto questo problema vent\'anni fa. Con una formula che fa tre cose insieme: '
       'ripristina il liquido sinoviale, fornisce alla cartilagine i mattoni necessari alla ricostruzione e ferma '
       'l\'infiammazione cronica che impedisce la guarigione. Non una delle tre — tutte e tre insieme. È questa '
       'la differenza tra la medicina pubblica e il nostro lavoro.')
T[47]='Come funziona STEPLEX — il protocollo reale, ora in forma di spray'
T[48]=('La sfida più grande non è stata la formula — quella la conoscevamo. La sfida è stata la forma. A Palazzo '
       'usavamo iniezioni intrarticolari: ago direttamente nell\'articolazione, guidato dall\'ecografia, in una '
       'clinica sterile. Perfetto per chi ha un medico personale. Impossibile per chi vive a Palermo, Bari o '
       'Genova e aspetta mesi per una visita ortopedica.')
T[49]=('Alla dottoressa Nair sono serviti quattordici mesi per risolvere il problema. Ha sviluppato un sistema di '
       'penetrazione transdermica basato su liposomi nanostrutturati: microsfere lipidiche che attraversano la '
       'barriera cutanea e portano i principi attivi direttamente nella capsula articolare — esattamente dove '
       'arrivava l\'ago. Senza ago. Senza clinica. Senza dolore.')
T[50]='1'
T[51]='Penetrazione'
T[52]='I liposomi nanostrutturati attraversano la pelle e raggiungono la capsula articolare entro 12 minuti dall\'applicazione.'
T[53]='2'
T[54]='Lubrificazione'
T[55]='L\'acido ialuronico ad alto peso molecolare ripristina il liquido sinoviale, eliminando lo sfregamento osso contro osso.'
T[56]='3'
T[57]='Ricostruzione'
T[58]='Condroitina, glucosamina e collagene di tipo II forniscono i mattoni per la rigenerazione della cartilagine.'
T[59]='4'
T[60]='Protezione'
T[61]='La Boswellia serrata e la curcumina bloccano l\'infiammazione cronica che ostacola la guarigione naturale.'
T[62]='Il risultato è'
T[63]='STEPLEX'
T[64]=('— uno spray da vaporizzare sulla pelle sopra l\'articolazione interessata, due volte al giorno, mattina e '
       'sera. Non unge, si assorbe in due minuti, non ha odore di medicinale. E fa esattamente ciò che a Palazzo '
       'faceva l\'iniezione — ma senza ago.')
T[65]='STEPLEX — la formula transdermica del Dixont Institute. Ogni confezione contiene un trattamento di 30 giorni.'
T[66]='✦ ✦ ✦'
T[67]='Cosa succede se ignora il dolore articolare'
T[68]=('Molti credono che il dolore al ginocchio, all\'anca o alla spalla «venga con l\'età» e che ci si debba '
       'convivere. La verità clinica è un\'altra: il dolore articolare è un segnale d\'allarme. Ignorarlo non è '
       'eroismo — è autodistruzione silenziosa.')
T[69]='Fase I → Fase IV: la distruzione è irreversibile'
T[70]=('Nella cartilagine articolare non ci sono vasi sanguigni. Questo significa che non può rigenerarsi come la '
       'pelle o i muscoli. Ogni giorno che passa senza nutrimento, la cartilagine perde spessore. E questa '
       'perdita non torna da sola.')
T[71]='Fase I'
T[72]='— Dolore occasionale, rigidità mattutina. La cartilagine si assottiglia del 10-15%. Ancora reversibile.'
T[73]='Fase II'
T[74]='— Dolore quotidiano, scricchiolii, difficoltà sulle scale. Perdita del 30-40%. Parzialmente reversibile.'
T[75]='Fase III'
T[76]='— Dolore costante, deformazione visibile, zoppia. Perdita del 60-70%. Possono aiutare solo l\'intervento o un protocollo rigenerativo intensivo.'
T[77]='Fase IV'
T[78]=('— Osso contro osso. Non resta cartilagine. L\'unica possibilità è la protesi artificiale — un intervento '
       'da 3,5 milioni di fiorini con sei mesi di riabilitazione, e nessuna garanzia che il dolore scompaia del '
       'tutto.')
T[79]='Gli antidolorifici non curano. Accelerano la distruzione.'
T[80]=('Ibuprofene, diclofenac, naprossene — i farmaci che centinaia di migliaia di italiani assumono ogni giorno '
       '— non ricostruiscono la cartilagine. Non ne rallentano la distruzione. La mascherano. E nel frattempo:')
T[81]='Danno gastrico:'
T[82]='l\'uso prolungato di FANS provoca ulcera gastrica nel 15-25% dei pazienti cronici.'
T[83]='Danno renale:'
T[84]='dopo 5 anni di assunzione quotidiana il rischio di insufficienza renale cronica aumenta del 58%.'
T[85]='Danno cardiovascolare:'
T[86]='il diclofenac aumenta del 40% il rischio di infarto rispetto a chi non lo assume.'
T[87]='Accelerazione dell\'artrosi:'
T[88]=('senza il segnale del dolore il paziente carica l\'articolazione danneggiata. La cartilagine si consuma '
       'più in fretta. Quando il farmaco smette di fare effetto, la condizione è peggiore di anni.')
T[89]='A sinistra: articolazione sana con cartilagine integra. A destra: artrosi di III grado — la cartilagine è quasi del tutto distrutta.'
T[90]=('Intervento di protesi totale di ginocchio. Costo medio nel privato: 3,5 milioni di Ft. Riabilitazione: 6 '
       'mesi. Lista d\'attesa nel servizio pubblico: fino a 2 anni.')
T[91]='Non aspetti la Fase IV — ordini STEPLEX adesso'
T[92]='✦ ✦ ✦'
T[93]='Composizione — cosa contiene ogni singola applicazione'
T[94]='Formula STEPLEX — Protocollo Dixont'
T[95]='✓'
T[96]='Acido ialuronico ad alto peso molecolare'
T[97]='— 45 mg/applicazione'
T[98]='Ripristina volume e viscosità del liquido sinoviale. Elimina l\'attrito articolare.'
T[99]='✓'
T[100]='Condroitin solfato'
T[101]='— 60 mg/applicazione'
T[102]='Stimola i condrociti a produrre nuova matrice cartilaginea. Rallenta la degradazione enzimatica.'
T[103]='✓'
T[104]='Glucosamina solfato'
T[105]='— 55 mg/applicazione'
T[106]='Precursore dei glicosamminoglicani — il materiale da costruzione della cartilagine.'
T[107]='✓'
T[108]='Collagene di tipo II idrolizzato'
T[109]='— 40 mg/applicazione'
T[110]='Fornisce la struttura fibrosa su cui si ricostruisce la cartilagine danneggiata.'
T[111]='✓'
T[112]='Estratto di Boswellia serrata'
T[113]='— 30 mg/applicazione'
T[114]='Inibitore naturale della 5-lipossigenasi. Blocca l\'infiammazione cronica senza disturbi gastrici.'
T[115]='✓'
T[116]='Curcumina in complesso fosfolipidico'
T[117]='— 25 mg/applicazione'
T[118]='Antinfiammatorio e antiossidante. Il complesso fosfolipidico aumenta di 29 volte la biodisponibilità.'
T[119]='✓'
T[120]='Complesso liposomiale nanostrutturato'
T[121]='— sistema di trasporto'
T[122]='Porta tutti i principi attivi attraverso la barriera cutanea, direttamente nella capsula articolare.'
T[123]='✦ ✦ ✦'
T[124]='Risultati — studio osservazionale su 1.847 pazienti'
T[125]=('Prima di rendere STEPLEX disponibile al pubblico, abbiamo condotto presso il Dixont Institute uno studio '
        'osservazionale di dodici mesi, in collaborazione con tre cliniche ortopediche britanniche. 1.847 '
        'pazienti, età media 62 anni, tutti con diagnosi di osteoartrosi di II-III grado.')
T[126]='Parametro'
T[127]='Prima del trattamento'
T[128]='Dopo 8 settimane'
T[129]='Variazione'
T[130]='Dolore articolare (scala VAS)'
T[131]='7,4 / 10'
T[132]='2,1 / 10'
T[133]='−71,6%'
T[134]='Mobilità articolare'
T[135]='41% della norma'
T[136]='84% della norma'
T[137]='+104,9%'
T[138]='Spessore della cartilagine (ecografia)'
T[139]='1,2 mm'
T[140]='2,1 mm'
T[141]='+75%'
T[142]='Uso di antidolorifici'
T[143]='quotidiano (89%)'
T[144]='occasionale (12%)'
T[145]='−86,5%'
T[146]='Quota di pazienti che hanno evitato l\'intervento'
T[147]='—'
T[148]='78,3%'
T[149]=('Partecipanti allo studio osservazionale del Dixont Institute. Età media: 62 anni. Durata: 12 mesi. 1.847 '
        'pazienti con osteoartrosi di II-III grado.')
T[150]='Nota del ricercatore:'
T[151]=('Il 78,3% dei pazienti inizialmente in attesa di una protesi totale di ginocchio o anca ha potuto evitare '
        'l\'intervento dopo due cicli di STEPLEX. La serie completa dei dati è disponibile nel registro del '
        'Dixont Institute (rif. DI-2024-ART-1847).')
T[152]='Provi STEPLEX — Paga solo alla consegna'
T[153]='✦ ✦ ✦'
T[154]='Perché il suo medico non gliene parla'
T[155]='Me lo chiedono spesso. La risposta è semplice e non ha nulla a che vedere con complotti o malafede.'
T[156]=('Il medico di famiglia ha sette minuti per paziente. In sette minuti può fare una cosa sola: prescrivere '
        'ciò che conosce. Conosce gli antidolorifici, conosce le infiltrazioni di cortisone, conosce la lista '
        'd\'attesa per la protesi. Il suo manuale finisce lì. Non perché sia incompetente — ma perché il sistema '
        'è costruito così. Un sistema che guadagna sui farmaci quotidiani e sulle protesi da milioni non ha alcun '
        'interesse economico a far sapere che esiste un\'alternativa applicabile a casa in due minuti.')
T[157]='Un dato che può far riflettere:'
T[158]=('In Italia il mercato degli antidolorifici per le articolazioni vale 60 miliardi di fiorini l\'anno. Il '
        'mercato delle protesi articolari 40 miliardi. Insieme fanno 100 miliardi. Nessun settore da 100 miliardi '
        'si smantella da solo. Non è un complotto — è economia.')
T[159]=('Io non ho più nulla da perdere. Non vendo farmaci. Non ho quote in cliniche ortopediche. Ho una pensione '
        'britannica e una coscienza che non mi lascia dormire finché so che l\'uomo seduto al bancone del pub — e '
        'milioni come lui — aspettano un intervento che uno spray potrebbe rendere superfluo.')
T[160]='✦ ✦ ✦'
T[161]='Come si usa STEPLEX'
T[162]=('Vaporizzi due o tre spruzzi sulla zona interessata da una distanza di 10-15 cm — ginocchio, anca, spalla, '
        'mano, caviglia, colonna — due volte al giorno: mattina e sera, su pelle pulita e asciutta. Si può '
        'distribuire con qualche movimento circolare. Lo spray si assorbe completamente in due minuti. Non lascia '
        'macchie, non unge, non ha odore di medicinale.')
T[163]=('Il primo ciclo dura 30 giorni. La maggior parte dei pazienti avverte una riduzione significativa del '
        'dolore già nella prima settimana. Per il ripristino strutturale della cartilagine servono 6-8 settimane '
        'di uso continuativo. Nei casi più avanzati (artrosi di III grado) consigliamo due cicli consecutivi.')
T[164]='✦ ✦ ✦'
T[165]='Una richiesta personale'
T[166]=('Ho settantun anni. Non ho molto tempo e non ho bisogno di denaro. Ho bisogno di sapere che la formula che '
        'per trentaquattro anni ha funzionato dietro le mura del Palazzo arriva finalmente a chi ne ha davvero '
        'bisogno.')
T[167]=('Se ha superato i quarantacinque anni e la mattina si alza «a pezzi». Se le scale sono diventate un '
        'nemico. Se con il ginocchio sente il tempo prima dei meteorologi. Se sul comodino si allineano scatole '
        'di antidolorifici e non va comunque meglio. Se le hanno detto: «che vuole, è l\'età» — non ci creda. '
        'L\'età è una causa, non una condanna.')
T[168]=('Sotto questo testo trova un modulo. Inserisca il suo nome e il suo numero di telefono. Un consulente la '
        'richiamerà, le farà qualche domanda sulla sua condizione, sceglierà il ciclo più adatto e glielo farà '
        'recapitare a casa con corriere. Paga solo alla consegna — non chiediamo alcun anticipo. Su questa '
        'condizione ho insistito personalmente: chi soffre non deve rischiare un solo fiorino prima di avere il '
        'prodotto in mano.')
T[169]=('E se non sta leggendo per sé, ma pensando a sua madre, a suo padre, a un nonno che vive solo e a ogni '
        'telefonata dice: «sto bene, non preoccuparti» — non aspetti. Fino all\'ultimo diranno «sto bene», perché '
        'non vogliono essere un peso. Non lasci che la persona che ama diventi in silenzio prigioniera di casa '
        'sua.')
T[170]='Modulo d\'ordine ufficiale'
T[171]='N.'
T[172]='19'
T[173]='974'
T[174]='/ 20'
T[175]='000'
T[176]='Per usufruire dello sconto del 50% inserisca nome e numero di telefono nei campi qui sotto e prema il pulsante «ORDINO».'
T[177]='Disponibili:'
T[178]='33'
T[179]='/ 1000'
T[180]='19800\n            HUF'
T[181]='9900\n            HUF'
T[182]='Nome'
T[183]='Numero di telefono'
T[184]='ORDINO ADESSO'
T[185]='✔️ La consegna è effettuata dal Centro Sanitario Nazionale direttamente all\'indirizzo indicato. Recapito entro 2-3 giorni lavorativi con corriere.'
T[186]='Commenti dei lettori'
T[187]='Bruno C., Torino'
T[188]=('Ho 63 anni, per otto anni ho preso antidolorifici per il ginocchio destro. L\'ortopedico mi ha messo in '
        'lista d\'attesa per la protesi — tempo previsto: 11 mesi. Ho provato STEPLEX per curiosità, non ci '
        'credevo granché. Dopo tre settimane mi sono alzato dalla sedia senza aggrapparmi al tavolo. Dopo sei '
        'settimane sono sceso in cantina — per la prima volta in due anni. Ho chiamato l\'ospedale e ho detto che '
        'per ora la protesi non la voglio.')
T[189]='Elisabetta N., Bologna'
T[190]=('Mattina e sera vaporizzo sulle mani. Cucio da quarant\'anni, le dita mi si erano irrigidite come '
        'bastoncini — non riuscivo più a infilare il filo nell\'ago. Dopo un mese ho ripreso a cucire. Le mie '
        'clienti pensavano che mi avessero operata. No, cari miei. Uno spray, due volte al giorno, e basta.')
T[191]='Stefano F., Firenze'
T[192]=('Me l\'ha ordinato mia moglie, perché io non ci credevo. «Un\'altra truffa» — dicevo. Dopo due settimane '
        'ho smesso con l\'ibuprofene. Dopo un mese faccio di nuovo le scale senza reggermi. Mia moglie non dice '
        '«te l\'avevo detto» — lo pensa soltanto, e io le sono grato.')
T[193]='Andrea V., Roma'
T[194]=('L\'ho comprato per mia madre, 78 anni, artrosi all\'anca. Da due anni non scendeva le scale del '
        'condominio — noi figli le portavamo su la spesa. Dopo sei settimane di STEPLEX è scesa da sola al bar '
        'sotto casa. Il barista la guardava come se vedesse un fantasma. Ha preso un caffè, ha mangiato un '
        'cornetto e mi ha chiamato piangendo. Di gioia. La sera stessa ho ordinato il secondo ciclo.')
T[195]='Giuseppe L., Napoli'
T[196]=('Ho sessantanove anni, ex muratore, la spalla destra rovinata. Il chirurgo voleva operare, io non volevo '
        'l\'anestesia — a sessantanove anni ne ho paura. Un amico mi ha mandato questo articolo. Due mesi di '
        'spray. All\'ultimo controllo il chirurgo guardava l\'ecografia, poi me, poi di nuovo l\'ecografia. «Cosa '
        'ha fatto?» — mi ha chiesto. «Uno spray» — ho risposto. Non ha commentato. Ma l\'intervento l\'ha '
        'cancellato dal calendario.')
T[197]='🏫'
T[198]='Sviluppato a Cambridge (UK)'
T[199]='💬'
T[200]='Consulenza gratuita'
T[201]='🚚'
T[202]='Corriere in 2-3 giorni'
T[203]='💰'
T[204]='Pagamento alla consegna'
T[205]=('© Dixont Institute of Regenerative Medicine, Cambridge, UK. Tutti i diritti riservati. Le informazioni '
        'contenute in questa pagina hanno carattere informativo e non sostituiscono il parere medico.')
T[206]='{_box:2sHZz2rc}'
T[207]='Sono Michael Dixont.'
