# -*- coding: utf-8 -*-
"""STEPLEX → LT. Локализация без изменения сюжета, цифр и медицинских утверждений."""
T={}
T[0]='STEPLEX — Sir Michael Dixont'
T[1]='ISSN 2784-0391'
T[2]='Specialusis leidimas • Regeneracinė medicina'
T[3]='The Royal Medical Gazette'
T[4]='Sir Michael Dixont'
T[5]='Buvęs Britų karališkosios šeimos asmeninis gydytojas'
T[6]='Vol. XLVII • N. 12'
T[7]='Lietuviškas leidimas'
T[8]='Išskirtinai — pirmoji publikacija'
T[9]='34 metus gydžiau Karališkosios šeimos sąnarius. Šiandien pirmą kartą šią formulę padarau'
T[10]='visiems'
T[11]='prieinamą'
T[12]=('«Bakingamo rūmus palikau būdamas tikras dėl vieno dalyko: medicina, kurią praktikavau karališkojoje '
       'šeimoje, veikia. Ir milijonai žmonių, kuriems jos reikėtų, apie ją net nėra girdėję. Tai nepriimtina.»')
T[13]=('Sir Michael Dixont, MD, FRCP. 34 metai tarnybos Britų karališkojoje šeimoje. Britų imperijos ordino '
       'riteris. Kembridžo Dixont Institute of Regenerative Medicine įkūrėjas.')
T[14]='✦ ✦ ✦'
T[15]='Sir Michael Dixont, MD, FRCP'
T[16]='Buvęs Britų karališkųjų rūmų vyriausiasis gydytojas'
T[17]=('34 metai tarnybos Karališkojoje šeimoje. Royal College of Physicians narys. Britų imperijos ordino '
       'riteris. Dixont Institute of Regenerative Medicine įkūrėjas.')
T[18]=('Esu Michael Dixont. Trisdešimt ketverius metus buvau Britų karališkosios šeimos asmeninis gydytojas. '
       'Gydžiau sąnarius, stuburus, kelius — taip pat žmonių, kurių vardų iki šiol negaliu ištarti. Turėjau '
       'prieigą prie laboratorijų, tyrimų ir veikliųjų medžiagų, kurių valstybinė sveikatos apsauga niekada '
       'nepamatys. Ne iš piktavališkumo — dėl ekonominių priežasčių. Tai, kas iš tiesų veikia, pramoniniu mastu '
       'per brangu, o tai, kas gaminama pramoniniu mastu, per mažai išgydo.')
T[19]='Rūmus palikau būdamas šešiasdešimt septynerių. Ne iš nuovargio — iš gėdos. Leiskite paaiškinti.'
T[20]=('Paskutiniais tarnybos metais, vieną popietę po vizito rūmuose, užsukau į vieną Čelsio barą. Prie baro '
       'sėdėjo apie šešiasdešimties vyras su elastiniu kelio įtvaru, jo veidas buvo pilkas nuo skausmo, ir jis '
       'užsisakė alaus, kad juo užgertų eilinį ibuprofeną. Užkalbinau jį — profesinė yda. Paklausiau, kiek laiko '
       'jis kenčia. «Vienuolika metų» — atsakė. «Mano gydytojas sako, kad nieko negalima padaryti. Geriu skausmą '
       'malšinančius ir laukiu operacijos. Eilė — keturiolika mėnesių.»')
T[21]=('Vienuolika metų. Keturiolikos mėnesių eilė. Tą pačią dieną aš gydžiau lygiai tokio paties tipo sąnarį '
       'protokolu, kuris per šešias savaites atstato kremzlę. Bet tas protokolas buvo skirtas tiems, kurie gyvena '
       'už Rūmų sienų. Prie baro sėdinčiam vyrui — buvusiam Dagenhamo Ford gamyklos darbininkui, trijų vaikų '
       'tėvui — teko tenkintis ibuprofenu ir kelio įtvaru.')
T[22]=('Tą akimirką supratau vieną labai paprastą dalyką: turėti gydymo būdą ir juo nesidalyti yra tas pats, kas '
       'jo išvis neturėti. Trisdešimt ketveri metai karališkosios tarnybos nieko neverti, jei prie baro sėdintis '
       'žmogus miršta su sugriautu keliu, laukdamas operacijos, kuri galbūt niekada neateis.')
T[23]='— Sir Michael Dixont'
T[24]=('Po trijų mėnesių išėjau į pensiją. Pardaviau namą Kensingtone, paėmiau visą gyvenimą kauptas santaupas ir '
       'Kembridže atidariau Dixont Institute of Regenerative Medicine. Kartu su manimi atėjo du patikimi '
       'bendradarbiai: biochemikas dr. James Harlow, su kuriuo dirbau dvidešimt metų, ir dr. Priya Nair, '
       'transderminių formulių specialistė, kuri kartu su manimi kūrė karališkuosius protokolus.')
T[25]=('Tikslas buvo vienas: paimti protokolą, kuris veikė Rūmuose, ir paversti jį kažkuo, ką bet kas galėtų '
       'naudoti namuose. Be injekcijų. Be ligoninės. Be keturiolikos mėnesių eilių.')
T[26]=('Dixont Institute of Regenerative Medicine laboratorija, Kembridžas. Būtent čia buvo sukurta transderminė '
       'STEPLEX formulė.')
T[27]='Iš kairės: dr. James Harlow, Sir Michael Dixont ir dr. Priya Nair formulių kūrimo laboratorijoje.'
T[28]='✦ ✦ ✦'
T[29]='Kodėl Lietuva — ir kodėl dabar'
T[30]='Lietuva buvo mūsų pirmasis pasirinkimas. Ne atsitiktinai.'
T[31]=('Lietuvoje sąnarių ligų paplitimas yra vienas didžiausių Europoje: daugiau nei 600 000 žmonių paliečia kokia nors '
       'artrozės forma — beveik kas penktas Lietuvos gyventojas. Tarp vyresnių nei 65 metų šis rodiklis viršija 60%.')
T[32]=('Bet tai, kas mus iš tiesų įtikino, yra laukimo eilės. Pas ortopedą vidutiniškai tenka laukti 2–3 mėnesius. '
       'Kelio ar klubo protezavimo operacijos valstybinėje sistemoje — 1–2 metus, kai kuriuose rajonuose dar '
       'ilgiau. Dešimtys tūkstančių lietuvių gyvena šiandienos skausmo ir operacijos, kuri ateis kitąmet — o gal '
       'niekada — spąstuose.')
T[33]=('Kai nusprendėme padaryti STEPLEX prieinamą ir už Jungtinės Karalystės ribų, pasirinkimas buvo akivaizdus. '
       'Lietuvoje poreikis didžiausias. Susisiekiau su profesoriumi Gediminu Alekna, buvusiu Vilniaus ligoninės '
       'Ortopedijos skyriaus vedėju, su kuriuo susipažinau 2017 metais Edinburgo kongrese. Jis išbandė formulę su '
       'šešiasdešimčia pacientų savo privačiame kabinete. Rezultatai patvirtino tai, ką jau žinojome. Jis man '
       'pasakė: «Michael, tai turėtų būti kiekvienoje Lietuvos vaistinėje.»')
T[34]='600 000+'
T[35]='Lietuvių, gyvenančių su sąnarių liga'
T[36]='1–2 metai'
T[37]='Laukimas protezavimo operacijos'
T[38]='60 mlrd. Ft'
T[39]='Metinės išlaidos sąnarių skausmą malšinantiems vaistams'
T[40]='✦ ✦ ✦'
T[41]='Kodėl genda sąnariai — ir kodėl niekas to nepaaiškina'
T[42]=('Tiesa, kurios nė vienas ortopedas nepasako per šešių minučių apžiūrą: sąnarys nėra geležies gabalas, kuris '
       'tiesiog nusidėvi. Tai gyvas organizmas. Kremzlė regeneruojasi — bet tik tada, kai gauna tai, ko jai reikia.')
T[43]=('Kiekviename sąnaryje yra kremzlė — pagalvėlė, neleidžianti kaului trintis į kaulą. Aplink ją — sąnario '
       'skystis, kuris tepa ir maitina pačią kremzlę. Kai ši sistema veikia, sąnarys juda be skausmo, be '
       'traškėjimo, be apribojimų.')
T[44]='Štai kas vyksta su amžiumi ir nusidėvėjimu:'
T[45]=('sąnario skysčio sumažėja, kremzlė nebegauna maitinimo, pradeda džiūti ir trupėti. Kaulas į kaulą. '
       'Kiekvienas žingsnis — skausmas. O vaistai? Jie išjungia pavojaus signalą — skausmą — bet nieko nepataiso. '
       'Maža to: be skausmo sąnarys apkraunamas dar labiau, ir irimas paspartėja.')
T[46]=('Rūmuose šią problemą išsprendėme prieš dvidešimt metų. Formule, kuri daro tris dalykus vienu metu: '
       'atstato sąnario skystį, aprūpina kremzlę atstatymui reikalingomis statybinėmis medžiagomis ir sustabdo '
       'lėtinį uždegimą, kuris trukdo gijimui. Ne vieną iš trijų — visus tris kartu. Tuo ir skiriasi valstybinė '
       'medicina nuo mūsų darbo.')
T[47]='Kaip veikia STEPLEX — karališkasis protokolas, dabar purškiklio pavidalu'
T[48]=('Didžiausias iššūkis buvo ne formulė — ją žinojome. Iššūkis buvo forma. Rūmuose naudojome injekcijas į '
       'sąnarį: adata tiesiai į sąnarį, valdoma ultragarsu, sterilioje klinikoje. Tobula tam, kas turi asmeninį '
       'gydytoją. Neįmanoma tam, kas gyvena Šiauliuose, Panevėžyje ar Klaipėdoje ir mėnesių mėnesius laukia '
       'ortopedo apžiūros.')
T[49]=('Dr. Nair prireikė keturiolikos mėnesių šiai problemai išspręsti. Ji sukūrė transderminę prasiskverbimo '
       'sistemą, pagrįstą nanostruktūrinėmis liposomomis: lipidų mikrorutuliukais, kurie prasiskverbia pro odos '
       'barjerą ir veikliąsias medžiagas pristato tiesiai į sąnario kapsulę — būtent ten, kur patekdavo adata. Be '
       'adatos. Be klinikos. Be skausmo.')
T[50]='1'
T[51]='Prasiskverbimas'
T[52]='Nanostruktūrinės liposomos prasiskverbia pro odą ir per 12 minučių nuo užpurškimo pasiekia sąnario kapsulę.'
T[53]='2'
T[54]='Tepimas'
T[55]='Didelės molekulinės masės hialurono rūgštis atstato sąnario skystį, panaikindama kaulo į kaulą trintį.'
T[56]='3'
T[57]='Atstatymas'
T[58]='Chondroitinas, gliukozaminas ir II tipo kolagenas suteikia statybines medžiagas kremzlės regeneracijai.'
T[59]='4'
T[60]='Apsauga'
T[61]='Boswellia serrata ir kurkuminas blokuoja lėtinį uždegimą, trukdantį natūraliam gijimui.'
T[62]='Rezultatas —'
T[63]='STEPLEX'
T[64]=('— purškiklis, kurį reikia purkšti ant odos virš pažeisto sąnario du kartus per dieną, ryte ir vakare. '
       'Neriebaluoja, susigeria per dvi minutes, nėra vaistų kvapo. Ir daro būtent tai, ką Rūmuose darė injekcija '
       '— tik be adatos.')
T[65]='STEPLEX — Dixont Institute transderminė formulė. Kiekvienoje pakuotėje — 30 dienų kursas.'
T[66]='✦ ✦ ✦'
T[67]='Kas nutinka, jei ignoruojate sąnarių skausmą'
T[68]=('Daugelis mano, kad kelio, klubo ar peties skausmas «ateina su amžiumi» ir su juo reikia gyventi. Klinikinė '
       'tiesa kitokia: sąnario skausmas yra pavojaus signalas. Jį ignoruoti — ne didvyriškumas, o tylus savęs '
       'naikinimas.')
T[69]='I stadija → IV stadija: irimas negrįžtamas'
T[70]=('Sąnario kremzlėje nėra kraujagyslių. Tai reiškia, kad ji negali regeneruotis taip, kaip oda ar raumenys. '
       'Kiekviena diena, praleista be maitinimo, kremzlei atima storio. Ir šis praradimas savaime negrįžta.')
T[71]='I stadija'
T[72]='— Retkarčiais skausmas, rytinis sustingimas. Kremzlė suplonėja 10–15%. Dar grįžtama.'
T[73]='II stadija'
T[74]='— Kasdienis skausmas, traškėjimas, sunkumas ant laiptų. 30–40% praradimas. Iš dalies grįžtama.'
T[75]='III stadija'
T[76]='— Nuolatinis skausmas, matoma deformacija, šlubavimas. 60–70% praradimas. Padėti gali tik operacija arba intensyvus regeneracinis protokolas.'
T[77]='IV stadija'
T[78]=('— Kaulas į kaulą. Kremzlės nebeliko. Vienintelė galimybė — dirbtinis protezas: 3,5 milijono forintų '
       'kainuojanti operacija su šešių mėnesių reabilitacija ir jokios garantijos, kad skausmas visiškai praeis.')
T[79]='Skausmą malšinantys vaistai negydo. Jie greitina irimą.'
T[80]=('Ibuprofenas, diklofenakas, naproksenas — vaistai, kuriuos kasdien geria dešimtys tūkstančių lietuvių — '
       'neatstato kremzlės. Nelėtina jos irimo. Jie jį užmaskuoja. Ir tuo pat metu:')
T[81]='Skrandžio pažeidimas:'
T[82]='ilgalaikis NVNU vartojimas 15–25% lėtinių ligonių sukelia skrandžio opą.'
T[83]='Inkstų pažeidimas:'
T[84]='po 5 metų kasdienio vartojimo lėtinio inkstų nepakankamumo rizika padidėja 58%.'
T[85]='Širdies ir kraujagyslių pažeidimas:'
T[86]='diklofenakas 40% padidina infarkto riziką, palyginti su tais, kurie jo nevartoja.'
T[87]='Artrozės paspartėjimas:'
T[88]=('be skausmo signalo ligonis apkrauna pažeistą sąnarį. Kremzlė dyla greičiau. Kai vaistas nustoja veikti, '
       'būklė jau keleriais metais blogesnė.')
T[89]='Kairėje: sveikas sąnarys su nepažeista kremzle. Dešinėje: III laipsnio artrozė — kremzlė beveik visiškai sunaikinta.'
T[90]=('Visiško kelio protezavimo operacija. Vidutinė kaina privačiai: 3,5 mln. Ft. Reabilitacija: 6 mėnesiai. '
       'Laukimo eilė valstybinėje sistemoje: iki 2 metų.')
T[91]='Nelaukite IV stadijos — užsisakykite STEPLEX dabar'
T[92]='✦ ✦ ✦'
T[93]='Sudėtis — ką turi kiekvienas užpurškimas'
T[94]='STEPLEX formulė — Dixont protokolas'
T[95]='✓'
T[96]='Didelės molekulinės masės hialurono rūgštis'
T[97]='— 45 mg/užpurškimui'
T[98]='Atstato sąnario skysčio tūrį ir klampumą. Panaikina sąnario trintį.'
T[99]='✓'
T[100]='Chondroitino sulfatas'
T[101]='— 60 mg/užpurškimui'
T[102]='Skatina kremzlės ląsteles gaminti naują kremzlės matricą. Lėtina fermentinį ardymą.'
T[103]='✓'
T[104]='Gliukozamino sulfatas'
T[105]='— 55 mg/užpurškimui'
T[106]='Glikozaminoglikanų pirmtakas — kremzlės statybinė medžiaga.'
T[107]='✓'
T[108]='Hidrolizuotas II tipo kolagenas'
T[109]='— 40 mg/užpurškimui'
T[110]='Suteikia pluoštinę struktūrą, ant kurios atsistato pažeista kremzlė.'
T[111]='✓'
T[112]='Boswellia serrata ekstraktas'
T[113]='— 30 mg/užpurškimui'
T[114]='Natūralus 5-lipoksigenazės slopiklis. Blokuoja lėtinį uždegimą be skrandžio negalavimų.'
T[115]='✓'
T[116]='Kurkuminas fosfolipidų komplekse'
T[117]='— 25 mg/užpurškimui'
T[118]='Priešuždegiminis ir antioksidantas. Fosfolipidų kompleksas 29 kartus padidina biologinį prieinamumą.'
T[119]='✓'
T[120]='Nanostruktūrinis liposomų kompleksas'
T[121]='— pernešimo sistema'
T[122]='Perneša visas veikliąsias medžiagas pro odos barjerą tiesiai į sąnario kapsulę.'
T[123]='✦ ✦ ✦'
T[124]='Rezultatai — stebimasis tyrimas su 1 847 pacientais'
T[125]=('Prieš padarydami STEPLEX prieinamą visuomenei, Dixont Institute atlikome dvylikos mėnesių stebimąjį '
        'tyrimą bendradarbiaudami su trimis britų ortopedijos klinikomis. 1 847 pacientai, vidutinis amžius 62 '
        'metai, visiems diagnozuota II–III laipsnio osteoartrozė.')
T[126]='Rodiklis'
T[127]='Prieš gydymą'
T[128]='Po 8 savaičių'
T[129]='Pokytis'
T[130]='Sąnarių skausmas (VAS skalė)'
T[131]='7,4 / 10'
T[132]='2,1 / 10'
T[133]='−71,6%'
T[134]='Sąnarių judrumas'
T[135]='41% normos'
T[136]='84% normos'
T[137]='+104,9%'
T[138]='Kremzlės storis (ultragarsu)'
T[139]='1,2 mm'
T[140]='2,1 mm'
T[141]='+75%'
T[142]='Skausmą malšinančių vaistų vartojimas'
T[143]='kasdien (89%)'
T[144]='retkarčiais (12%)'
T[145]='−86,5%'
T[146]='Operacijos išvengusių pacientų dalis'
T[147]='—'
T[148]='78,3%'
T[149]=('Dixont Institute stebimojo tyrimo dalyviai. Vidutinis amžius: 62 metai. Trukmė: 12 mėnesių. 1 847 '
        'pacientai su II–III laipsnio osteoartroze.')
T[150]='Tyrėjo pastaba:'
T[151]=('78,3% pacientų, iš pradžių laukusių visiško kelio ar klubo protezavimo, po dviejų STEPLEX kursų '
        'operacijos išvengė. Visas duomenų rinkinys prieinamas Dixont Institute registre (nuor. DI-2024-ART-1847).')
T[152]='Išbandykite STEPLEX — mokate tik atsiimdami'
T[153]='✦ ✦ ✦'
T[154]='Kodėl jūsų gydytojas jums apie tai nepasakoja'
T[155]='Manęs to dažnai klausia. Atsakymas paprastas ir neturi nieko bendra su sąmokslu ar piktavališkumu.'
T[156]=('Šeimos gydytojas vienam pacientui turi septynias minutes. Per septynias minutes jis gali padaryti vieną '
        'dalyką: išrašyti tai, ką žino. Jis žino skausmą malšinančius, žino kortizono injekcijas, žino protezų '
        'laukimo eilę. Jo vadovėlis ten baigiasi. Ne todėl, kad jis nekompetentingas — o todėl, kad sistema taip '
        'sukurta. Sistema, kuri uždirba iš kasdienių vaistų ir milijoninių protezų, neturi jokio ekonominio '
        'intereso pranešti, kad egzistuoja namuose per dvi minutes pritaikoma alternatyva.')
T[157]='Skaičius, kuris gali priversti susimąstyti:'
T[158]=('Lietuvoje sąnarių skausmą malšinančių vaistų rinka vertinama 60 milijardų forintų per metus. Sąnarių '
        'protezų rinka — 40 milijardų. Kartu tai 100 milijardų. Nė viena 100 milijardų vertės pramonės šaka '
        'savanoriškai savęs nelikviduoja. Tai ne sąmokslas — tai ekonomika.')
T[159]=('Man nebėra ko prarasti. Aš neprekiauju vaistais. Neturiu akcijų ortopedijos klinikose. Turiu britišką '
        'pensiją ir sąžinę, kuri neleidžia miegoti, kol žinau, kad prie baro sėdėjęs žmogus — ir milijonai '
        'panašių į jį — laukia operacijos, kurią purškiklis galėtų padaryti nereikalingą.')
T[160]='✦ ✦ ✦'
T[161]='Kaip naudoti STEPLEX'
T[162]=('Du tris purškimus reikia nukreipti į pažeistą vietą iš 10–15 cm atstumo — kelis, klubas, petys, plaštaka, '
        'kulkšnis, stuburas — du kartus per dieną: ryte ir vakare, ant švarios, sausos odos. Galima paskirstyti '
        'keliais sukamaisiais judesiais. Purškiklis visiškai susigeria per dvi minutes. Nepalieka dėmių, '
        'neriebaluoja, nėra vaistų kvapo.')
T[163]=('Pirmasis kursas — 30 dienų. Dauguma pacientų reikšmingą skausmo sumažėjimą pajunta jau pirmą savaitę. '
        'Kremzlės struktūriniam atsistatymui reikia 6–8 savaičių nuolatinio naudojimo. Pažengusiais atvejais (III '
        'laipsnio artrozė) rekomenduojame du kursus iš eilės.')
T[164]='✦ ✦ ✦'
T[165]='Asmeninis prašymas'
T[166]=('Man septyniasdešimt vieneri. Laiko nedaug, o pinigų man nereikia. Man reikia žinoti, kad formulė, kuri '
        'trisdešimt ketverius metus veikė už Rūmų sienų, pagaliau pasiekia tuos, kuriems jos iš tiesų reikia.')
T[167]=('Jei jums per keturiasdešimt penkerius ir rytais keliatės «sudužęs». Jei laiptai tapo priešu. Jei orą '
        'keliu pajuntate anksčiau nei meteorologai. Jei ant naktinio staliuko rikiuojasi skausmą malšinančių '
        'vaistų dėžutės, o geriau vis tiek nėra. Jei jums pasakė: «ko norite, toks amžius» — netikėkite. Amžius '
        'yra priežastis, o ne nuosprendis.')
T[168]=('Po šiuo tekstu rasite formą. Įrašykite savo vardą ir telefono numerį. Konsultantas jums paskambins, '
        'užduos kelis klausimus apie jūsų būklę, parinks tinkamiausią kursą ir pristatys kurjeriu į namus. Mokate '
        'tik atsiimdami — jokio išankstinio mokėjimo neprašome. Šios sąlygos pareikalavau asmeniškai: kas kenčia, '
        'tegul nerizikuoja nė vienu forintu, kol prekė nėra jo rankose.')
T[169]=('O jei tai skaitote ne dėl savęs, o galvodami apie mamą, tėtį, vienišą senelį, kuris kiekvieno skambučio '
        'metu sako: «man viskas gerai, nesijaudink» — nelaukite. Iki paskutinės akimirkos jie sakys «man viskas '
        'gerai», nes nenori būti našta. Neleiskite, kad jūsų artimasis tyliai taptų savo namų kaliniu.')
T[170]='Oficiali užsakymo forma'
T[171]='Nr.'
T[172]='19'
T[173]='974'
T[174]='/ 20'
T[175]='000'
T[176]='Norėdami pasinaudoti 50% nuolaida, įrašykite savo vardą ir telefono numerį į laukelius žemiau ir paspauskite mygtuką «UŽSISAKAU».'
T[177]='Sandėlyje:'
T[178]='33'
T[179]='/ 1000'
T[180]='19800\n            HUF'
T[181]='9900\n            HUF'
T[182]='Vardas'
T[183]='Telefono numeris'
T[184]='UŽSISAKAU DABAR'
T[185]='✔️ Pristatymą vykdo Nacionalinis sveikatos centras tiesiai nurodytu adresu. Pristatymas per 2–3 darbo dienas kurjeriu.'
T[186]='Skaitytojų komentarai'
T[187]='Kęstutis B., Šiauliai'
T[188]=('Man 63 metai, aštuonerius metus gėriau skausmą malšinančius dėl dešinio kelio. Ortopedas įrašė mane į '
        'protezavimo eilę — numatomas laikas 11 mėnesių. Iš smalsumo išbandžiau STEPLEX, labai netikėjau. Po '
        'trijų savaičių atsistojau nuo kėdės nesilaikydamas stalo. Po šešių savaičių nulipau į rūsį — pirmą kartą '
        'per dvejus metus. Paskambinau į ligoninę ir pasakiau, kad kol kas protezo neprašau.')
T[189]='Elena N., Kaunas'
T[190]=('Ryte ir vakare purškiu ant plaštakų. Keturiasdešimt metų siuvu, pirštai sustingo kaip pagaliukai — '
        'nebegalėjau įverti siūlo į adatą. Po mėnesio vėl pradėjau siūti. Klientės manė, kad man padarė operaciją. '
        'Ne, prašau. Purškiklis du kartus per dieną, ir tiek.')
T[191]='Stasys F., Klaipėda'
T[192]=('Žmona man jį užsakė, nes aš netikėjau. «Vėl kokia nors apgavystė» — sakiau. Po dviejų savaičių nustojau '
        'gerti ibuprofeną. Po mėnesio vėl lipu laiptais nesilaikydamas. Žmona nesako «aš tau sakiau» — tik '
        'galvoja, o aš jai dėkingas.')
T[193]='Aldona V., Vilnius'
T[194]=('Nupirkau mamai, jai 78 metai, klubo artrozė. Dvejus metus nebuvo nusileidusi laiptinėje — mes, vaikai, '
        'nešdavome jai pirkinius. Po šešių savaičių su STEPLEX ji viena nusileido į kavinę po namu. Barmenas '
        'žiūrėjo į ją kaip į vaiduoklį. Išgėrė kavos, suvalgė bandelę su kakava ir verkdama man paskambino. Iš '
        'džiaugsmo. Tą patį vakarą užsakiau antrą kursą.')
T[195]='Juozas L., Panevėžys'
T[196]=('Man šešiasdešimt devyneri, buvęs mūrininkas, dešinys petys sugedo. Chirurgas norėjo operuoti, aš '
        'nenorėjau narkozės — šešiasdešimt devynerių jos bijau. Draugas atsiuntė man šį straipsnį. Du mėnesiai '
        'purškiklio. Per paskutinį patikrinimą chirurgas žiūrėjo į echoskopiją, paskui į mane, paskui vėl į '
        'echoskopiją. «Ką jūs darėte?» — paklausė. «Purškiklį» — atsakiau. Nekomentavo. Bet operaciją iš '
        'kalendoriaus išbraukė.')
T[197]='🏫'
T[198]='Sukurta Kembridže (JK)'
T[199]='💬'
T[200]='Nemokama konsultacija'
T[201]='🚚'
T[202]='Kurjeris per 2–3 dienas'
T[203]='💰'
T[204]='Mokėjimas atsiimant'
T[205]=('© Dixont Institute of Regenerative Medicine, Cambridge, UK. Visos teisės saugomos. Šiame puslapyje '
        'pateikta informacija yra informacinio pobūdžio ir nepakeičia gydytojo konsultacijos.')
T[206]='{_box:2sHZz2rc}'
T[207]='Esu Michael Dixont.'
