# -*- coding: utf-8 -*-
"""STEPLEX → SK."""
T={}
T[0]='STEPLEX — Sir Michael Dixont'
T[1]='ISSN 2784-0391'
T[2]='Mimoriadne vydanie • Regeneratívna medicína'
T[3]='The Royal Medical Gazette'
T[4]='Sir Michael Dixont'
T[5]='Bývalý osobný lekár Britskej kráľovskej rodiny'
T[6]='Vol. XLVII • N. 12'
T[7]='Slovenské vydanie'
T[8]='Exkluzívne — prvé uverejnenie'
T[9]='34 rokov som liečil kĺby Kráľovskej rodiny. Dnes po prvýkrát sprístupňujem túto formulu'
T[10]='všetkým'
T[11]='bez rozdielu'
T[12]=('«Buckinghamský palác som opúšťal s istotou v jedinej veci: medicína, ktorú som praktizoval v kráľovskej '
       'rodine, funguje. A milióny ľudí, ktorí by ju potrebovali, o nej nikdy ani nepočuli. To je neprijateľné.»')
T[13]=('Sir Michael Dixont, MD, FRCP. 34 rokov služby u Britskej kráľovskej rodiny. Rytier Radu Britského '
       'impéria. Zakladateľ Dixont Institute of Regenerative Medicine v Cambridgei.')
T[14]='✦ ✦ ✦'
T[15]='Sir Michael Dixont, MD, FRCP'
T[16]='Bývalý hlavný lekár Britského kráľovského dvora'
T[17]=('34 rokov služby u Kráľovskej rodiny. Člen Royal College of Physicians. Rytier Radu Britského impéria. '
       'Zakladateľ Dixont Institute of Regenerative Medicine.')
T[18]=('Som Michael Dixont. Tridsaťštyri rokov som bol osobným lekárom Britskej kráľovskej rodiny. Liečil som '
       'kĺby, chrbtice, kolená — aj ľuďom, ktorých mená dodnes nesmiem vysloviť. Mal som prístup k laboratóriám, '
       'výskumom a účinným látkam, ktoré štátne zdravotníctvo nikdy neuvidí. Nie zo zlomyseľnosti — z '
       'ekonomických dôvodov. To, čo naozaj funguje, je v priemyselnom meradle príliš drahé, a to, čo sa vyrába '
       'priemyselne, lieči príliš málo.')
T[19]='Palác som opustil ako šesťdesiatsedemročný. Nie z únavy — z hanby. Dovoľte mi to vysvetliť.'
T[20]=('Jedno popoludnie posledného roku služby, po vizite na kráľovskom dvore som zašiel do jedného chelseaského pubu. Pri '
       'pulte sedel asi šesťdesiatročný muž s elastickou ortézou na kolene, tvár mal sivú od bolesti a objednával '
       'si pivo, aby ním zapil ďalší ibuprofén. Dal som sa s ním do reči — profesionálna deformácia. Spýtal som '
       'sa, ako dlho trpí. «Jedenásť rokov» — povedal. «Môj lekár hovorí, že sa nedá nič robiť. Beriem lieky '
       'proti bolesti a čakám na operáciu. Čakacia lehota je štrnásť mesiacov.»')
T[21]=('Jedenásť rokov. Štrnásť mesiacov čakania. V ten istý deň som presne taký istý typ kĺbu ošetroval '
       'protokolom, ktorý za šesť týždňov obnoví chrupavku. Lenže ten protokol bol vyhradený tým, čo žijú za '
       'múrmi Paláca. Muž pri pulte — bývalý robotník Fordu v Dagenhame, otec troch detí — sa musel uspokojiť s '
       'ibuprofénom a ortézou.')
T[22]=('V tej chvíli som pochopil veľmi jednoduchú vec: vlastniť liek a nepodeliť sa oň je to isté, ako keby '
       'neexistoval. Tridsaťštyri rokov kráľovskej služby nestojí za nič, ak muž pri pulte zomrie so zničeným '
       'kolenom, kým čaká na operáciu, ktorá možno nikdy nepríde.')
T[23]='— Sir Michael Dixont'
T[24]=('O tri mesiace neskôr som odišiel do dôchodku. Predal som dom v Kensingtone, vzal celoživotné úspory a v '
       'Cambridgei otvoril Dixont Institute of Regenerative Medicine. Prišli so mnou dvaja spoľahliví '
       'spolupracovníci: biochemik dr. James Harlow, s ktorým som pracoval dvadsať rokov, a dr. Priya Nair, '
       'špecialistka na transdermálne formulácie, ktorá so mnou vyvíjala kráľovské protokoly.')
T[25]=('Cieľ bol jediný: vziať protokol, ktorý fungoval v Paláci, a premeniť ho na niečo, čo môže doma použiť '
       'hocikto. Bez injekcií. Bez nemocnice. Bez štrnásťmesačných čakacích lehôt.')
T[26]='Laboratórium Dixont Institute of Regenerative Medicine, Cambridge. Práve tu vyvinuli transdermálnu formulu STEPLEX.'
T[27]='Zľava: dr. James Harlow, Sir Michael Dixont a dr. Priya Nair vo formulačnom laboratóriu.'
T[28]='✦ ✦ ✦'
T[29]='Prečo Slovensko — a prečo teraz'
T[30]='Slovensko bolo našou prvou voľbou. Nie náhodou.'
T[31]=('Na Slovensku je podiel kĺbových ochorení jeden z najvyšších v Európe: viac než 2 milióny ľudí trpí '
       'niektorou formou artrózy — takmer každý piaty Slovák. U ľudí nad 65 rokov tento podiel presahuje 60%.')
T[32]=('Ale to, čo nás naozaj presvedčilo, sú čakacie lehoty. Na ortopedickú ambulanciu sa čaká v priemere 2-3 '
       'mesiace. Na operáciu kolennej alebo bedrovej protézy v štátnej starostlivosti 1-2 roky — v niektorých '
       'krajoch aj viac. Státisíce Slovákov žijú v pasci dnešnej bolesti a operácie, ktorá príde budúci rok — '
       'alebo možno nikdy.')
T[33]=('Keď sme sa rozhodli sprístupniť STEPLEX aj mimo Spojeného kráľovstva, voľba bola okamžitá. Na Slovensku '
       'je potreba najväčšia. Skontaktoval som sa s profesorom Ladislavom Hanzelom, emeritným primárom '
       'ortopedického oddelenia v Bratislave, ktorého som spoznal na kongrese v Edinburghu v roku 2017. Formulu '
       'otestoval na šesťdesiatich pacientoch vo svojej súkromnej ambulancii. Výsledky potvrdili to, čo sme už '
       'vedeli. Povedal mi: «Michael, toto by malo byť v každej slovenskej lekárni.»')
T[34]='2 milióny+'
T[35]='Slovákov žijúcich s kĺbovým ochorením'
T[36]='1-2 roky'
T[37]='Čakanie na operáciu protézy'
T[38]='60 mld. Ft'
T[39]='Ročné výdavky na lieky proti bolesti kĺbov'
T[40]='✦ ✦ ✦'
T[41]='Prečo sa kĺby ničia — a prečo to nikto nevysvetlí'
T[42]=('Pravda, ktorú vám žiaden ortopéd nepovie pri šesťminútovom vyšetrení: kĺb nie je kus železa, ktorý sa '
       'jednoducho opotrebuje. Je to živý organizmus. Chrupavka sa regeneruje — ale len vtedy, keď dostane to, '
       'čo potrebuje.')
T[43]=('V každom kĺbe je chrupavka — vankúš, ktorý bráni tomu, aby sa kosť trela o kosť. Okolo nej kĺbový maz, '
       'ktorý chrupavku maže a vyživuje. Keď tento systém funguje, kĺb sa pohybuje bez bolesti, bez vŕzgania, '
       'bez obmedzení.')
T[44]='Toto sa deje s vekom a opotrebovaním:'
T[45]=('kĺbového mazu ubúda, chrupavka už nedostáva výživu, začína vysychať a praskať. Kosť na kosť. Každý krok '
       'je bolesť. A lieky? Vypnú poplašný signál — bolesť — ale nič neopravia. Naopak: bez bolesti sa kĺb '
       'zaťažuje ešte viac a ničenie sa zrýchľuje.')
T[46]=('V Paláci sme tento problém vyriešili pred dvadsiatimi rokmi. Formulou, ktorá robí tri veci naraz: obnoví '
       'kĺbový maz, dodá chrupavke stavebné prvky potrebné na prestavbu a zastaví chronický zápal, ktorý bráni '
       'hojeniu. Nie jednu z troch — všetky tri spolu. V tom je rozdiel medzi štátnou medicínou a našou prácou.')
T[47]='Ako funguje STEPLEX — kráľovský protokol, teraz vo forme spreja'
T[48]=('Najväčšou výzvou nebola formula — tú sme poznali. Výzvou bola forma. V Paláci sme používali '
       'vnútrokĺbové injekcie: ihla priamo do kĺbu, pod ultrazvukovou kontrolou, na sterilnej klinike. Dokonalé '
       'pre toho, kto má osobného lekára. Nemožné pre toho, kto žije v Košiciach, Prešove alebo Žiline a mesiace '
       'čaká na ortopedické vyšetrenie.')
T[49]=('Dr. Nairovej trvalo štrnásť mesiacov, kým problém vyriešila. Vyvinula transdermálny penetračný systém '
       'založený na nanoštruktúrovaných lipozómoch: lipidové mikroguľôčky, ktoré prenikajú cez kožnú bariéru a '
       'účinné látky dopravia priamo do kĺbového puzdra — presne tam, kam sa dostala ihla. Bez ihly. Bez '
       'kliniky. Bez bolesti.')
T[50]='1'
T[51]='Prienik'
T[52]='Nanoštruktúrované lipozómy prenikajú cez kožu a do 12 minút od aplikácie dosiahnu kĺbové puzdro.'
T[53]='2'
T[54]='Mazanie'
T[55]='Kyselina hyalurónová s vysokou molekulovou hmotnosťou obnoví kĺbový maz a odstráni trenie kosti o kosť.'
T[56]='3'
T[57]='Prestavba'
T[58]='Chondroitín, glukozamín a kolagén typu II poskytujú stavebné prvky na regeneráciu chrupavky.'
T[59]='4'
T[60]='Ochrana'
T[61]='Boswellia serrata a kurkumín blokujú chronický zápal, ktorý bráni prirodzenému hojeniu.'
T[62]='Výsledkom je'
T[63]='STEPLEX'
T[64]=('— sprej, ktorý sa nastrekuje na kožu nad postihnutým kĺbom, dvakrát denne, ráno a večer. Nemastí, '
       'vstrebe sa za dve minúty, nemá liekový zápach. A robí presne to, čo v Paláci robila injekcia — ale bez '
       'ihly.')
T[65]='STEPLEX — transdermálna formula Dixont Institute. Každé balenie obsahuje 30-dňovú kúru.'
T[66]='✦ ✦ ✦'
T[67]='Čo sa stane, ak budete ignorovať bolesť kĺbov'
T[68]=('Mnohí si myslia, že bolesť kolena, bedra či ramena «patrí k veku» a treba s ňou žiť. Klinická pravda je '
       'iná: bolesť kĺbu je poplašný signál. Ignorovať ho nie je hrdinstvo — je to tiché sebazničenie.')
T[69]='I. fáza → IV. fáza: ničenie je nezvratné'
T[70]=('V kĺbovej chrupavke nie sú cievy. To znamená, že sa nedokáže regenerovať ako koža alebo svaly. Každý '
       'deň, ktorý prejde bez výživy, chrupavka stráca hrúbku. A táto strata sa sama nevráti.')
T[71]='I. fáza'
T[72]='— Občasná bolesť, ranná stuhnutosť. Chrupavka sa stenčí o 10-15%. Ešte zvratné.'
T[73]='II. fáza'
T[74]='— Denná bolesť, vŕzganie, ťažkosti na schodoch. Strata 30-40%. Čiastočne zvratné.'
T[75]='III. fáza'
T[76]='— Trvalá bolesť, viditeľná deformácia, krívanie. Strata 60-70%. Pomôcť môže už len operácia alebo intenzívny regeneratívny protokol.'
T[77]='IV. fáza'
T[78]=('— Kosť na kosť. Chrupavka neostala. Jedinou možnosťou je umelá protéza — operácia za 3,5 milióna '
       'forintov so šesťmesačnou rehabilitáciou a žiadnou zárukou, že bolesť úplne zmizne.')
T[79]='Lieky proti bolesti neliečia. Zrýchľujú ničenie.'
T[80]=('Ibuprofén, diklofenak, naproxén — lieky, ktoré denne berú státisíce Slovákov — chrupavku neobnovujú. '
       'Nespomaľujú jej ničenie. Zakrývajú ho. A medzitým:')
T[81]='Poškodenie žalúdka:'
T[82]='dlhodobé užívanie NSAID spôsobí u 15-25% chronických pacientov žalúdočný vred.'
T[83]='Poškodenie obličiek:'
T[84]='po 5 rokoch denného užívania sa riziko chronického zlyhania obličiek zvyšuje o 58%.'
T[85]='Poškodenie srdca a ciev:'
T[86]='diklofenak zvyšuje riziko infarktu o 40% oproti tým, ktorí ho neužívajú.'
T[87]='Zrýchlenie artrózy:'
T[88]=('bez signálu bolesti pacient zaťažuje poškodený kĺb. Chrupavka sa opotrebuje rýchlejšie. Kým liek '
       'prestane účinkovať, stav je o roky horší.')
T[89]='Vľavo: zdravý kĺb s neporušenou chrupavkou. Vpravo: artróza III. stupňa — chrupavka je takmer úplne zničená.'
T[90]=('Operácia totálnej kolennej protézy. Priemerná cena v súkromnom sektore: 3,5 milióna Ft. Rehabilitácia: 6 '
       'mesiacov. Čakacia lehota v štátnej starostlivosti: až 2 roky.')
T[91]='Nečakajte na IV. fázu — objednajte si STEPLEX teraz'
T[92]='✦ ✦ ✦'
T[93]='Zloženie — čo obsahuje každá jedna aplikácia'
T[94]='Formula STEPLEX — Protokol Dixont'
T[95]='✓'
T[96]='Kyselina hyalurónová s vysokou molekulovou hmotnosťou'
T[97]='— 45 mg/aplikáciu'
T[98]='Obnovuje objem a viskozitu kĺbového mazu. Odstraňuje trenie v kĺbe.'
T[99]='✓'
T[100]='Chondroitín sulfát'
T[101]='— 60 mg/aplikáciu'
T[102]='Stimuluje chrupavkové bunky k tvorbe novej chrupavkovej matrice. Spomaľuje enzymatický rozklad.'
T[103]='✓'
T[104]='Glukozamín sulfát'
T[105]='— 55 mg/aplikáciu'
T[106]='Prekurzor glykozaminoglykánov — stavebný materiál chrupavky.'
T[107]='✓'
T[108]='Hydrolyzovaný kolagén typu II'
T[109]='— 40 mg/aplikáciu'
T[110]='Poskytuje vláknitú štruktúru, na ktorej sa poškodená chrupavka prestavuje.'
T[111]='✓'
T[112]='Extrakt z Boswellia serrata'
T[113]='— 30 mg/aplikáciu'
T[114]='Prirodzený inhibítor 5-lipoxygenázy. Blokuje chronický zápal bez žalúdočných ťažkostí.'
T[115]='✓'
T[116]='Kurkumín vo fosfolipidovom komplexe'
T[117]='— 25 mg/aplikáciu'
T[118]='Protizápalový a antioxidačný. Fosfolipidový komplex zvyšuje biologickú dostupnosť 29-násobne.'
T[119]='✓'
T[120]='Nanoštruktúrovaný lipozómový komplex'
T[121]='— transportný systém'
T[122]='Prenáša všetky účinné látky cez kožnú bariéru priamo do kĺbového puzdra.'
T[123]='✦ ✦ ✦'
T[124]='Výsledky — observačná štúdia na 1 847 pacientoch'
T[125]=('Skôr než sme STEPLEX sprístupnili verejnosti, uskutočnili sme v Dixont Institute dvanásťmesačnú '
        'observačnú štúdiu v spolupráci s tromi britskými ortopedickými klinikami. 1 847 pacientov, priemerný '
        'vek 62 rokov, všetci s diagnózou osteoartrózy II.-III. stupňa.')
T[126]='Parameter'
T[127]='Pred liečbou'
T[128]='Po 8 týždňoch'
T[129]='Zmena'
T[130]='Bolesť kĺbov (škála VAS)'
T[131]='7,4 / 10'
T[132]='2,1 / 10'
T[133]='−71,6%'
T[134]='Pohyblivosť kĺbov'
T[135]='41% normy'
T[136]='84% normy'
T[137]='+104,9%'
T[138]='Hrúbka chrupavky (ultrazvuk)'
T[139]='1,2 mm'
T[140]='2,1 mm'
T[141]='+75%'
T[142]='Užívanie liekov proti bolesti'
T[143]='denne (89%)'
T[144]='príležitostne (12%)'
T[145]='−86,5%'
T[146]='Podiel pacientov, ktorí sa vyhli operácii'
T[147]='—'
T[148]='78,3%'
T[149]=('Účastníci observačnej štúdie Dixont Institute. Priemerný vek: 62 rokov. Trvanie: 12 mesiacov. 1 847 '
        'pacientov s osteoartrózou II.-III. stupňa.')
T[150]='Poznámka výskumníka:'
T[151]=('78,3% pacientov, ktorí pôvodne čakali na totálnu kolennú alebo bedrovú protézu, sa po dvoch kúrach '
        'STEPLEX operácii vyhlo. Kompletný súbor údajov je dostupný v registri Dixont Institute (ref. '
        'DI-2024-ART-1847).')
T[152]='Vyskúšajte STEPLEX — platba až pri prevzatí'
T[153]='✦ ✦ ✦'
T[154]='Prečo vám o tom váš lekár nepovie'
T[155]='Často sa ma na to pýtajú. Odpoveď je jednoduchá a nemá nič spoločné so sprisahaním ani so zlým úmyslom.'
T[156]=('Obvodný lekár má na pacienta sedem minút. Za sedem minút môže urobiť jedinú vec: predpísať to, čo pozná. '
        'Pozná lieky proti bolesti, pozná kortizónové injekcie, pozná čakaciu lehotu na protézu. Jeho príručka '
        'tam končí. Nie preto, že by bol neschopný — ale preto, že systém je takto nastavený. Systém, ktorý '
        'zarába na denných liekoch a miliónových protézach, nemá žiaden ekonomický záujem dať vedieť, že '
        'existuje alternatíva, ktorú si možno doma aplikovať za dve minúty.')
T[157]='Údaj, ktorý vás môže prinútiť zamyslieť sa:'
T[158]=('Na Slovensku má trh s liekmi proti bolesti kĺbov hodnotu 60 miliárd forintov ročne. Trh s kĺbovými '
        'protézami 40 miliárd. Spolu je to 100 miliárd. Žiadne 100-miliardové odvetvie sa dobrovoľne nezruší. '
        'Nie je to sprisahanie — je to ekonómia.')
T[159]=('Ja už nemám čo stratiť. Nepredávam lieky. Nemám podiely v ortopedických klinikách. Mám britský dôchodok '
        'a svedomie, ktoré mi nedá spať, kým viem, že muž pri pulte v pube — a milióny jemu podobných — čakajú '
        'na operáciu, ktorú by sprej mohol urobiť zbytočnou.')
T[160]='✦ ✦ ✦'
T[161]='Ako sa STEPLEX používa'
T[162]=('Dva-tri streky nastriekajte na postihnuté miesto zo vzdialenosti 10-15 cm — koleno, bedro, rameno, '
        'ruka, členok, chrbtica — dvakrát denne: ráno a večer, na čistú a suchú pokožku. Niekoľkými krúživými '
        'pohybmi sa dá rozotrieť. Sprej sa úplne vstrebe za dve minúty. Nezanecháva škvrny, nemastí, nemá '
        'liekový zápach.')
T[163]=('Prvá kúra trvá 30 dní. Väčšina pacientov cíti výrazné zmiernenie bolesti už v prvom týždni. Na '
        'štrukturálnu obnovu chrupavky je potrebných 6-8 týždňov nepretržitého používania. V pokročilejších '
        'prípadoch (artróza III. stupňa) odporúčame dve kúry za sebou.')
T[164]='✦ ✦ ✦'
T[165]='Osobná prosba'
T[166]=('Mám sedemdesiatjeden rokov. Nemám veľa času a peniaze nepotrebujem. Potrebujem vedieť, že formula, '
        'ktorá tridsaťštyri rokov fungovala za múrmi Paláca, sa konečne dostane k tým, ktorí ju naozaj '
        'potrebujú.')
T[167]=('Ak máte po štyridsiatich piatich a ráno vstávate «po kúskoch». Ak sa schody stali nepriateľom. Ak '
        'kolenom cítite počasie skôr ako meteorológovia. Ak sa vám na nočnom stolíku radia škatuľky liekov '
        'proti bolesti a aj tak to nie je lepšie. Ak vám povedali: «čo chcete, to je vek» — neverte tomu. Vek '
        'je príčina, nie rozsudok.')
T[168]=('Pod týmto textom nájdete formulár. Uveďte svoje meno a telefónne číslo. Poradca vám zavolá, položí '
        'niekoľko otázok o vašom stave, vyberie najvhodnejšiu kúru a dá vám ju doručiť kuriérom domov. Platíte '
        'až pri prevzatí — žiadnu zálohu nepýtame. Na tejto podmienke som osobne trval: kto trpí, nech '
        'neriskuje ani jeden forint skôr, než má výrobok v rukách.')
T[169]=('A ak toto nečítate pre seba, ale myslíte na svoju mamu, otca, na osamelého starého rodiča, ktorý pri '
        'každom telefonáte hovorí: «som v poriadku, neboj sa» — nečakajte. Do poslednej chvíle budú hovoriť '
        '«som v poriadku», lebo nechcú byť na ťarchu. Nedovoľte, aby sa váš blízky potichu stal väzňom '
        'vlastného domova.')
T[170]='Oficiálny objednávkový formulár'
T[171]='Č.'
T[172]='19'
T[173]='974'
T[174]='/ 20'
T[175]='000'
T[176]='Ak chcete využiť 50% zľavu, uveďte svoje meno a telefónne číslo do polí nižšie a stlačte tlačidlo «OBJEDNÁVAM».'
T[177]='Na sklade:'
T[178]='33'
T[179]='/ 1000'
T[180]='19800\n            HUF'
T[181]='9900\n            HUF'
T[182]='Meno'
T[183]='Telefónne číslo'
T[184]='OBJEDNÁVAM TERAZ'
T[185]='✔️ Doručenie zabezpečuje Národné zdravotné centrum priamo na uvedenú adresu. Dodanie do 2-3 pracovných dní kuriérom.'
T[186]='Komentáre čitateľov'
T[187]='Belo K., Košice'
T[188]=('Mám 63 rokov, osem rokov som bral lieky proti bolesti na pravé koleno. Ortopéd ma zapísal na čakaciu '
        'listinu na protézu — predpokladaný čas: 11 mesiacov. Zo zvedavosti som vyskúšal STEPLEX, veľmi som '
        'tomu neveril. Po troch týždňoch som vstal zo stoličky bez toho, aby som sa chytal stola. Po šiestich '
        'týždňoch som zišiel do pivnice — prvýkrát po dvoch rokoch. Zavolal som do nemocnice a povedal, že '
        'protézu zatiaľ nechcem.')
T[189]='Alžbeta N., Nitra'
T[190]=('Ráno a večer si strekám na ruky. Štyridsať rokov šijem, prsty mi stuhli ako paličky — už som nedokázala '
        'navliecť niť do ihly. Po mesiaci som začala znova šiť. Zákazníčky si mysleli, že ma operovali. Nie, '
        'prosím. Sprej, dvakrát denne, a to je celé.')
T[191]='Štefan F., Žilina'
T[192]=('Objednala mi ho manželka, lebo ja som tomu neveril. «Zase nejaký podvod» — hovoril som. Po dvoch '
        'týždňoch som prestal s ibuprofénom. Po mesiaci chodím po schodoch znova bez držania. Manželka '
        'nehovorí «ja som ti to vravela» — len si to myslí, a ja som jej vďačný.')
T[193]='Andrea V., Bratislava'
T[194]=('Kúpila som ho mame, má 78 rokov, artrózu bedra. Dva roky nezišla po schodoch v paneláku — my, deti, sme '
        'jej nosili nákup hore. Po šiestich týždňoch so STEPLEX zišla sama do kaviarne pod domom. Čašník na ňu '
        'pozeral, akoby videl ducha. Dala si kávu, zjedla kakaový závin a s plačom mi zavolala. Od radosti. '
        'Ešte v ten večer som objednala druhú kúru.')
T[195]='Jozef L., Prešov'
T[196]=('Mám šesťdesiatdeväť rokov, bývalý murár, pravé rameno mi odišlo. Chirurg chcel operovať, ja som '
        'nechcel narkózu — v šesťdesiatich deviatich sa jej bojím. Kamarát mi poslal tento článok. Dva mesiace '
        'spreja. Na poslednej kontrole chirurg pozeral na ultrazvuk, potom na mňa, potom zase na ultrazvuk. '
        '«Čo ste robili?» — spýtal sa. «Sprej» — povedal som. Nekomentoval to. Ale operáciu z kalendára '
        'vyškrtol.')
T[197]='🏫'
T[198]='Vyvinuté v Cambridgei (UK)'
T[199]='💬'
T[200]='Bezplatné poradenstvo'
T[201]='🚚'
T[202]='Kuriér za 2-3 dni'
T[203]='💰'
T[204]='Platba pri prevzatí'
T[205]=('© Dixont Institute of Regenerative Medicine, Cambridge, UK. Všetky práva vyhradené. Informácie na tejto '
        'stránke majú informatívny charakter a nenahrádzajú lekársku konzultáciu.')
T[206]='{_box:2sHZz2rc}'
T[207]='Som Michael Dixont.'
