# -*- coding: utf-8 -*-
"""SK. Hrdina: dedko Ondrej Kuchár, Poľana, Detva. Produkt: Trauflix, KAPSULY."""
T = {}
T[0] = '﻿'
T[1] = ('„Kto neverí v silu prírody, nikdy neporozumie vlastnému telu" — dedko Ondrej Kuchár spod Poľany, ktorý vyše '
        '1700 ľuďom vrátil radosť z chôdze bez jedinej predpísanej chemickej tabletky')
T[2] = 'Špeciálna reportáž · Zdravie a dobrý pocit'
T[3] = '+'
T[4] = 'ZdravieInfo Slovensko'
T[5] = 'Reportáže o verejnom zdraví'
T[6] = '„Kto neverí v'
T[7] = 'silu prírody'
T[8] = ', nikdy neporozumie'
T[9] = 'vlastnému telu'
T[10] = '."'
T[11] = 'Dedko Ondrej Kuchár, ľudový bylinkár spod Poľany, vrátil'
T[12] = 'vyše 1700 ľuďom'
T[13] = 'radosť z chôdze'
T[14] = 'bez jedinej predpísanej chemickej tabletky'
T[15] = '. Náš novinár sa vybral na jeho odľahlú usadlosť, aby položil najdôležitejšiu otázku: ako sa mu to darí?'
T[16] = 'Zverejnené:'
T[17] = ', 09:36'
T[18] = ('V lesoch pod Poľanou žije 72-ročný muž, ktorého v okolitých dedinách volajú jednoducho „dedko Ondrej". Nikdy '
         'nebol lekárom. Nikdy neštudoval. Ale za posledné tri roky zachránil vyše 1700 ľudí pred bolesťou kĺbov — '
         'ľudí, ktorých aj tí najlepší špecialisti už odpísali. Ľudí odsúdených na invalidný vozík. Ľudí, ktorí sa '
         'nevedeli postaviť z vlastnej postele. A to všetko vďaka obyčajným kapsulám, vyrobeným vlastnými rukami — '
         'podľa dávnej múdrosti prírody.')
T[19] = ('V utorok ráno sme dorazili do Detvy, do zalesnených dolín pod Poľanou. Hmla ešte visela medzi vrcholcami '
         'stromov. Posledné kilometre sme šli pešo, lebo ďalej už asfaltová cesta nevedie. „Hľadáte dedka Ondreja?" — '
         'spýtala sa staršia žena na konci dediny, so šatkou na hlave. „Zabočte doľava pri malej kamennej studni. Jeho '
         'dom je pri prameni. Ale poponáhľajte sa, lebo na poludnie ide do hory zbierať byliny."')
T[20] = ('Tak sme našli Ondreja Kuchára — 72-ročného ľudového bylinkára, ktorý celý život prežil pod Poľanou a dnes '
         'búra jedno z najväčších tabu v krajine: že na bolesť kĺbov existuje skutočné riešenie. Riešenie, ktoré '
         'nezávisí od chemických tabletiek, injekcií ani operácií. Ale od stretnutia prírody, dávnej múdrosti a pamäti '
         'stáročí.')
T[21] = ('V najbližších obciach — v Detve, Zvolene, Hriňovej a inde — dedka Ondreja pozná takmer každá rodina. Dcéry '
         'privážajú svojich krívajúcich otcov, aby ich pozrel. Manželky objednávajú balenia kapsúl pre svoje matky v '
         'domovoch dôchodcov. Muži prichádzajú po dlhých dňoch práce, aby mohli znova chodiť. Lekár z okresnej '
         'polikliniky priznáva:')
T[22] = '„Neviem vysvetliť, čo sa deje s tým človekom. Ale moji pacienti sa naozaj zotavujú."'
T[23] = ('„Devätnásť rokov som žila s bolesťou. Predpísali mi dvanásť rôznych liekov — a ani jeden mi nepomohol. Jedného '
         'dňa mi sestra povedala o dedkovi Ondrejovi. Tri hodiny som k nemu šla pešo, lebo som neverila. Teraz tie '
         'kapsuly beriem už štyri týždne. Včera som si sama zišla do pivnice po zaváraniny. Prvýkrát po devätnástich '
         'rokoch."')
T[24] = '— Helena, 78 rokov, Detva'
T[25] = ('„Syn pracuje v Nemecku. Jeho žena so mnou nechcela bývať pre moje bolesti chrbta. Zostal som sám na konci '
         'dediny, v dome, ktorý sotva vykúrim. Ani pes so mnou nechodil, lebo som mu nestačil. Vtedy za mnou dedko '
         'Ondrej prišiel sám. Na kolenách som mu ďakoval. Dnes si sám chodím po vodu k prameňu."')
T[26] = '— Vladimír, 71 rokov, Zvolen'
T[27] = ('Dedko Ondrej s jednou zo svojich pacientok, tetou Žofiou z Detvy. „Týchto ľudí nikto nenavštevuje. Deti '
         'odišli, lekári ich odpísali. Ale príroda ich neodpísala. Treba len počúvať, čo šepká."')
T[28] = '„Telo vie všetko. Treba len stíšiť hluk, aby si počul, čo šepká."'
T[29] = ('Rozhovor s dedkom Ondrejom v srdci Poľany — v jeho dome, kde zo stien visia zväzky sušených bylín a na '
         'policiach spočívajú storočné knihy')
T[30] = 'Dedko Ondrej Kuchár:'
T[31] = ('„Všetko si pamätám, akoby to bolo včera. Skoro na úsvite, hmla ešte visela medzi vrcholcami. Sedel som pred '
         'svojou chalupou pri ohni a pripravoval výťažok z ihličnanov — vtedy ešte na vlastné bolesti. Zrazu som počul '
         'tiché kroky. Objavila sa žena v tmavých šatách po zem, asi šesťdesiatročná. Oči mala ako stojatú vodu — plné '
         'strachu. Sadla si vedľa mňa na zoťatý kmeň a povedala:')
T[32] = ('„Dedko Ondrej, prosím ťa, zachráň mi manžela. Môj muž umiera. Kĺby mu čoraz viac tuhnú, kolená sú zničené. '
         'Lekári už nevedia nič urobiť. Nevie chodiť, nevie sa postaviť, nevie ani sedieť. Len leží a plače."')
T[33] = ('V TEJ CHVÍLI SOM POCHOPIL: MÚDROSŤ O BYLINÁCH, KTORÚ SOM ZDEDIL PO SVOJOM UČITEĽOVI, NEBOLA DANÁ LEN MNE — ALE '
         'AJ TEJ ŽENE A JEJ MUŽOVI. VTEDY SOM SA ROZHODOL NIESŤ JU ĎALEJ."')
T[34] = ('Dedko Ondrej Kuchár, 72-ročný ľudový liečiteľ spod Poľany. Býva v malom kamennom dome, ktorý si v '
         'sedemdesiatych rokoch sám postavil, hlboko v horách. Nemá vysokoškolský diplom — ale mal učiteľa, od ktorého '
         'sa v mladosti naučil liečivé poznanie o bylinách, a vyše päťdesiat rokov skúseností, aké nemá nikto iný.')
T[35] = ('Dedko Ondrej hovorí pomaly, občas s dlhými pauzami — akoby každé slovo zvlášť vážil. Jeho veľké kostnaté ruky '
         'spočívajú na kolenách. Prsty má zafarbené od živíc a koreňov, s ktorými pracuje už šesťdesiatpäť rokov. Za '
         'ním na stene visia sušené zväzky šalvie a rasce. Na policiach stoja poháre, malé tmavé nádobky a ťažká, do '
         'kože viazaná kniha — taliansky preklad „De Materia Medica" zo šestnásteho storočia, ktorý zdedil po svojom '
         'učiteľovi.')
T[36] = ('„Ľudia si myslia, že bolesti kĺbov sú prirodzenou súčasťou staroby. To je lož. Kolená, chrbát, bedrá — to je '
         'ako les. Ak ho dobre chrániš, žije stáročia. Ak ho vyčerpávaš a otravuješ, za šesť či osem rokov sa rozpadne. '
         'Súčasná medicína kĺby nechráni. Len uspáva bolesť. A každý rok predpíše viac tabletiek. Až kým človek nespadne '
         'a nezlomí si kosť."')
T[37] = ('„Štyridsať rokov som robila na gazdovstve. Vstávala som o štvrtej ráno, líhala o ôsmej večer. Nikdy som sa '
         'nesťažovala. Keď mi vypovedalo bedro, lekár mi povedal: »Pani Mária, to sú roky. Musíte si zvyknúť.« Ako si '
         'mám zvyknúť? Sotva šesťdesiatpäť rokov mám! Muža niet. Deti sú v Nemecku. Som sama a nevládzem do záhrady po '
         'paradajky. Vtedy mi poštár povedal o dedkovi Ondrejovi."')
T[38] = '— Mária, 65 rokov, Hriňová'
T[39] = '„Lekárne nehovoria pravdu — lebo keby ju povedali, skrachovali by"'
T[40] = 'Dedko Ondrej Kuchár vysvetľuje, prečo tradičné lieky na kĺby škodia viac, než pomáhajú'
T[41] = 'Dedko Ondrej Kuchár:'
T[42] = ('— Poviem vám, čo vidím mesiac čo mesiac u tých, ktorí ku mne prichádzajú. Žena, šesťdesiatpäť rokov. Už desať '
         'rokov berie protizápalové lieky. Bolesť kolena sa každý rok zhoršuje. Teraz ju bolí aj žalúdok od toľkých '
         'tabletiek. Výsledky obličiek sú zlé. Lekár predpíše ďalšiu tabletku — teraz na žalúdok. Potom na obličky. A '
         'koleno sa medzitým rozpadá. Chrupavku nikto neobnovuje. Len sa uspáva bolesť — až kým sa chrupavka celkom '
         'neopotrebuje.')
T[43] = ('Je to začarovaný kruh: bolesť → tabletka → bolesť sa vráti silnejšia → silnejšia tabletka → žalúdok trpí → '
         'ďalšia tabletka na žalúdok → oblička vypovie → a kĺb sa medzitým rozpadá.')
T[44] = 'Nikto nehovorí pravdu: existuje iná cesta — dať chrupavke to, čo potrebuje, a nechať ju, nech sa sama obnoví.'
T[45] = ('Kolená tety Jany, 74 rokov, zo Zvolena. Artróza tretieho stupňa — chrupavka je takmer úplne opotrebovaná. Už '
         'päť mesiacov nevychádza z domu. Na nočnom stolíku — šesť druhov tabletiek, ktoré nezmenili nič. Všetky jej '
         'doniesol syn z rôznych lekární v nádeji, že niektorá pomôže. Ani jedna neúčinkuje.')
T[46] = 'Bolesť kolena, chrbta alebo bedra po štyridsiatom piatom roku'
T[47] = 'nie je „normálna na vek"'
T[48] = ('— je to znak, že kĺbová chrupavka sa opotrebúva a že mizne kĺbový maz. Kto tento znak potláča tabletkami, '
         'pomaly a potichu ničí vlastné kĺby.')
T[49] = ('Vľavo: zdravý kĺb so zachovanou chrupavkou a dostatkom kĺbového mazu. Vpravo: zničený kĺb — opotrebovaná '
         'chrupavka, chronický zápal, kosť na kosti. To je realita mnohých ľudí nad šesťdesiat rokov na dedinách. '
         'Protizápalové lieky chrupavku neobnovujú — len tlmia bolesť, kým sa všetko ďalej rozpadá.')
T[50] = ('Protizápalové lieky len blokujú signál bolesti, kým ničenie potichu postupuje. Bez skutočnej regenerácie '
         'chrupavky sa kĺb nakoniec celkom rozpadne — a vtedy zostávajú len dve možnosti: invalidný vozík alebo '
         'operácia s implantáciou endoprotézy, ktorá stojí celý majetok. Ani jedna nevracia skutočný život.')
T[51] = 'Dedko Ondrej Kuchár:'
T[52] = ('— Pochopte vážnosť toho. U mnohých, ktorí ku mne prichádzajú, je chrupavka v kolene, v chrbtici alebo v bedre '
         'zničená na sedemdesiat až deväťdesiat percent. Chodia kosť na kosti — ak vôbec ešte vládzu chodiť. Každý krok '
         'je mučenie.')
T[53] = 'TRADIČNÉ TABLETKY NEDOKÁŽU OBNOVIŤ CHRUPAVKU — LEN ZAKRÝVAJÚ BOLESŤ, KÝM SA VŠETKO ROZPADÁ!'
T[54] = ('A viete, čo ma najviac bolí na hrudi? To, že tí ľudia sú sami. Deti odišli do Nemecka, do Rakúska, do Česka, '
         'do Anglicka. Lekáreň im lieky donesie raz za týždeň. Lekár ich vidí raz za rok. A medzitým sa potichu '
         'rozpadajú. Chrbát, kolená, bedrá. Časom sa boja aj vyjsť z domu, aby nespadli. Preto robím to, čo robím.')
T[55] = ('„Štyridsaťdva rokov som robila na gazdovstve. Dojila som kravy, zbierala zemiaky, nosila drevo. Nikdy som sa '
         'nesťažovala. Potom jedného rána po šesťdesiatke som sa nevedela postaviť z postele. Koleno bolo ako kameň. '
         'Dcéra pracuje v Nemecku. Cez telefón mi povedala, aby som šla do Bratislavy k špecialistovi. Ako mám ísť? Ani '
         'po schodoch nezídem. Dedko Ondrej prišiel za mnou, pol dňa šiel pešo. Za dva týždne som už robila v záhrade."')
T[56] = '— Katarína, 72 rokov, spod Detvy'
T[57] = ('„Tridsať rokov som pracoval v kameňolome pri Detve. Chrbát ma bolel už od štyridsiatky. V sedemdesiatich som '
         'nevedel ani rovno stáť. Diskopatia, ischias — lekári vymýšľali názvy a bolesť neprestávala. Syn stavia v '
         'Nemecku. Posiela peniaze, ale nemá čas ma navštíviť. S kapsulami dedka Ondreja som po štyroch týždňoch znova '
         'vyliezol na strechu opraviť ju — prvýkrát po šiestich rokoch."')
T[58] = '— Rastislav, 70 rokov, robotník z kameňolomu na dôchodku'
T[59] = 'Príbehy, na ktoré nikdy nezabudnem — a príbehy, ktoré zmenia to, ako sa pozeráte na silu prírody'
T[60] = 'Dedko Ondrej Kuchár:'
T[61] = ('— Poviem vám, koho vídam každý týždeň. Nehovorím o štatistikách. O ľuďoch. O ľuďoch s menami, ktorí majú '
         'rodinu, ktorí majú svoje príbehy. O ľuďoch, ktorých medicína už odpísala — a príroda ich ešte neodpísala.')
T[62] = ('Teta Genovéva, 77 rokov, z Detvy. Reumatoidná artritída v oboch rukách — nevedela udržať ani lyžicu. Muž jej '
         'zomrel pred dvoma rokmi. Dcéra pracuje v Nemecku. „V lekárni mi dali 12 rôznych liekov. Všetky mi škodili na '
         'žalúdok a kĺb bolel rovnako. Dedko Ondrej prišiel za mnou, keď mu poštár povedal, že už nevládzem ani zemiak '
         'ošúpať."')
T[63] = ('„Ráno som pozerala na svoje ruky a nespoznávala som ich — boli opuchnuté, pokrivené, akoby neboli moje. '
         'Nevedela som sa ani učesať, ani paradajku nakrájať. S kapsulami dedka Ondreja som po dvoch týždňoch už '
         'háčkovala. Včera som dokončila svoju prvú dečku — prvýkrát po celom roku. Pozerám na ňu a plačem."')
T[64] = '— Teta Genovéva, 77 rokov'
T[65] = ('Dedko Jozef, 75 rokov, zo Zvolena. Diskopatia L4-L5, obojstranná koxartróza. Už osem mesiacov nevstával. '
         '„Povedali, že som prestarý na operáciu. Že sa s tým musím zmieriť. Že nemám nádej. Dedko Ondrej si jednoducho '
         'sadol ku mne, chytil ma za koleno a povedal: »Jozef, o dva týždne ideme spolu do záhrady.« A tak bolo."')
T[66] = ('„Štyridsaťpäť rokov som bol traktoristom na gazdovstve. Preoral som pol okresu. A potom jedného rána som '
         'nevedel ani hlavu zdvihnúť z vankúša. Dve moje deti pracujú v Rakúsku. Posielajú mi peniaze a volajú na '
         'sviatky. Ale kto mi podá vodu, ak sa v noci zadusím od kašľa? S kapsulami dedka Ondreja som po štyroch '
         'týždňoch znova štiepal drevo. Nie veľa — ale dosť na to, aby som sa vlastnými silami zohrial."')
T[67] = '— Dedko Jozef, 75 rokov'
T[68] = 'Toto sú príznaky, ktoré vídam najčastejšie — a ktoré milióny ľudí neberú vážne, mysliac si, že sú to „len roky":'
T[69] = 'Ostrá bolesť kolena pri chôdzi hore alebo dole schodmi — alebo pri každom pohybe;'
T[70] = 'Ranná stuhnutosť — telo je „drevené", nepohne sa 30–60 minút po zobudení;'
T[71] = 'Chronická bolesť chrbta — neviem sa zohnúť, neviem vstať z postele;'
T[72] = 'Opuchy v kolenách, členkoch alebo prstoch;'
T[73] = 'Vŕzganie a praskanie v kĺboch pri každom pohybe;'
T[74] = 'Bolesť bedra, ktorá sa šíri do stehna — neprejdem viac ako 50 metrov;'
T[75] = 'Zdeformované, hrčovité prsty — neviem uchopiť predmety;'
T[76] = 'Mravčenie v nohách alebo rukách — znak diskopatie či utlačeného nervu;'
T[77] = 'Pocit „noža" v krížoch pri narovnávaní chrbta;'
T[78] = 'Zhrbený chrbát, pokrivené držanie tela — postupujúca kyfóza;'
T[79] = 'Nočná bolesť, ktorá nedá spať — budím sa 4–5 razy za noc;'
T[80] = ('Každý z týchto príznakov je poplach. A po štyridsiatom piatom či päťdesiatom roku vedie ich ignorovanie k '
         'jedinému koncu:')
T[81] = ('ÚPLNÁ NEPOHYBLIVOSŤ, INVALIDNÝ VOZÍK, ÚPLNÁ ZÁVISLOSŤ OD INÝCH — A V MNOHÝCH PRÍPADOCH UMIESTNENIE V DOMOVE '
         'DÔCHODCOV, KAM DETI PRÍDU RAZ ZA ROK.')
T[82] = ('Každý deň strávený s neliečenými kĺbmi vás približuje k trvalej nepohyblivosti! Tisíce slovenských dôchodcov '
         'skončili v domovoch dôchodcov práve preto, že bolesť nebrali vážne — alebo brali len tabletky, ktoré problém '
         'nevyriešili. Konajte hneď — pre seba alebo pre svojich najbližších — kým nie je neskoro!')
T[83] = '„Môj učiteľ ma naučil: na každú bolesť má príroda odpoveď — ak vieš, kde hľadať"'
T[84] = 'Ako dedko Ondrej Kuchár našiel formulu, ktorú dnes používa vyše 1700 ľudí z dedín pod Poľanou'
T[85] = 'Dedko Ondrej Kuchár:'
T[86] = ('— Na druhý deň som sa šiel pozrieť na manžela tej ženy. Dom bol v pološere. Človek vyzeral ako vysušená huba '
         '— suchý, žltkastý. Telo bolo ešte teplé a pohľad sa už lúčil so svetom. Sadol som si k nemu, chytil ho za '
         'ruku a spýtal sa: „Koľko rokov už žiješ s tou bolesťou, brat?" Mlčal. Slza mu stiekla po líci. „Devätnásť '
         'rokov," zašepkal. „A nikto nevie, ako mi pomôcť. Všetci len predpisujú lieky."')
T[87] = ('Vtedy som si spomenul na starý zápis. Pred mnohými rokmi som v pozostalosti svojho učiteľa našiel zabudnutý '
         'zošit — taliansky herbár zo šestnásteho storočia, preklad „De Materia Medica" veľkého Dioskorida. Na jednej '
         'strane bolo napísané:')
T[88] = ('„Vnútorný oheň tela kradne kĺbom ich vlahu a pružnosť. Len ten, kto pozná slzu stromu — živicu, ktorá '
         'uchováva pamäť ľudského tkaniva — im môže vrátiť život do kostí."')
T[89] = ('Herbár, ktorý dedko Ondrej zdedil po svojom učiteľovi. „Táto kniha strážila múdrosť dvesto rokov, kým som ju '
         'nenašiel. Všetky byliny, ktoré idú do Trauflixu, sú na týchto stranách."')
T[90] = ('Samozrejme, nebolo to vedecké vysvetlenie — ale múdrosť odovzdávaná z pokolenia na pokolenie. Ale vtedy som '
         'ešte nevedel, že ten deň bude začiatkom troch rokov práce. Troch rokov, v ktorých som dedičstvo svojich '
         'učiteľov a dary lesa spojil do obyčajných kapsúl, vyrobených ručne — ktoré dokážu obnoviť chrupavku zvnútra, '
         'bez chemických tabletiek.')

# ---------- 91–180 ----------
T[91] = 'Čo obsahujú kapsuly, ktoré vyrába dedko Ondrej:'
T[92] = 'Živica ihličnanov spod Poľany — slza stromu'
T[93] = ('Živica ihličnanov — ktorú môj učiteľ volal „slza stromu". Tradičná ľudová medicína ju stáročia používa pri '
         'bolestiach kĺbov. Prirodzený protizápalový prostriedok, ktorý zastavuje rozpad chrupavky a budí regeneráciu')
T[94] = 'Glukozamín a chondroitín — v prirodzenej forme'
T[95] = 'Tehly chrupavky — dávna zásoba prírody, ktorú bunky rozpoznajú a využijú'
T[96] = 'Kyselina hyalurónová — vo forme malých molekúl'
T[97] = 'Vracia kĺbu vlahu — to, čo príroda určila ľudskému telu a čo mu vzal zápal'
T[98] = 'Kolagén typu II a MSM'
T[99] = 'Posilňujú väzy a šľachy okolo kĺbu — prirodzenú ochrannú sieť, ktorá s rokmi slabne'
T[100] = 'Gáfor a horská arnika'
T[101] = 'Okamžitá úľava od bolesti a opuchu — ako hovoril môj učiteľ: „duch stromu, ktorý hasí oheň"'
T[102] = ('Kapsuly obsahujú ešte 14 ďalších vzácnych rastlinných výťažkov, ktoré dedko Ondrej a jeho pomocníci zbierajú '
          'na svahoch Poľany počas šiestich týždňov — každý rok, len raz do roka, keď sú byliny v plnej zrelosti. '
          'Pomery sa dedko Ondrej naučil od svojho učiteľa a každý krok robí vlastnými rukami.')
T[103] = 'Tak vznikli kapsuly Trauflix — vyrobené ručne, z najlepších liečivých bylín spod Poľany'
T[104] = 'Dedko Ondrej Kuchár:'
T[105] = ('— Nerodia sa v laboratóriu. Rodia sa v mojej dielni, tu pod horou. Živicu ihličnanov zbierame ja a moji '
          'pomocníci — v starých smrekových lesoch, na najvyšších hrebeňoch, kde stromy stáročia ronia svoje slzy. Aj '
          'ostatné liečivé byliny zbierame tu, po svahoch. Zber nám zaberie šesť týždňov, lebo každú rastlinu treba '
          'odrezať v okamihu jej zrelosti. Potom kapsuly vyrábame v malých sériách a balíme ich ručne. Denne vieme '
          'urobiť najviac 70 balení — nie viac, lebo by to pokazilo kvalitu.')
T[106] = ('Dielňa dedka Ondreja pod Poľanou. Na policiach visia sušené zväzky šalvie, nechtíka a šípok. Tu vzniká každé '
          'balenie Trauflixu — ručne, v malých sériách.')
T[107] = ('Základom kapsúl je 200 rokov stará receptúra, ktorú mi zanechal môj učiteľ. Povedané súčasným vedeckým '
          'jazykom: kombinácia koncentrovaných rastlinných výťažkov umožňuje, aby sa účinné látky vstrebali do tela a '
          's krvou sa dostali priamo do kĺbového puzdra, kde sa rozpadá chrupavka. Účinok je päťkrát silnejší než '
          'akýkoľvek doplnok z lekárne, lebo príroda presne vie, ako spolupracovať s ľudským telom. A výhoda kapsúl '
          'oproti mastiam a gélom je v tom, že pôsobia zvnútra: účinné látky kolujú s krvou a dostanú sa naraz do '
          'všetkých chorých kĺbov — kolien, chrbta, bedier, rúk aj krku — a nie len tam, kam práve dosiahnete rukou. '
          'Pre starších ľudí, ktorí žijú sami a už sa nevedia zohnúť, to znamená jednoduché užívanie a samostatnosť.')
T[108] = ('Trauflix nie je konkurent. Nechce súťažiť. Chce len pomôcť. Každá zložka — v presnom pomere — budí '
          'regeneráciu chrupavky, obnovu kĺbového mazu a utíšenie zápalu. Je to jediný prostriedok, ktorý pôsobí na '
          'bunkovej úrovni a zároveň dosiahne všetky postihnuté miesta — kolená, chrbát, bedrá, ruky, krk — zvnútra. A '
          'najdôležitejšie: účinkuje aj v sedemdesiatich, osemdesiatich, osemdesiatich piatich rokoch! Mojimi prvými '
          'pacientmi boli tí najstarší — ľudia, ktorých už všetci odpísali.')
T[109] = 'Dedko Ondrej Kuchár:'
T[110] = ('— Prvá žena, ktorej som dal tieto kapsuly, štyri mesiace nevstala z postele. Bola to teta Žofia z Detvy. Na '
          'tretí deň si sama prišla do kuchyne a uvarila mi kávu. Obaja sme plakali. Ona — lebo prvýkrát po mnohých '
          'rokoch ju nebolel každý pohyb. Ja — lebo som v tej chvíli pochopil, že dedičstvo môjho učiteľa žije. Že som '
          'všetky tie roky nepracoval nadarmo.')
T[111] = 'Trauflix vám štyrmi spôsobmi pomáha vrátiť radosť z chôdze — v akomkoľvek veku'
T[112] = 'Štyri hlavné účinky kapsúl Trauflix:'
T[113] = 'Odstránenie bolesti a zápalu'
T[114] = ('Už v prvých 30–45 minútach po užití kombinácia živice ihličnanov, arniky a gáfru zmierňuje bolesť a zápal. '
          'Neblokuje nervový signál (ako obyčajné chemické tabletky) — ale utišuje samotný zdroj zápalu, tam, kde '
          'problém začína.')
T[115] = 'Obnova chrupavky'
T[116] = ('Glukozamín, chondroitín a kolagén typu II sa dostanú do kĺbového puzdra a zobudia bunky chrupavky '
          '(chondrocyty), ktoré začnú tvoriť nové chrupavkové tkanivo. Tento proces sa začína po 3–5 dňoch pravidelného '
          'užívania.')
T[117] = 'Obnova kĺbového mazu'
T[118] = ('Kyselina hyalurónová z malých molekúl sa vstrebáva do tela a dopĺňa kĺbový maz — prirodzené „mazivo" kĺbu. '
          'Vďaka tomu sa kosti už netrú jedna o druhú a pohyb sa stáva ľahkým a bezbolestným.')
T[119] = 'Dlhodobá ochrana a prevencia'
T[120] = ('MSM a minerálny komplex posilňujú väzy a šľachy okolo kĺbu a predchádzajú budúcim poškodeniam. Po 30–60 '
          'dňoch užívania získa kĺb stabilnú ochranu, ktorá vydrží niekoľko mesiacov.')
T[121] = 'Príbehy, ktoré dedko Ondrej rozpráva osobne — o ľuďoch, ktorí znova chodia'
T[122] = 'Dedko Ondrej Kuchár:'
T[123] = ('— Poviem vám o niektorých z tých, ktorých vídam každý týždeň. O ľuďoch, ktorým nikto nedával šancu — ani '
          'lekári, ani rodina. O ľuďoch, ktorí znova chodia.')
T[124] = 'Teta Žofia, 82 rokov, Detva.'
T[125] = ('Štyri mesiace nevstala z postele. Na tretí deň užívania Trauflixu urobila prvé kroky sama. Po 30 dňoch '
          'vychádza na dvor bez pomoci. „To nikto nečakal. Ani ja sama. Dedko Ondrej príde raz za týždeň. Len sa '
          'pozrie, dotkne sa kolena a prikývne."')
T[126] = 'Výsledok po 30 dňoch:'
T[127] = 'Samostatná chôdza, ranná stuhnutosť zmizla, bolesť klesla z 9/10 na 2/10.'
T[128] = 'Dedko Rastislav, 70 rokov, robotník z kameňolomu na dôchodku.'
T[129] = ('Diskopatia, ischias, nevedel stáť dlhšie ako 5 minút. Po 6 týždňoch — vrátil sa do svojej záhrady, obrába '
          'dva záhony denne. „Myslel som, že mám chrbát navždy zničený. Bol som pripravený zmieriť sa so životom '
          'invalida. Mýlil som sa. S kapsulami dedka Ondreja sa cítim o dvadsať rokov mladší."')
T[130] = 'Výsledok po 45 dňoch:'
T[131] = 'Ostrá bolesť v krížoch zmizla, pohyblivosť sa vrátila, prvýkrát po 4 rokoch prespal hlboko celú noc.'
T[132] = 'Prečo Trauflix nie je v lekárňach? A ako sa k nemu dostať?'
T[133] = 'Dedko Ondrej Kuchár:'
T[134] = ('Úprimne povedané, výroba Trauflixu je ťažký a pomalý proces. Suroviny sú vzácne — živicu ihličnanov možno '
          'zbierať len v starých smrekových lesoch, ostatné byliny ručne po svahoch hory, a máme len šesťtýždňové okno '
          'v roku, keď sú rastliny úplne zrelé. Denne vieme v dielni dedka Ondreja urobiť najviac 70 balení. Nedokážeme '
          'uspokojiť všetky dopyty.')
T[135] = ('Prejdú ešte aspoň 2–3 roky, kým sa Trauflix dostane do lekární. Dovtedy je dostupný na celom území krajiny '
          'len cez internet, v podporných programoch, ktoré sa otvárajú dvakrát do roka.')
T[136] = 'Zľava môže dosiahnuť 50 %'
T[137] = '— čo je mimoriadne dôležité pre dôchodcov z dedín na Slovensku, ktorí žijú z nízkeho dôchodku.'
T[138] = ('Keď sa v lekárňach dozvedeli, že tieto kapsuly naozaj účinkujú — aj pri pokročilej artróze a diskopatii — '
          'chceli za ne pýtať 129 EUR za balenie. Povedal som im: „Nepracujem pre peniaze. Môj učiteľ mi zadarmo dal '
          'všetko, čo vedel. Neokradnem slovenských dôchodcov." Lekárne ma odmietli. O niekoľko dní ma začali '
          'navštevovať ľudia z hygieny. Žiadali dokumenty. Chceli ma pokutovať. Ale nevzdal som sa. Vtedy sa v mojom '
          'živote objavil mladý muž z Bratislavy. Jeho matku som tri roky predtým vyliečil z ťažkej artrózy kolien — '
          'jeho aj jeho matku som už dávno zabudol. Teraz sa vrátil. Povedal: „Dedko Ondrej, ty tu v horách robíš '
          'zázraky vlastnými rukami. Ale na Slovensku sú tisíce trpiacich ľudí, ktorí sa sem nikdy nedostanú. Dovoľ mi '
          'pomôcť." Zariadil, aby sa kapsuly, vyrobené mojím náradím, balili v čistej dielni do sterilných balení, aby '
          'ich kuriérska služba doručovala po celej krajine a aby malý tím odpovedal na telefóny. Ja ich stále vyrábam '
          'tu, vlastným tempom. On sa stará len o to, aby sa dostali k tým, ktorí ich potrebujú.')
T[139] = 'Cena, ku ktorej sme dospeli:'
T[140] = 'Cena, ktorú žiadali lekárne'
T[141] = '129 EUR'
T[142] = 'Cena v iných krajinách regiónu'
T[143] = '99 EUR'
T[144] = 'Cena, ktorú ponúkame dnes'
T[145] = '78 EUR'
T[146] = 'So zľavou pre čitateľov dnes'
T[147] = '39 EUR'
T[148] = ('Prosím vás: NEZMEŠKAJTE TENTO PROGRAM! Nielen pre seba — ale aj pre rodičov, starých otcov a mamy, blízkych '
          'príbuzných, ktorí možno trpia v tichosti. Alebo pre tých, ktorí sú už v domovoch dôchodcov, sami, a ktorým '
          'nikto nič neposiela. Buďte ten, kto urobí rozdiel.')
T[149] = 'Na objednávku použite formulár nižšie.'
T[150] = 'Posledná príležitosť získať tento rok Trauflix — pre seba alebo pre niekoho blízkeho, kto trpí v tichosti'
T[151] = 'Dedko Ondrej Kuchár:'
T[152] = ('— Rezervoval som 20 000 balení výhradne pre čitateľov tohto portálu. Každý obyvateľ Slovenska starší ako 40 '
          'rokov môže získať')
T[153] = 'zľavu 50 %'
T[154] = ', ale program sa zatvára'
T[155] = '.'
T[156] = ('Nečakajte, kým nebudete vládať vyjsť po schodoch. Kým vám kolená konečne nevypovedia. Kým sa vám chrbát '
          'nezablokuje. A predovšetkým — nečakajte, kým sa nestanete „príťažou" pre najbližších. Jedna kúra zobudí '
          'prirodzenú regeneráciu chrupavky — a od tej chvíle telo pracuje samo. Netreba sa liečiť celý život, netreba '
          'chemické tabletky, niet bolesti, ktorá sa vracia. Jeden krok a vaše telo si spomenie, ako sa žije.')
T[157] = ('Napíšte svoje meno a telefónne číslo. Poradca vám zavolá, vyberie vhodný program a zariadi doručenie do 2–3 '
          'dní kuriérskou službou priamo na vašu adresu, po celom Slovensku.')
T[158] = ('S láskou a starostlivosťou — dedko Ondrej Kuchár. Starajte sa o svojich najbližších. Možno jediné, čo '
          'potrebujú, je vedieť, že nie sú zabudnutí.')
T[159] = 'Aktualizované:'
T[160] = ':'
T[161] = 'Vzhľadom na mimoriadny záujem sa zásoby môžu minúť rýchlejšie, než sa predpokladalo! Dnes —'
T[162] = '— je posledný deň programu'
T[163] = 'alebo do vyčerpania zásob.'
T[164] = 'Pozor! Nezatvárajte a neobnovujte stránku, inak bude vaše balenie Trauflixu ponúknuté inému človeku!'
T[165] = 'Môžete sa zúčastniť ponuky — vaše miesto je rezervované:'
T[166] = 'Č.'
T[167] = '19'
T[168] = '974'
T[169] = 'Oficiálny objednávkový formulár'
T[170] = 'Č.'
T[171] = '19'
T[172] = '974'
T[173] = '/'
T[174] = '20 000'
T[175] = 'Ak chcete získať'
T[176] = 'zľavu 50 %'
T[177] = 'napíšte svoje meno a telefónne číslo do políčok nižšie a stlačte tlačidlo „OBJEDNAŤ".'
T[178] = 'Dostupné:'
T[179] = '33'
T[180] = '/1000'

# ---------- 181–273 ----------
T[181] = '78 EUR'
T[182] = '39 EUR'
T[183] = 'Meno'
T[184] = 'Telefónne číslo'
T[185] = 'OBJEDNAŤ TERAZ'
T[186] = '✔️ Garantované doručenie certifikovaným kuriérom'
T[187] = 'priamo na vami uvedenú adresu'
T[188] = 'KOMENTÁRE'
T[189] = 'Andrea Debnárová'
T[190] = 'Pred 2 hodinami'
T[191] = ('Plakala som, keď som to čítala. Mama má 76 rokov, už dva roky je v domove dôchodcov v Banskej Bystrici — '
          'práve preto, že ju kolená zradili a ja som sa o ňu nevedela postarať. To je moja najväčšia vina. Objednala '
          'som jej Trauflix. Dúfam, že nie je neskoro. Daj Boh, aby to zabralo.')
T[192] = 'Viera Kovaľová'
T[193] = 'Pred 5 hodinami'
T[194] = ('Minulý piatok mi prišiel Trauflix. Ráno a večer beriem kapsuly. Za 5 dní bolesť výrazne poľavila, viem zísť '
          'dole schodmi bez držania sa zábradlia! Príbeh o dedkovi Ondrejovi ma presvedčil objednať. Výnimočný človek, '
          'naozaj.')
T[195] = 'Stanislava Hajdučková'
T[196] = 'Pred 8 hodinami'
T[197] = ('Mám 69 rokov. Štyri roky som sa trápila s chrbtom — diskopatia a ischias. Nevedela som sa ani zohnúť, aby '
          'som si zaviazala topánky. Lekári mi predpísali protizápalové lieky, ktoré mi zničili žalúdok. Po 3 týždňoch '
          's Trauflixom bolesť takmer zmizla. Sama chodím na trh, varím. Vrátila som si svoj život, vďaka Bohu.')
T[198] = 'Gabriel Kráľ'
T[199] = 'Pred 12 hodinami'
T[200] = ('Pracujem 10 hodín denne v kancelárii v Bratislave. Chrbát a krk už nereagujú. Lekár povedal: „Alebo meníš '
          'prácu, alebo operácia." Vybral som si kapsuly Trauflix. Po 5 týždňoch — ani stopa po bolesti. A obrovská '
          'úcta k dedkovi Ondrejovi — vo svete, kde všetci chcú peniaze, on kráča pešo k zabudnutým starčekom v horách.')
T[201] = 'Lýdia Nováková'
T[202] = 'Pred 14 hodinami'
T[203] = ('Úprimne, neverila som. Toľko vecí sa na internete reklamuje, že som stratila dôveru. Tento text som si '
          'prečítala len preto, že moja svokra nevie chodiť a ja som zúfalá. Objednala som s myšlienkou „ak to '
          'nezaberie, stratím 39 €". Prešli 3 týždne. Svokra včera sama vstala z kresla! Moja svokra! Ktorá nevstala 8 '
          'mesiacov. Teraz neviem, čo povedať. Píšem pre tých, ktorí pochybujú ako ja.')
T[204] = 'Dušan Michalko'
T[205] = 'Pred 16 hodinami'
T[206] = ('Objednal som 3 balenia — pre seba (kolená), pre ženu (ruky, artritída) a pre ženinho otca v domove '
          'dôchodcov. Nevieme ho často navštevovať, aspoň mu pošleme to, čo potrebuje. Dúfam, že pomôže aj jemu. Ďakujem '
          'za tento článok.')
T[207] = 'Danica Ružičková'
T[208] = 'Pred 18 hodinami'
T[209] = ('Rozmýšľam, či objednať pre otca. Už 3 roky je v domove dôchodcov — kolená vôbec nefungujú. Vzdal sa, sotva '
          'rozpráva. Myslíte, že Trauflix môže pomôcť aj v 78 rokoch?')
T[210] = 'Marianna Holubová'
T[211] = 'Pred 17 hodinami'
T[212] = ('Danica, moja mama má 82 rokov! Ťažká artritída v oboch kolenách, nevstávala z postele. Už 2 mesiace používa '
          'Trauflix — teraz sama vychádza na dvor. Nepreháňam. A to najkrajšie: keď som ju navštívila, čakala ma stojac '
          'vo dverách! Plakali sme spolu. Objednaj bez váhania, tvoj otec si zaslúži šancu.')
T[213] = 'Zdenko Sabol'
T[214] = 'Pred 15 hodinami'
T[215] = ('Danica, objednajte bez obáv. Mám 78 rokov, bol som krok od invalidného vozíka — koxartróza. Trauflix ma za 2 '
          'mesiace postavil na nohy. Doslova. Otec si zaslúži viac než domov dôchodcov.')
T[216] = 'Jolana Andrejčíková'
T[217] = 'Pred 20 hodinami'
T[218] = ('Týždeň beriem kapsuly ráno a večer. Ráno už nie som „drevená palica". Viem sa zohnúť, viem vstať bez „joj". '
          'Objednala som aj susede, má 73 rokov a býva sama, pri chôdzi sa drží stien.')
T[219] = 'Zuzana Vrabcová'
T[220] = 'Pred 1 dňom'
T[221] = ('Priznávam — tento článok som čítala s nedôverou. Mám skúsenosti s výrobkami, ktoré sľubujú všetko. Ale '
          'príbeh o dedkovi Ondrejovi ma získal a rozhodla som sa skúsiť to, lebo kolená ma trápia už 5 rokov. Po '
          'mesiaci — viem kopať v záhrade! Nehovorím, že je to zázrak. Hovorím, že to účinkuje. Dajte tomu šancu.')
T[222] = 'Štefánia Tomčíková'
T[223] = 'Pred 1 dňom'
T[224] = ('Mám 82 rokov. Vlani som sa nevedela ani sama dostať na toaletu. Deti hovorili, že ma dajú do domova '
          'dôchodcov. Skúsila som Trauflix — bez veľkých nádejí. A ÚČINKUJE!!! Chodím sama, obliekam sa sama, sama '
          'dôjdem ku dverám. Deti domov dôchodcov už nespomínajú. To je moje najväčšie šťastie.')
T[225] = 'Branislav Pavlík'
T[226] = 'Pred 1 dňom'
T[227] = ('Moja žena nevedela zísť ani dole schodmi. Držala sa steny a plakala od bolesti. Myslel som, že ju strácam — '
          'nie kvôli chorobe, ale kvôli zúfalstvu. Objednal som Trauflix so zľavou. Po 4 týždňoch včera sama šla na '
          'trh a vrátila sa s kvetmi. S kvetmi! Ďakujem zo srdca.')
T[228] = 'Jarmila Kremeňová'
T[229] = 'Pred 1 dňom'
T[230] = ('Objednala som štyri balenia — pre mamu (v domove, kolená), pre otca (v domove, chrbát) a dve pre seba (ruky, '
          'artritída v prstoch, nevedela som písať). Príbehy z článku ma dojali. Už nemám výhovorky.')
T[231] = 'Slávka Gajdošová'
T[232] = 'Pred 2 dňami'
T[233] = ('Dostala som Trauflix — kuriér ho doručil za 2 dni! Kapsuly som už odovzdala mame v domove. V srdci mám '
          'nádej. Tento článok posielam aj personálu — možno zavolajú dedkovi Ondrejovi.')
T[234] = 'Igor Lazár'
T[235] = 'Pred 2 dňami'
T[236] = ('Hľadal som Trauflix po lekárňach — nemajú ho. Povedali, že ho treba objednať na tejto stránke. Dúfam, že ešte '
          'je. Môj dedko ho súrne potrebuje — má 81 rokov a už nevie chodiť.')
T[237] = 'Marta Vrabcová'
T[238] = 'Pred 3 dňami'
T[239] = ('Otázka pre tých, ktorí ho už užívajú: koľkokrát denne sa kapsuly berú a ako dlho trvá jedna kúra? V článku '
          'som to čítala narýchlo a nezapamätala som si to.')
T[240] = 'Andrej Poliak'
T[241] = 'Pred 3 dňami'
T[242] = ('Marta, vyššie v texte je napísané: najkratšia kúra, ktorú dedko Ondrej odporúča, je 30 dní, pri ťažších '
          'problémoch 60 alebo 90 dní. Kapsuly sa užívajú ústami a zapíjajú vodou. Ak si nie ste istá, opýtajte sa '
          'poradcu, keď vám zavolá — mne všetko vysvetlil cez telefón.')
T[243] = 'Fotografia, ktorú priložil čitateľ.'
T[244] = 'Ivana Savková'
T[245] = 'Pred 4 dňami'
T[246] = 'Treba niečo platiť vopred, keď sa zadá objednávka na tejto stránke? Nerada dávam údaje o karte.'
T[247] = 'Boris Rakovský'
T[248] = 'Pred 4 dňami'
T[249] = ('Nie, na stránke sa vopred neplatí nič — do formulára napíšete len meno a telefónne číslo. Platíte pri '
          'prevzatí, kuriérovi. Tak je to napísané aj pod formulárom.')
T[250] = 'Terézia Kosová'
T[251] = 'Pred 5 dňami'
T[252] = 'Čo presne je vo vnútri? Pýtam sa preto, že som citlivá na niektoré byliny.'
T[253] = 'Alojz Hrnčiar'
T[254] = 'Pred 5 dňami'
T[255] = ('Zložky sú vymenované vyššie v článku: živica ihličnanov, glukozamín a chondroitín, kyselina hyalurónová, '
          'kolagén typu II a MSM, gáfor a horská arnika. Ak ste na niečo citlivá, povedzte to svojmu lekárovi — tu to '
          'za neho nikto posúdiť nemôže.')
T[256] = 'Pred'
T[257] = 'Po'
T[258] = '*'
T[259] = 'Pridať profilovú fotografiu'
T[260] = 'Pridať fotografiu'
T[261] = 'ODOSLAŤ'
T[262] = '🛡️'
T[263] = 'Certifikovaná kvalita'
T[264] = '🚚'
T[265] = 'Doručenie za 2–3 dni'
T[266] = '⚕️'
T[267] = 'Bez receptu'
T[268] = '🔒'
T[269] = 'Bezpečná objednávka'
T[270] = '© ZdravieInfo Slovensko — špeciálna reportáž'
T[271] = 'Informácie na tejto stránke majú informatívny charakter a nenahrádzajú lekárske vyšetrenie.'
T[272] = '{_box:2sHZz2rc}'
T[273] = '{_box:2sHZz2rc}'
