# -*- coding: utf-8 -*-
import sys; sys.path.insert(0,'/tmp/claude-0/tea')
from repl import apply

R = [
 (r'Sastav prirodnih Parazol kapsula po receptu',        'Sastav biljnog čaja Parazol po receptu'),
 (r'u prirodne kapsule dostupne svakome',                'u biljni čaj dostupan svakome'),
 (r'— prirodne kapsule koje djeluju upravo tamo',        '— biljni čaj koji se pije i djeluje upravo tamo'),
 (r'U sastavu Parazol kapsula nalazi se',                'U sastavu čaja Parazol nalazi se'),
 (r'Rezultat — kapsule koje djeluju',                    'Rezultat — čaj koji djeluje'),
 (r'ali mogu da se dostave u svaki dom',                 'ali može da se dostavi u svaki dom'),
 (r'Uzimate ih dva puta dnevno',                         'Pijete ga dva puta dnevno'),
 (r'kod Parazol kapsula jeste to što one ne samo da ublažavaju simptome — nego aktiviraju',
                                                         'kod čaja Parazol jeste to što on ne samo da ublažava simptome — nego aktivira'),
 (r'Kapsule se uzimaju, a mikroekstrakti',               'Čaj se pije, a mikroekstrakti'),
 (r'Već od prve kapsule aktivne komponente',             'Već od prve šolje aktivne komponente'),
 (r'omogućava kapsulama da dostave aktivne materije',    'omogućava čaju da dostavi aktivne materije'),
 (r'Uzimajte kapsule dva puta dnevno',                   'Pijte čaj dva puta dnevno'),
 (r'donosio Parazol kapsule iz',                         'donosio čaj Parazol iz'),
 (r'Dva mjeseca uzimanja —',                             'Dva mjeseca pijenja —'),
 (r'Sa Parazol kapsulama — 30 dana uzimanja',            'Sa čajem Parazol — 30 dana pijenja'),
 (r'Uzimao je Parazol kapsule svaki dan',                'Pio je čaj Parazol svaki dan'),
 (r'pakovanja Parazol kapsula posebno za',               'pakovanja čaja Parazol posebno za'),
 (r'Parazol kapsule rezervisane za vas biće ponuđene',   'čaj Parazol rezervisan za vas biće ponuđen'),
 (r'Deset dana uzimam kapsule ujutru i uveče',           'Deset dana pijem čaj ujutru i uveče'),
 (r'Uzimam kapsule 5 sedmica',                           'Pijem čaj 5 sedmica'),
 (r'poslije početka uzimanja kapsula',                   'poslije početka pijenja čaja'),
 (r'Ali Parazol kapsule — to je sasvim nešto drugo',     'Ali čaj Parazol — to je sasvim nešto drugo'),
 (r'Nastavljam sa uzimanjem',                            'Nastavljam da ga pijem'),
 (r'Počela sam da uzimam Parazol kapsule dva puta dnevno','Počela sam da pijem čaj Parazol dva puta dnevno'),
 (r'Daje mi kapsule svako jutro i veče',                 'Kuva mi čaj svako jutro i veče'),
 (r'Tri sedmice sa kapsulama',                           'Tri sedmice sa čajem'),
 (r'da probamo Parazol kapsule',                         'da probamo čaj Parazol'),
 (r'Davao sam joj dva puta dnevno',                      'Kuvao sam joj ga dva puta dnevno'),
 (r'Odmah sam počela da uzimam kapsule',                 'Odmah sam počela da pijem čaj'),
 (r'Dvije sedmice uzimam dva puta dnevno',               'Dvije sedmice ga pijem dva puta dnevno'),
 (r'Parazol kapsule jedina su stvar koja mi je dala',    'Čaj Parazol jedina je stvar koja mi je dala'),
 (r'REZULTAT — uzimam dva puta dnevno',                  'REZULTAT — pijem ga dva puta dnevno'),
 (r'Uzimam Parazol kapsule 50 dana',                     'Pijem čaj Parazol 50 dana'),
 (r'naručila Parazol kapsule i natjerala me da probam — davala mi je ujutru i uveče',
                                                         'naručila čaj Parazol i natjerala me da probam — kuvala mi ga je ujutru i uveče'),
 (r'tri pakovanja kapsula, za pun kurs',                 'tri pakovanja čaja, za pun kurs'),
]
apply('/root/.claude/uploads/ebcc1709-ea34-5dd5-ad04-bda3b7359ce7/3a729671-index.html',
      '/tmp/claude-0/tea/ME.html', R)
